- webdev/bin/webdev.dart
- webdev/lib/src/command/build_command.dart
- webdev/lib/src/webdev_command_runner.dart
- webdev/lib/webdev.dart
- webdev/pubspec.yaml
Simply passes all args to build_runner.
> Initial support for build_runner build

- webdev/lib/src/command/build_command.dart
- webdev/lib/src/command/build_runner_command_base.dart
- webdev/lib/src/command/serve_command.dart
- webdev/lib/src/webdev_command_runner.dart
Refactor shared arguments into abstract class.
> Add initial support for build_runner serve

- webdev/README.md
- webdev/example/lib/app_component.css
- webdev/example/lib/app_component.dart
- webdev/example/lib/app_component.html
- webdev/example/lib/src/hello_world/hello_world.css
- webdev/example/lib/src/hello_world/hello_world.dart
- webdev/example/lib/src/hello_world/hello_world.html
- webdev/example/pubspec.yaml
- webdev/example/web/index.html
- webdev/example/web/main.dart
- webdev/example/web/styles.css
- webdev/lib/src/command/build_command.dart
- webdev/lib/src/command/build_runner_command_base.dart
- webdev/lib/src/command/serve_command.dart
- webdev/pubspec.yaml
Avoids TTY issues and hacks.
Add example angular app to experiment with.
> Update build and serve commands to run in an isolate

- webdev/bin/webdev.dart
- webdev/lib/src/command/build_command.dart
- webdev/lib/src/command/build_runner_command_base.dart
- webdev/lib/src/command/serve_command.dart
- webdev/lib/src/pubspec.dart
- webdev/lib/src/util.dart
- webdev/lib/src/webdev_command_runner.dart
- webdev/pubspec.yaml
- webdev/test/integration_test.dart
Also change the commands to return the exitCode from build_runner
> Initial validation of build_runner dependency and version

- webdev/CHANGELOG.md
- webdev/lib/src/pubspec.dart
- webdev/pubspec.yaml
- webdev/test/integration_test.dart
Going for a more general model
> Remove check on web_dev_compilers

- webdev/CHANGELOG.md
- webdev/lib/src/pubspec.dart
- webdev/test/integration_test.dart
Much more robust than just checking for a .packages file
> Use `pub deps` to validate target directory

- webdev/pubspec.yaml
- webdev/test/integration_test.dart
Closes https://github.com/dart-lang/webdev/issues/23
> Ensure pub/dart invoked by tests are the same as the top-level SDK

- webdev/CHANGELOG.md
- webdev/lib/src/command/serve_command.dart
- webdev/pubspec.yaml
Allows you so specify a directory:port when running the serve command.
> Pass the remaining args when running serve

- webdev/test/e2e_test.dart
- webdev/test/test_utils.dart
Waiting on https://github.com/dart-lang/webdev/pull/35 to land
> Add an integration test for serve

- webdev/CHANGELOG.md
- webdev/lib/src/command/build_command.dart
- webdev/lib/src/command/command_base.dart
> Set `--fail-on-severe` always for `webdev build`.

- webdev/CHANGELOG.md
- webdev/README.md
- webdev/bin/webdev.dart
- webdev/lib/src/command/command_base.dart
- webdev/lib/src/command/serve_command.dart
- webdev/lib/src/pubspec.dart
- webdev/test/integration_test.dart
Also moved the arg to only be supported for the serve command.
> restore original build_runner constraints, fail on --live-reload if you are on <0.10.1

- webdev/CHANGELOG.md
- webdev/lib/src/command/command_base.dart
- webdev/pubspec.yaml
This part of the process can take 7+ seconds. Until we find a way to
bring that down, it's good to minimize the time a user waits for any
output
> feature: print `Creating build script` at the start of execution

- webdev/lib/src/command/command_base.dart
- webdev/lib/src/command/serve2_command.dart
- webdev/lib/src/serve/daemon_client.dart
- webdev/lib/src/serve/handlers/asset_handler.dart
- webdev/lib/src/serve/handlers/webdev_handler.dart
- webdev/lib/src/serve/server_manager.dart
- webdev/lib/src/serve/webdev_server.dart
- webdev/lib/src/webdev_command_runner.dart
- webdev/pubspec.yaml
- webdev/test/e2e_test.dart
- Create new command `serve2` which will eventually replace `serve`
- The new command will:
- be hidden for the time being
- connect to the build daemon
- create a proxy server for each requested build target 
- this server forward requests to the daemon asset server
- in the future this server will have hooks for hot reload / hot restart
- Add and E2E integration test
- This test is expected to fail until `package:build_runner` version `1.2.1` is released
> Integrate WebDev and build_runner daemon

- webdev/lib/src/command/serve2_command.dart
- webdev/lib/src/serve/handlers/build_results_handler.dart
- webdev/lib/src/serve/handlers/webdev_handler.dart
- webdev/lib/src/serve/middlewares/reload_middleware.dart
- webdev/lib/src/serve/reload_client/live_reload_client.js
- webdev/lib/src/serve/server_manager.dart
- webdev/lib/src/serve/webdev_server.dart
- webdev/pubspec.yaml
- webdev/test/handlers/build_results_handler_test.dart
- webdev/test/middlewares/reload_middleware_test.dart
- Add `live-reload` argument to `serve2` command
- Create a new build results handler which forwards results over a websocket
- Create middleware to inject js which creates a websocket connection for build result updates
- Add corresponding tests
Closes https://github.com/dart-lang/webdev/issues/107
> Enable live reload through build daemon

- webdev/CHANGELOG.md
- webdev/lib/src/serve/middlewares/reload_middleware.dart
- webdev/test/middlewares/reload_middleware_test.dart
There was an additional edge case here when going from non-hot-reload to hot-reload.
This fixes it by modifying the if-none-match header before forwarding to the proxy, which effectively disables caching for the bootstrap.js files.
Also fixes https://github.com/dart-lang/webdev/issues/120
> Fix hot-reload caching bug

- webdev/CHANGELOG.md
- webdev/lib/src/command/serve_command.dart
- webdev/lib/src/serve/daemon_client.dart
- webdev/lib/src/serve/utils.dart
- webdev/pubspec.yaml
Previously the daemon command handled color logging which proved to be problematic. Initial log messages from outside the daemon command, e.g. the generate build script action, were not colored correctly. `package:build_runner` was updated to always write simplified logs through the daemon command. `package:build_daemon` was updated to easily handle initial logs, those prior to the daemon client connection. 
For this change: rev to the latest `package:build_daemon` and migrate color logging over to webdev which ensures consistency of terminal log messages.
> Improved serve logging

- webdev/lib/src/serve/chrome.dart
- webdev/pubspec.yaml
- webdev/test/chrome_test.dart
Add basic support for connecting the webkit inspector. What we expose through the Chrome class will almost certainly change.
Towards  https://github.com/dart-lang/webdev/issues/133
> Support connecting through the webkit inspection protocol

- webdev/test/serve/chrome_test.dart
The Chrome instance can start with multiple extensions so instead check to make sure a tab with the supplied URL is loaded. Also move the test under the serve folder.
> Fix Chrome test flakiness

- analysis_options.yaml
- dwds/bin/proxy.dart
- dwds/lib/src/chrome_proxy_service.dart
- dwds/pubspec.yaml
- dwds/tool/standalone_proxy.dart
You can use this to try hooking up web apps to the Dart DevTools ui, which helps with discovering what the missing apis are.
> add a standalone dwds proxy binary for debugging

- webdev/README.md
- webdev/lib/src/command/configuration.dart
- webdev/lib/src/command/serve_command.dart
- webdev/lib/src/serve/chrome.dart
- webdev/lib/src/serve/webdev_server.dart
- webdev/pubspec.yaml
- webdev/test/serve/chrome_test.dart
- Add new flag `--chrome-debug-port` to either specify a debug port for Chrome to use or an existing port to connect to
- Rely on latest `package:build_daemon` so that we can close the client if there is an issue
Towards: https://github.com/dart-lang/webdev/issues/133
> Chrome Debug Port

- dwds/example/hello_world/index.html
- dwds/example/hello_world/main.dart
- dwds/lib/src/chrome_proxy_service.dart
- dwds/pubspec.yaml
- dwds/test/chrome_proxy_service_test.dart
This allows posting of events through dart:debugger and registering of extensions, but we don't yet have a way of invoking extensions.
> implement Extension stream an  ServiceExtensionAdded event for Isolate stream

- dwds/lib/src/chrome_proxy_service.dart
- dwds/test/chrome_proxy_service_test.dart
We need to have these return success for devtools to not complain, but we won't actually implement them yet. I filed https://github.com/dart-lang/webdev/issues/168 to track investigating/implementing them.
> stub out the GC/Timeline streams

- dwds/lib/service.dart
- dwds/lib/src/helpers.dart
- dwds/tool/standalone_proxy.dart
- webdev/lib/src/serve/handlers/dev_handler.dart
- Expose `DebugService` as the public API from `DWDS`
- Use the new public API from `WebDev`
- Add some additional log messages when spawning the service
- Update the `standalone_proxy` to use the new public API
> Refactor DebugService

- dwds/example/hello_world/main.dart
- dwds/lib/src/chrome_proxy_service.dart
- dwds/test/chrome_proxy_service_test.dart
This lights up all the buttons in the flutter inspector, and most of them even work :fireworks: :champagne: :tada: .
Also fixed up the `callServiceExtension` method to auto-serialize the keys and values if they aren't strings (The `ServiceExtensionHandler` only accepts a `Map<String, String>`, but the protocol allows any type of Map).
> populate Isolate.extensionRPCs on initial connection

- dwds/example/hello_world/main.dart
- dwds/lib/src/chrome_proxy_service.dart
- dwds/test/chrome_proxy_service_test.dart
~This doesn't fully appear to get things working yet (the goal is to have it so if you inspect an element in the app it would select it in devtools), but the basic events should now be working and some more investigation is needed.~
This now selects the correct object in the widget inspector when you inspect in the app.
> Support the `Inspect` events from the `Debug` stream.

- .gitignore
- dwds/lib/service.dart
- dwds/lib/src/chrome_proxy_service.dart
- dwds/pubspec.yaml
- dwds/test/chrome_proxy_service_test.dart
- webdev/lib/src/serve/handlers/asset_handler.dart
- webdev/lib/src/serve/handlers/dev_handler.dart
- webdev/lib/src/serve/webdev_server.dart
- Implement `getVersion()`
- Implement `getScripts()`
- Implement `getObject` => Script (with source)
- Update `AssetHandler` to return an asset from a relative path
- Plumb `AssetHandler` through to `DevHandler`
- Add corresponding tests
> Enable getScripts, getVersion and getScripts => Script

- .travis.yml
- dwds/test/chrome_proxy_service_test.dart
- mono_repo.yaml
- webdev/test/serve/injected/devtools_test.dart
- webdev/test/serve/injected/reload_test.dart
Start `ChromeDriver` as a part of the test and throw with a helpful error if it isn't found.
Closes https://github.com/dart-lang/webdev/issues/187
> Make local testing easier

- webdev/lib/src/serve/chrome.dart
When the application loses focus, by default Chrome will slow down timers. This greatly impacts the various evaluation calls coming from DevTools. This simple fix will improve performance a thousand fold. :tada:
> Improve DevTools performance

- dwds/lib/src/chrome_proxy_service.dart
- Use a map of `ObjectId` to `LibraryRef`
- Actually store the `getLibrary` work within a map of `ObjectId` to `Library`
This improves performance, especially for the `debugger` page which calls `getScripts` and `getScript` often. However there is still significant performance issues with the Inspector page. Notice that each button sequentially "lights up" with a second delay. This may be related to https://github.com/dart-lang/sdk/issues/36143 
Edit:
performance issue was resolved in: https://github.com/dart-lang/webdev/pull/194
> Refactor getLibrary and getLibraryRefs

- webdev/lib/src/command/serve_command.dart
- webdev/lib/src/serve/debugger/devtools.dart
- webdev/lib/src/serve/handlers/dev_handler.dart
- webdev/lib/src/serve/utils.dart
- webdev/lib/src/serve/webdev_server.dart
WebDev called `print` directly a handful of times. For a consistent logging experience we should color the log with a level.
> Consistent logging

- dwds/lib/service.dart
- dwds/lib/src/chrome_proxy_service.dart
- dwds/test/chrome_proxy_service_test.dart
- webdev/lib/src/serve/handlers/dev_handler.dart
- webdev/lib/src/serve/injected/client.dart
- webdev/lib/src/serve/injected/client.js
- webdev/test/serve/injected/devtools_test.dart
Webdev now connects to its own vm service as a client and registers the `hotReload` and `reloadSources` (hot reload) service extensions (`reloadSources` returns an unsupported error for now). 
Exposes a `$dartHotRestart` global function that can be invoked on the page to perform a hot restart. This exists regardless of the command line args provided to webdev.
This also removes support for the `registerService` method and `_Service` streams from the proxy itself - these will now be handled by the VmServerConnection, see https://github.com/dart-lang/vm_service_drivers/pull/226. 
Closes https://github.com/dart-lang/webdev/issues/136
> Enable hot reload via a service extension

- webdev/lib/src/command/daemon_command.dart
- webdev/lib/src/daemon/daemon.dart
- webdev/lib/src/daemon/daemon_domain.dart
- webdev/lib/src/daemon/domain.dart
- webdev/lib/src/daemon/utilites.dart
- webdev/lib/src/webdev_command_runner.dart
- webdev/test/daemon/daemon_domain_test.dart
WebDev will initially support Flutter oriented IDE plugins through the daemon protocol outlined here:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/doc/daemon.md
Only a subsection of the protocol will be implemented. This command is a stop gap solution and is not intended to be supported long term. This code is heavily influenced by the logic in  `flutter_tools` here:
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/daemon.dart
> Daemon command boilerplate

- dwds/lib/src/chrome_proxy_service.dart
- dwds/test/chrome_proxy_service_test.dart
- webdev/lib/src/serve/handlers/dev_handler.dart
- webdev/test/serve/injected/devtools_test.dart
Part of https://github.com/dart-lang/webdev/issues/202
- Adds `createIsolate` and `destroyIsolate` methods to `ChromeProxyService`.
- Update webdev to invoke these before/after a hot restart
> Isolate refactor

- dwds/example/hello_world/index.html
- dwds/lib/service.dart
- dwds/lib/src/chrome_proxy_service.dart
- dwds/test/chrome_proxy_service_test.dart
- webdev/lib/src/daemon/app_domain.dart
- webdev/lib/src/pubspec.dart
- webdev/lib/src/serve/data/connect_request.dart
- webdev/lib/src/serve/data/connect_request.g.dart
- webdev/lib/src/serve/data/devtools_request.dart
- webdev/lib/src/serve/data/devtools_request.g.dart
- webdev/lib/src/serve/data/serializers.dart
- webdev/lib/src/serve/data/serializers.g.dart
- webdev/lib/src/serve/handlers/dev_handler.dart
- webdev/lib/src/serve/injected/client.dart
- webdev/lib/src/serve/injected/client.js
- webdev/lib/src/serve/middlewares/injected_middleware.dart
- webdev/lib/src/serve/webdev_server.dart
- webdev/test/daemon/app_domain_test.dart
- webdev/test/integration_test.dart
- webdev/test/serve/middlewares/injected_middleware_test.dart
- Depend on latest `build_web_compilers` version `1.2.0` which has the `main()` injection hook
- Update WebDev to now embed an `appId` in each application
- Updated `ChromeProxyService` to connect to an existing application using an `appId`
- The connection simply evaluates an expression on each tab looking for the correct `appId`
- Update `App Domain` to now send the `.started` event
> App Domain Event .started

- webdev/lib/src/serve/dev_workflow.dart
- webdev/lib/src/serve/utils.dart
Messages that end in a new line are not erased. However, messages that contain multiple lines and not a trailing new line should not be erased. This fixes the double new line logging weirdness. Also add a new line to the devtools message so that sticks around.
> Fix multiline messages

- webdev/lib/src/daemon/app_domain.dart
- webdev/test/daemon/app_domain_test.dart
Closes https://github.com/dart-lang/webdev/issues/220
> Hot Restart progress events

- dwds/example/hello_world/index.html
- dwds/lib/service.dart
- dwds/lib/src/chrome_proxy_service.dart
- dwds/test/chrome_proxy_service_test.dart
- webdev/lib/src/daemon/app_domain.dart
- webdev/lib/src/serve/data/connect_request.dart
- webdev/lib/src/serve/data/connect_request.g.dart
- webdev/lib/src/serve/data/devtools_request.dart
- webdev/lib/src/serve/data/devtools_request.g.dart
- webdev/lib/src/serve/data/serializers.dart
- webdev/lib/src/serve/data/serializers.g.dart
- webdev/lib/src/serve/handlers/dev_handler.dart
- webdev/lib/src/serve/injected/client.dart
- webdev/lib/src/serve/injected/client.js
- webdev/test/serve/injected/devtools_test.dart
Fixes https://github.com/dart-lang/webdev/issues/202
Note that I added an app instance id - this allows us to unambiguously identify the correct tab for a given instance of an app, separate from the app id which is consistent across all instances.
We cache the debug services per app ID and keep them running, but we only allow debugging one instance of a given app at a time.
The rough logic here is as follows:
- When a new client connects
- if we have cached debug services for the app
- if the old tab connection is still connected to the correct tab (page refresh case)
- reconnect and create the new isolate
- else
- don't do anything
- else
- don't do anything
- When a client disconnects (from the SSE connection)
- destroy the isolate (but leave the proxy services running).
- When a client …
> Handle page refreshes and opening in new tabs

- webdev/lib/src/serve/injected/client.dart
- webdev/pubspec.yaml
Will re-run travis after https://github.com/dart-lang/sse/pull/6 is merged and published, at which point it should be happy.
Fixes https://github.com/dart-lang/webdev/issues/224
> add missing uuid dependency, require 2.0

- webdev/lib/src/command/daemon_command.dart
- webdev/lib/src/command/serve_command.dart
- webdev/lib/src/daemon/app_domain.dart
- webdev/lib/src/serve/dev_workflow.dart
- webdev/lib/src/serve/handlers/dev_handler.dart
- webdev/lib/src/serve/logging.dart
- webdev/lib/src/serve/utils.dart
- webdev/test/daemon/app_domain_test.dart
- No longer plumb the `logHandler` throughout `DevWorkflow` simply make it globally available.
- Override the `logHandler` in the `Daemon` command.
- This fixes an issue where some logs were not captured from the `DevHandler`.
- Actually enable verbose logs in `webdev serve`
- Add additional progress logs for the daemon command
Closes https://github.com/dart-lang/webdev/issues/219 
Closes https://github.com/dart-lang/webdev/issues/220
> Updated logs

- webdev/test/e2e_test.dart
I'm at a loss as to what caused this change. My guess is https://github.com/dart-lang/build/pull/2091 but I don't see how it is impacting the error message.
> Update merged directory errors

- example/pubspec.yaml
- webdev/lib/src/command/configuration.dart
- webdev/lib/src/command/daemon_command.dart
- webdev/lib/src/command/serve_command.dart
- webdev/lib/src/command/shared.dart
- webdev/lib/src/pubspec.dart
- webdev/lib/src/serve/dev_workflow.dart
- webdev/pubspec.yaml
- webdev/test/integration_test.dart
- Add `outputInput` and `outputPath` to `Configuration` where `-o outputInput:outputPath`
- Shitty names so open to suggestions
- Update to `build_daemon` `0.5.0` which supports output paths
- Use parsed output in the new daemon protocol
- Now require a minimum of `build_runner` `1.3.0`
> Support latest build_daemon and build_runner

- webdev/CHANGELOG.md
- webdev/pubspec.yaml
We'll probably want to clean up some of these deps and mark them as dev dependencies because they are only used to build the injected JS. Probably not a blocker for alpha though.
> Prep Webdev for publish

- webdev/lib/src/daemon/app_domain.dart
1. Set the IDs to match for the start/end events so that the editor knows there are related
2. Set finished: true for the end events so the editor knows the progress finished (and can remove the progress indicator) (see https://github.com/dart-lang/webdev/issues/219#issuecomment-480794461)
3. Changed the start text to "Building" so that it makes sense when shown as a progress indicator
> Tweak daemon app.progress events

- webdev/lib/src/serve/injected/client.js
- webdev/web/client.dart
- webdev/web/reloading_manager.dart
Previously we hardcoded the translation but that isn't consistent between kernel/analyzer build_web_compilers 1.x and 2.x. This is also just generally more robust.
Fixes https://github.com/dart-lang/webdev/issues/273.
> fetch the module name from the urlToModuleName map

- webdev/lib/src/daemon/app_domain.dart
- webdev/test/daemon/app_domain_test.dart
- return an error code for hot reload instead of an exception result
In IDEs, we can show:
instead of:
I'm going to let this build through in the bots - I'm having trouble running the tests locally.
> return an error code for hot reload

- webdev/lib/src/command/build_command.dart
- webdev/test/e2e_test.dart
This is necessary for providing `--delete-conflicting-outputs` at a minimum.
> allow build_runner args to the build command

- webdev/lib/src/daemon/app_domain.dart
tweak how we send progress events:
- messages generally end in ellipses, in order to indicate that a task is ongoing
- `finished` events don't send messages
- `progressId` fields generally aren't needed. This is only used by flutter_tools to help clients call out hot reload and hot restart progress event
@grouma
> tweak how we send progress events

- webdev/lib/src/command/daemon_command.dart
- updates to the daemon.log event (follow up to https://github.com/dart-lang/webdev/pull/304)
@grouma
> updates to the daemon.log event

- webdev/lib/src/command/shared.dart
- webdev/lib/src/pubspec.dart
It'll just cause problems since the call to `pub deps` is not updated
to correspond to the file location
> Remove unused path are to PubspecLock.read

- webdev/lib/src/serve/debugger/webdev_vm_client.dart
- webdev/lib/src/serve/injected/client.js
- webdev/web/client.dart
- webdev/web/promise.dart
- webdev/web/reloading_manager.dart
Fixes https://github.com/dart-lang/webdev/issues/302
Previously the behavior was pretty broken, after talking with @jacob314 we decided the best thing to do is actually restart the app (even if it doesn't have anything new to load).
I also did some other cleanup to make things more robust:
- Handle errors from the $dartHotRestart call and forward them along
- Return a promise to JS from the `$dartHotRestart` call so that it can be properly awaited (we weren't actually waiting before because it was a dart future, so this may have contributed to race conditions).
- Return an actual boolean result (success/failure) for the `$dartHotRestart` call.
> fix no-op hot restarts

- webdev/lib/src/logging.dart
- webdev/lib/src/serve/logging.dart
- webdev/test/logging_test.dart
This assumes the logger names do not contain spaces. Based off of https://github.com/dart-lang/build/pull/2194 this assumption appears correct.
Closes https://github.com/dart-lang/webdev/issues/301
> Remove logger name when not verbose

- webdev/lib/src/serve/chrome.dart
Closes https://github.com/dart-lang/webdev/issues/297
> Move chrome profile to .dart_tools

- .travis.yml
- dwds/example/hello_world/index.html
- dwds/mono_pkg.yaml
- dwds/test/test_context.dart
- tool/travis.sh
DWDS tests make use of `webdev` by global activation. When `webdev 2.0.0` was released it broke the tests. Changes:
- No longer implicitly cancel the `stdout` stream as that causes issues with `webdev`
- Get `instanceId` through an evaluate instead of hard coding a fake one
- `webdev 2.0.0` now embeds one
- Run only one test at a time due to blocking issue https://github.com/dart-lang/build/issues/2210
> Fix DWDS tests with webdev 2.0.0

- webdev/lib/src/serve/chrome.dart
We no longer use a system temp dir. This is intended to be kept around preserving user settings.
> Don't cleanup datadir

- .travis.yml
- webdev/lib/src/serve/chrome.dart
ChromeDriver no longer supports a range of Chrome versions :(
Figure out the correct version of ChromeDriver to download and use that one.
Fix an issue where we were reusing the chrome profile from the Travis cache. Also add a timeout for waiting for the Chrome DevTools connection.
> Use correct ChromeDriver

- webdev/CHANGELOG.md
- webdev/lib/src/serve/chrome.dart
- webdev/lib/src/serve/injected/client.js
- webdev/lib/src/version.dart
- webdev/pubspec.yaml
Closes https://github.com/dart-lang/webdev/issues/320
> Fix launching Chrome on Windows

- webdev/lib/src/serve/dev_workflow.dart
Possibly towards https://github.com/dart-lang/webdev/issues/319
There is a race condition where assets can be requested prior to starting a build which would cause read errors. Change the logic to register and start a build before starting the proxy asset server and launching chrome.
> Start build before launching Chrome

- webdev/README.md
- webdev/lib/src/command/serve_command.dart
Closes https://github.com/dart-lang/webdev/issues/328
> Update debug help

- dwds/CHANGELOG.md
- dwds/pubspec.yaml
Related to https://github.com/flutter/devtools/issues/562
Will follow up with a webdev update to allow this version and update for the breaking change.
> update vm_service_lib, prep for release

- webdev/lib/src/serve/injected/client.js
- webdev/web/client.dart
Closes https://github.com/dart-lang/webdev/issues/330
Users can now launch DevTools by running `$launchDevTools` in the console. They can easily add a bookmark to do this evaluation.
> Hoist DevTools launcher into a JS function

- dwds/CHANGELOG.md
- dwds/lib/src/chrome_proxy_service.dart
- dwds/pubspec.yaml
Towards https://github.com/flutter/devtools/issues/562
> improve dwds eval error reporting

- dwds/pubspec.yaml
- dwds/test/test_context.dart
- example/pubspec.yaml
- webdev/lib/src/command/daemon_command.dart
- webdev/lib/src/serve/chrome.dart
- webdev/lib/src/serve/dev_workflow.dart
- webdev/lib/src/serve/handlers/dev_handler.dart
- As suggested by the Chrome docs, always use a tmp dir when passing `--remote-debugging-port`
- Add graceful exit handler for daemon command
- This ensures that Chrome is properly closed
- Temporary pin build_daemon version to fix integration tests
- Fix concurrent modification issue
Closes https://github.com/dart-lang/webdev/issues/319
Closes https://github.com/dart-lang/webdev/issues/300
This reverts https://github.com/dart-lang/webdev/pull/322 & https://github.com/dart-lang/webdev/pull/316
> Chrome fixes for VS code

- dwds/CHANGELOG.md
- dwds/example/hello_world/main.dart
- dwds/lib/src/chrome_proxy_service.dart
- dwds/pubspec.yaml
- dwds/test/chrome_proxy_service_test.dart
This gets rid of some exceptions in devtools when selecting widgets.
Next up is implementing `getObject` for dart instances so that hovering over things works.
> support basic scope in evaluate calls

- webdev/lib/src/command/daemon_command.dart
`SIGTERM` is not supported on Windows. Flutter works around it like this: https://github.com/flutter/flutter/blob/8e7c7fcbd48abf2ded5ec876759375453ac18cff/packages/flutter_tools/lib/src/base/io.dart#L116
> Work around Windows limitations

- webdev/lib/src/daemon/app_domain.dart
Closes https://github.com/dart-lang/webdev/issues/363
This is less than ideal in my opinion. VS code must be listening for this response and actively killing the process. On Windows we can only capture `SIGINT`. I believe any other signal kills the process.
> Wait for daemon to exit before returning success

- webdev/CHANGELOG.md
- webdev/lib/src/serve/debugger/devtools.dart
- webdev/lib/src/version.dart
- webdev/pubspec.yaml
Hopefully closes https://github.com/dart-lang/webdev/issues/375 for the last time :P
> Use HTTP Multi Server for DevTools

- dwds/lib/src/chrome_proxy_service.dart
In preparation for debugging support, make assetHandler and handleErrorIfPresent public. Also simplify getLibrarySnippet.
> Expose some methods, simplify getLibrarySnippet

- webdev/CHANGELOG.md
- webdev/lib/src/pubspec.dart
- webdev/lib/src/version.dart
- webdev/pubspec.yaml
- webdev/test/integration_test.dart
We actually require this version today due to requiring version `1.0.0` of `package:build_daemon`. Updating this minimum provides better error messages.
Related to https://github.com/dart-lang/webdev/issues/408
> Update minimum build_runner version to 1.5.0

- dwds/example/hello_world/main.dart
This function has a return type of 'Future<ServiceExtensionResponse>', but doesn't end with a return statement.
> Fix new lints

- dwds/lib/src/dart_uri.dart
- dwds/lib/src/debugger.dart
- dwds/lib/src/location.dart
- dwds/test/chrome_proxy_service_test.dart
- Fix issue where we were not accounting for `.` in a relative path
- Fix some off by one issues for line and column data
- Move a TODO to a better location
- It's likely that we won't support setting breakpoints for lines that we do not have location data for
- See https://github.com/flutter/devtools/issues/703
> Fix source location incompatibilities

- webdev/CHANGELOG.md
- webdev/lib/src/serve/webdev_server.dart
- webdev/lib/src/version.dart
- webdev/pubspec.yaml
Bump to latest `http_multi_server` which encapsulates the logic for
special hostnames 'localhost' and 'any'.
> Add support for --hostname any

- example/web/main.dart
- webdev/CHANGELOG.md
- webdev/lib/src/serve/handlers/dev_handler.dart
- webdev/pubspec.yaml
- No longer use the `window.open` API as it has unintended consequences for debugging
- Update the example to have a counting logger
- This is useful as we build out the debugging support
- Add dependency_override comment to ease development
Unfortunately this regresses https://github.com/dart-lang/webdev/issues/287. The other option is to launch a new instance of Chrome but that's less than ideal.
> Fix pausing within DevTools

- webdev/lib/src/serve/handlers/dev_handler.dart
For some reason the `newWindow` parameter doesn't work. Nonetheless this is a preferred API.
See:
https://chromedevtools.github.io/devtools-protocol/tot/Target#method-createTarget
> Use createTarget API for DevTools

- example/pubspec.yaml
This should prevent issues like https://github.com/dart-lang/webdev/issues/408 in the future. 
This will involve a bit of followup work but it should be minimal, just bumping the versions when there are breaking changes.
Closes https://github.com/dart-lang/webdev/issues/429
> add angular deps to the example app as a smoke test

- webdev/lib/src/serve/handlers/favicon_handler.dart
- webdev/lib/src/serve/webdev_server.dart
Closes https://github.com/dart-lang/build/issues/892
If the users has not specified a favicon chrome will attempt to load
`/favicon.ico` by default. If this would otherwise be a 404 we can
provide a default and avoid an error in the console.
The default icon is the same as the `dart.dev` site.
> Add a handler for favicon.ico

- dwds/CHANGELOG.md
- dwds/example/hello_world/main.dart
- dwds/lib/src/chrome_proxy_service.dart
- dwds/lib/src/debugger.dart
- dwds/lib/src/location.dart
- dwds/lib/src/sources.dart
- dwds/pubspec.yaml
- dwds/test/chrome_proxy_service_test.dart
- Update `Location` to group JS fields into `JsLocation` and Dart fields into `DartLocation`
- Add logic to translate JS frame information into Dart frame
- Listen for pause events to cache the current Dart frame
Closes https://github.com/dart-lang/webdev/issues/348
Towards https://github.com/dart-lang/webdev/issues/352
> Initial support of getStack

- webdev/lib/src/serve/data/isolate_events.dart
- webdev/lib/src/serve/data/isolate_events.g.dart
- webdev/lib/src/serve/data/serializers.dart
- webdev/lib/src/serve/data/serializers.g.dart
- webdev/lib/src/serve/debugger/webdev_vm_client.dart
- webdev/lib/src/serve/handlers/dev_handler.dart
- webdev/lib/src/serve/injected/client.js
- webdev/lib/src/serve/middlewares/injected_middleware.dart
- webdev/test/daemon/app_domain_test.dart
- webdev/test/serve/injected/devtools_test.dart
- webdev/web/client.dart
- webdev/web/reloading_manager.dart
Fixes https://github.com/dart-lang/webdev/issues/432
Isolate events are now driven by the client side app and not webdev directly, which ensures they are handled in a more uniform fashion (and fixes them with --auto=restart).
> send isolate events with --auto=restart also

- dwds/lib/src/chrome_proxy_service.dart
- dwds/lib/src/debugger.dart
- dwds/test/chrome_proxy_service_test.dart
- Move pause and resume subscriptions into the `Debugger`
- Now always listen for these events even if the `Debug` stream does not have a subscription
- This allows us to also make frame handling logic private to the `Debugger` abstraction
- Update `mainProxy  to be private
- Also update the `BreakPoint` abstraction to use a private `mainProxy` for consistency (further clean up to follow)
- Move `pause` and `resume` into `Debugger`
- Update Chrome Proxy to delegate to the `Debugger`
- Update `resume` to support the `step` parameter
- Add tests
Closes https://github.com/dart-lang/webdev/issues/438
Closes https://github.com/dart-lang/webdev/issues/347
Towards https://github.com/dart-lang/webdev/issues/352
> Support stepping i.e. Over, Into, and Out

- dwds/lib/src/chrome_proxy_service.dart
- dwds/lib/src/debugger.dart
- dwds/lib/src/inspector.dart
- dwds/lib/src/sources.dart
- dwds/test/chrome_proxy_service_test.dart
- Create new `AppInspector` abstraction
- This abstraction constructs an `isolate`
- It handles all things related to inspection, e.g. `getObject`, `evaluate` etc.
- Note that essentially no new code is in this abstraction, just logic moved from `ChromeProxyService`
- Update `ChromeProxyService` to delegate to the `Inspector`
- Update `Debugger` to no longer need a reference to the main proxy
- Make the `Debugger` constructor private
- This ensures that we call `initialize` upon construction
- Move logic for pause modes over to the `Debugger`
> Refactor Chrome Proxy Service

- webdev/CHANGELOG.md
- webdev/lib/src/serve/debugger/webdev_vm_client.dart
- webdev/lib/src/version.dart
- webdev/pubspec.yaml
- webdev/test/serve/injected/devtools_test.dart
Closes https://github.com/dart-lang/webdev/issues/446
Now is the time to give pushback on the name as well if people have opinions, we could call it `refreshPage` or something more explicitly describing the behavior as well.
cc @natebosch @jonahwilliams
> add a fullReload service extension which performs a full page refresh

- dwds/lib/src/chrome_proxy_service.dart
- dwds/lib/src/debugger.dart
- dwds/lib/src/inspector.dart
- dwds/lib/src/sources.dart
- dwds/test/chrome_proxy_service_test.dart
- webdev/lib/src/serve/handlers/dev_handler.dart
- webdev/pubspec.yaml
Closes https://github.com/dart-lang/webdev/issues/426
This change only supports adding breakpoints after a refresh. This does not keep breakpoints around after a refresh.
> Breakpoint support with refreshing

- dwds/CHANGELOG.md
- dwds/lib/service.dart
- webdev/lib/src/serve/handlers/dev_handler.dart
- webdev/lib/src/serve/webdev_server.dart
- webdev/pubspec.yaml
- added onResponse and onRequest listeners to dwds
- use onResponse to log failed responses in verbose mode for webdev (logged at warning level, some are always expected right now).
Closes https://github.com/dart-lang/webdev/issues/451
> Log vm service rpc errors in verbose mode

- dwds/lib/src/chrome_proxy_service.dart
- dwds/lib/src/debugger.dart
- dwds/test/chrome_proxy_service_test.dart
We weren't setting the current run state on the isolate. This caused issues if the user refreshed the devtools page while debugging.
cc @jacob314
> Set isolate pause / resume state

- dwds/lib/src/debugger.dart
- example/web/main.dart
- webdev/lib/src/serve/debugger/webdev_vm_client.dart
- webdev/test/serve/injected/fixtures/web/main.dart
- webdev/test/serve/injected/reload_test.dart
The final desired behavior for hot restart while debugging is open for discussion. @jacob314 is working through that issue. 
Right now however, this fixes a class of issues with hot restarting while debugging. Upon hot restart we remove all breakpoints and resume execution.
> Fix hot restart while debugging

- webdev/test/serve/injected/reload_test.dart
Wait for the isolate start event before we check for values. This should close https://github.com/dart-lang/webdev/issues/466
> Wait for isolate start event

- .travis.yml
- appveyor.yml
- dwds/lib/src/debugger.dart
- dwds/lib/src/domain.dart
- tool/travis.sh
- webdev/dart_test.yaml
- webdev/mono_pkg.yaml
- webdev/test/build/ensure_build_test.dart
- webdev/test/daemon/app_domain_test.dart
- webdev/test/daemon/daemon_domain_test.dart
- webdev/test/serve/injected/devtools_test.dart
- webdev/test/serve/injected/reload_test.dart
- webdev/test/serve/screenshot_test.dart
We should come up with a better pattern. Not really sure why we do this `--run-skipped` silliness to begin with.
> Actually skip on windows

- dwds/CHANGELOG.md
- dwds/lib/app_connection.dart
- dwds/lib/debug_connection.dart
- dwds/lib/dwds.dart
- dwds/lib/src/connections/app_connection.dart
- dwds/lib/src/connections/debug_connection.dart
- dwds/lib/src/debugger.dart
- dwds/lib/src/domain.dart
- dwds/lib/src/dwds_vm_client.dart
- dwds/lib/src/handlers/asset_handler.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/handlers/injected_handler.dart
- dwds/lib/src/injected/configuration.dart
- dwds/lib/src/inspector.dart
- dwds/lib/src/services/app_debug_services.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/services/debug_service.dart
- dwds/lib/src/sources.dart
- dwds/pubspec.yaml
- dwds/test/chrome_proxy_service_test.dart
- dwds/test/debug_service_test.dart
- dwds/test/handlers/injected_handler_test.dart
- dwds/test/test_context.dart
- dwds/test/variable_scope_test.dart
- webdev/lib/src/command/configuration.dart
- webdev/lib/src/daemon/app_domain.dart
- webdev/lib/src/serve/dev_workflow.dart
- webdev/lib/src/serve/server_manager.dart
- webdev/lib/src/serve/webdev_server.dart
- Rename `dwds/lib/service.dart` to `dwds/lib/src/services/debug_service.dart`
- Move `chrome_proxy_service.dart` and `app_debug_services.dart` to `dwds/lib/src/services`
- Rename `DevConnection` to `AppConnection` and promote as a public abstraction
- Create new public `DebugConnection` abstraction
- Create new public entrypoint `dwds.dart`
- This entrypoint exposes a `handler` to be used with shelf (see changes to `webdev`)
- Update `webdev` to no longer import from `dwds`'s source
This mostly completes https://github.com/dart-lang/webdev/issues/475. In a follow up PR I'll shuffle the tests around so there is a better separation between `webdev` and `dwds` tests.
cc @jonahwilliams
> Public API to support Flutter CLI

- dwds/lib/dwds.dart
- dwds/test/fixtures/context.dart
- dwds/test/fixtures/server.dart
Some of these parameters can have sane defaults and should not be required.
> Make some required parameters optional

- _test/pubspec.yaml
- dwds/CHANGELOG.md
- dwds/pubspec.yaml
- example/pubspec.yaml
- webdev/CHANGELOG.md
- webdev/README.md
- webdev/lib/src/pubspec.dart
- webdev/lib/src/version.dart
- webdev/pubspec.yaml
- webdev/test/integration_test.dart
- Update `dwds`'s pubspec to include all deps
- Update `webdev` / `dwds` to depend on latest `build_daemon`
- Update `webdev` to restrict to proper `build_runner` version
- Temporarily override example deps
> Prepare to publish

- dwds/CHANGELOG.md
- dwds/lib/src/utilities/dart_uri.dart
- dwds/pubspec.yaml
- dwds/test/dart_ui_test.dart
- webdev/pubspec.yaml
Source map paths are often relative, e.g. `/packages/src/../foo.dart`. Account for this and add corresponding tests.
Closes: https://github.com/dart-lang/webdev/issues/505
> Normalize paths in DartUri

- dwds/lib/src/connections/debug_connection.dart
- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/debugging/inspector.dart
- dwds/lib/src/debugging/remote_debugger.dart
- dwds/lib/src/debugging/webkit_debugger.dart
- dwds/lib/src/dwds_vm_client.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/servers/extension_debugger.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/services/debug_service.dart
- dwds/test/debugger_test.dart
- dwds/test/fixtures/context.dart
- dwds/test/fixtures/fakes.dart
`WebkitDebugger` and `ExtensionDebugger` extend `RemoteDebugger`. `WebkitDebugger` replaces a `wipDebugger` that uses the Webkit Inspection Protocol connection.
> Created a generic remote debugger.

- dwds/lib/dwds.dart
If `--debug` is not set, `serveDevTools` is already defaulted to `false`. The null check is too late.
> Enabled serveDevTools for Dart Debug Extension.

- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/debugging/sources.dart
- Do not consider the JS column number when looking for a matching JS location.
- We use a heuristic to find the closest number based off a non-exact column number
- Add black boxing logic to the dart_sdk and stack_trace package to improve performance
> Better black boxing

- dwds/lib/src/debugging/inspector.dart
- example/web/scopes_main.dart
Undefined can occur when we are paused part-way through initializing a variable.
Adds ignores because we're explicitly testing an uninitialized local variable, and the lints want us to type uninitialized variables but not locals.
> Better instanceRefs for undefined and function types

- dwds/CHANGELOG.md
- dwds/lib/src/connections/debug_connection.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/services/debug_service.dart
- dwds/test/debug_service_test.dart
- webdev/lib/src/daemon/app_domain.dart
- Add option to the `DebugService` to start an `SSE` server instead of a `Websocket` server
- Update debug connection `wsUri` to be called `uri` to reflect that it may not be a websocket
Once https://github.com/flutter/devtools/issues/881 is resolved we should be able to do some E2E testing. I'll leave this work to @pisimulation.
> Provide initial support of SSE with DevTools

- dwds/CHANGELOG.md
- dwds/pubspec.yaml
- dwds/web/client.dart
- webdev/CHANGELOG.md
- webdev/README.md
- webdev/lib/src/command/configuration.dart
- webdev/lib/src/command/serve_command.dart
- webdev/lib/src/serve/webdev_server.dart
- webdev/lib/src/version.dart
- webdev/pubspec.yaml
Fixes https://github.com/dart-lang/webdev/issues/540
- Disables dwds altogether in favor of a simple proxy server when this flag is present
- Wrapped client.js in runZoned to catch all errors and notify of this flag
- Added checks that incompatible debugging flags aren't used when this flag is provided
> Add a --no-injected-client flag

- dwds/debug_extension/web/background.dart
- dwds/debug_extension/web/background.js
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/servers/extension_debugger.dart
- Since the extension background receives debugging events (`ExtensionEvent`) from all apps, it has to forward those events to correct apps using `tabId`.
- The flag 'Throttle expensive background timers' in `chrome://flags` must be disabled.
> Handled debugging multiple apps.

- dwds/lib/src/debugging/inspector.dart
When looking for the classes defined in a library we were iterating over
`Object.values` for the library, this evaluates any top level getters
defined on the library. When we are looking to understand the static
structure of a library we should not be executing any of the code it
contains.
- Use `Object.getOwnPropertyDescriptors` so that each value is not
evaluated, but turned into an object which may have either a `value`
or a `get` key.
- Filter down to the values which have a `value` key, since those are
the ones that exist without executing any code.
> Avoid executing top-level getters to find classes

- dwds/lib/src/handlers/injected_handler.dart
build_web_compilers now has multiple entrypoints to main. Because these entrypoints are formatted like (a.main || b.main).main(), stripping all parens is no longer feasible.
> Updating logic to accommodate multiple entrypoints

- dwds/lib/src/debugging/sources.dart
p.join() assumes path separators are `\` on Windows. Since both urls are actually UNIX-style, the path lookup fails.
> Updating url concat to use the current url's path separator

- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/debugging/inspector.dart
- dwds/lib/src/debugging/instance.dart
- dwds/lib/src/debugging/metadata.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/pubspec.yaml
- dwds/test/fixtures/debugger_data.dart
- dwds/test/fixtures/fakes.dart
- dwds/test/inspector_test.dart
- dwds/test/instance_test.dart
- example/web/main.dart
- Rev `devtools` version as inspection logic only works with this version
- Create new `instance.dart` which contains methods for creating `Instance`s and `InstanceRef`s.
- Now properly construct an `Instance` for objects
- Sort variables and fields
- No longer pass `hide=none` so that only working tabs are available
- Add some basic tests for the updated instance methods
> Better expand

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/debugging/exceptions.dart
- dwds/lib/src/debugging/inspector.dart
- dwds/lib/src/debugging/sources.dart
- dwds/lib/src/handlers/asset_handler.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/services/debug_service.dart
- dwds/pubspec.yaml
- dwds/test/debugger_test.dart
- dwds/test/debugging/sources_test.dart
Helps with issues like https://github.com/dart-lang/webdev/issues/514.
- Adds a warning log when we fail to fetch a source map
- Throws a ScriptNotFound exception when we fail to load a script
- Plumbs a `LogWriter` through various classes so we can use it for logging
- Cleans up the conflicting AssetHandler definitions by removing the typedef in favor of the class
- Changes `AssetHandler.getRelativeAsset` to return a `Future<Response>` instead of a `Future<String>` so the status code can be checked.
> Handle missing sources and source maps gracefully

- dwds/CHANGELOG.md
- dwds/pubspec.yaml
- webdev/CHANGELOG.md
- webdev/pubspec.yaml
- upgrade the webkit_inspection_protocol dependency
This wides the dep on `package:webkit_inspection_protocol` to allow us to bring in `0.5.0`; it's mostly the same as `0.4.0` but with fewer transitive deps.
> upgrade the webkit_inspection_protocol dependency

- webdev/CHANGELOG.md
- webdev/README.md
- webdev/lib/src/command/configuration.dart
- webdev/lib/src/command/serve_command.dart
- webdev/lib/src/serve/dev_workflow.dart
- webdev/lib/src/serve/webdev_server.dart
- webdev/lib/src/version.dart
- webdev/pubspec.yaml
Helps with issue: #564 
- Added option `tls-cert-chain`
- Added option `tls-cert-key`
By adding the above to flags to `webdev serve` users are able to launch the development server listening for HTTPS requests.
Known Issue:
The output line will show 127.0.0.1 regardless of what the `--hostname` flag is set to. However, the server will listen to all hostnames regardless. I did not see a place to set the hostname in HttpMultiServer's loopbackSecure to inject the hostname. Perhaps this issue could be resolved with a change in that output line?
> Added TLS support to webdev serve. (#564)

- webdev/CHANGELOG.md
- webdev/lib/src/command/configuration.dart
- webdev/lib/src/command/serve_command.dart
- webdev/lib/src/command/shared.dart
- webdev/test/configuration_test.dart
- webdev/test/e2e_test.dart
Fixes https://github.com/dart-lang/webdev/issues/571
We will now throw an InvalidConfiguration error and give the appropriate exit code if asked to serve or build anything other than a top level directory in the package.
This never worked but silently just didn't do what people expected.
> Allow building/serving top level dirs only

- webdev/lib/src/command/configuration.dart
- webdev/test/configuration_test.dart
Validate configuration during construction to ensure we never get an invalid configuration. Add some related tests.
> Improve Configuration Validation

- dwds/lib/src/debugging/instance.dart
- dwds/test/chrome_proxy_service_test.dart
See #575 
Chrome doesn't provide us with objectIds for strings, but the VM Service Protocol expects to be able to do getObject on Strings. This uses String as their own object Ids (with a prefix to identify them).
> Use String values as their own ids in instanceRefs

- dwds/lib/src/debugging/inspector.dart
- dwds/lib/src/debugging/instance.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/utilities/objects.dart
- dwds/test/fixtures/fakes.dart
- dwds/test/inspector_test.dart
- dwds/test/instance_test.dart
- dwds/test/objects_test.dart
- example/web/scopes_main.dart
Also strip out the Symbol() portion from private field names.
Removes an unrelated generic type that I noticed causing exceptions when passed a List<dynamic> coming from JSON, instead of the correct 'not implemented' exception :-)
> Use dart.getFields to accurately find the fields for an object

- webdev/lib/src/command/shared.dart
- Remove a debug `print` call.
- Remove a duplicate check for the path `'.'`.
> Debug print cleanup

- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/pubspec.yaml
This upgrades to the latest `package:vm_service` version. Version solving fails because devtools has not yet upgraded; that's in progress (https://github.com/flutter/devtools/pull/943).
Related to https://github.com/dart-lang/webdev/issues/580.
```
pub get
Resolving dependencies... 
Because devtools 0.1.6-dev.2 depends on vm_service 1.1.0 and no versions of devtools match >0.1.6-dev.2 <0.2.0, devtools ^0.1.6-dev.2 requires
vm_service 1.1.0.
So, because dwds depends on both vm_service 1.1.1 and devtools ^0.1.6-dev.2, version solving failed.
```
> upgrade to the latest package:vm_service

- dwds/debug_extension/web/background.dart
- dwds/debug_extension/web/background.js
- dwds/debug_extension/web/manifest.json
- Detaches debugger and stops debug service when the DevTools window is closed.
- Addressed #615 : only attaches debugger if it is not already attached. This prevents users from clicking on the extension again when DevTools is already serving. Is this a good design?
> Fixed attach & detach issues in Dart Debug Extension

- _test/example/hello_world/main.dart
- dwds/CHANGELOG.md
- dwds/lib/src/debugging/inspector.dart
- dwds/lib/src/debugging/instance.dart
- dwds/lib/src/debugging/metadata.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/utilities/conversions.dart
- dwds/test/chrome_proxy_service_test.dart
- dwds/test/fixtures/fakes.dart
- dwds/test/inspector_test.dart
- dwds/test/instance_test.dart
- dwds/test/variable_scope_test.dart
- example/web/scopes_main.dart
This ended up being a fairly substantial refactoring as well 
- Made InstanceHelper into a domain. 
- Renamed lots of the methods doing calls/evals to try to be more consistent and to make fewer direct calls to the Chrome APIs. So invoke splits into invokeMethod and invokeFunction, and direct calls to Chrome APIs are prefixed with "js" and named like what they call, e.g. jsCallFunctionOn.
- Added a noSuchMethod handler to FakeInspector so anything that just throws can be omitted.
- Created a conversions library for converting back and forth between the different representations we're using.
- Because JavaScript, there's something strange going on with how we pass arguments in callFunctionOn that expects them differently if we try to pass an array of the positional arguments (what we did …
> Implement invoke

- dwds/CHANGELOG.md
- dwds/lib/asset_handler.dart
- dwds/lib/dwds.dart
- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/debugging/inspector.dart
- dwds/lib/src/debugging/sources.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/services/debug_service.dart
- dwds/pubspec.yaml
- dwds/test/debugging/sources_test.dart
- dwds/test/fixtures/server.dart
- webdev/CHANGELOG.md
- webdev/lib/src/serve/webdev_server.dart
- webdev/lib/src/version.dart
- webdev/pubspec.yaml
- Expose `AssetHandler` abstraction
- Also provide a default implementation for external users
- Update `Dwds.start` to now take a required `AssetHandler`
> Expose AssetHandler

- dwds/CHANGELOG.md
- dwds/lib/src/dwds_vm_client.dart
- dwds/pubspec.yaml
Fixes https://github.com/dart-lang/webdev/issues/694
This is a safeguard for when we get a request to the vm service but the request controller is already closed. Instead of crashing we log a warning with the request.
> Add a guard for a closed sink before writing requests

- dwds/CHANGELOG.md
- dwds/lib/src/connections/debug_connection.dart
- dwds/lib/src/debugging/webkit_debugger.dart
- dwds/lib/src/dwds_vm_client.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/servers/devtools.dart
- dwds/lib/src/servers/extension_backend.dart
- dwds/lib/src/servers/extension_debugger.dart
- dwds/lib/src/services/app_debug_services.dart
- dwds/lib/src/services/debug_service.dart
- dwds/pubspec.yaml
- dwds/test/fixtures/fakes.dart
Fixes https://github.com/dart-lang/webdev/issues/701.
Use a common strategy of caching the result of previous close methods and returning that on subsequent calls.
In investigating the linked issue I realized the logic for closing things is very convoluted and we almost certainly close some things repeatedly. It is easiest to simply allow this but handle it gracefully.
> make all close methods handle being called multiple times

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/debugger.dart
Fixes https://github.com/dart-lang/webdev/issues/697
This is a general fix for handling the require js is not loaded errors - in response to chrome pause events which could explicitly happen at any time.
These are all indications of race conditions or other things outside of our control.
I did add a warning log though.
> when handling pause events, catch app not loaded errors and log a warning

- dwds/CHANGELOG.md
- dwds/lib/dwds.dart
- dwds/lib/src/connections/app_connection.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/pubspec.yaml
- dwds/test/fixtures/context.dart
- dwds/test/run_request_test.dart
Fix the following issues:
- If you enable debugging, we eagerly set up the app services on a run request
- If you initiate debugging while the application is already running the initial state is not valid
- If you open an application in another tab while debugging, refresh events in this new tab cause the isolate to be destroyed
> Correct set the pause state

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/dart_scope.dart
- dwds/lib/src/debugging/inspector.dart
- dwds/lib/src/utilities/shared.dart
- dwds/pubspec.yaml
With the legacy module system, we must manually import all transitive modules. This work is a no-op the second time around. Therefore, it's fine to have a static preamble that is used while loading libraries.
> Preload libraries for legacy module system

- dwds/CHANGELOG.md
- dwds/lib/data/run_request.dart
- dwds/lib/data/run_request.g.dart
- dwds/lib/data/serializers.dart
- dwds/lib/data/serializers.g.dart
- dwds/lib/dwds.dart
- dwds/lib/src/connections/app_connection.dart
- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/injected/client.js
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/test/fixtures/context.dart
- dwds/test/run_request_test.dart
- dwds/web/client.dart
- No longer wait for `CreateIsolate` to complete or the debugger to be enabled before creating the `ChromeProxyService`
- Get rid of the `correctTab` evals as they are no longer necessary
- No longer return a `RunResponse` as the run state is now properly stored in the `AppConnection`
> Faster DevTools launch

- dwds/test/fixtures/context.dart
- dwds/test/refresh_test.dart
- dwds/test/reload_test.dart
- dwds/test/variable_scope_test.dart
- example/web/scopes_main.dart
- fixtures/_test/example/append_body/main.dart
- fixtures/_test/example/hello_world/main.dart
- webdev/CHANGELOG.md
- webdev/lib/src/command/configuration.dart
- webdev/lib/src/command/daemon_command.dart
- webdev/lib/src/command/serve_command.dart
- webdev/lib/src/command/shared.dart
- webdev/lib/src/serve/dev_workflow.dart
- webdev/lib/src/version.dart
- webdev/pubspec.yaml
- webdev/test/daemon/app_domain_test.dart
- webdev/test/daemon/launch_app_test.dart
- webdev/test/daemon/utils.dart
Closes https://github.com/dart-lang/webdev/issues/744
- Expects a package relative path to an html file, such as `web/app.html`.
- Launches the specified application in chrome on startup instead of the server root.
- Allows multiple apps, and will launch all of them.
- Supported for the `daemon` and `serve` commands.
This also adds general arg parsing for the shared arguments for all commands, such as -v and -r, as well as actual support for trailing args in `<dir>:<port>` format (just like the serve command).
cc @alexander-doroshko @devoncarew @jwren
> Add --launch-app command line option

- dwds/test/chrome_proxy_service_test.dart
Using the `hasLength` matcher improves the output when the expectation
fails. Instead of:
```
Expected: <1>
Actual: <2>
```
The failure looks like:
```
Expected: an object with length of <1>
Actual: <The real list>
Which: has a length of <2>
```
> Use hasLength for expectations around length

- webdev/CHANGELOG.md
- webdev/lib/src/command/configuration.dart
- webdev/lib/src/serve/dev_workflow.dart
- webdev/lib/src/version.dart
- webdev/pubspec.yaml
- webdev/test/configuration_test.dart
- webdev/test/e2e_test.dart
When `webdev build` is run with the `--output=NONE` option:
- Default the `outputInput` to an empty string (build everything)
- I'm not sure if this is the desired behavior, but it matches `build_runner build`
- Fix validation logic that was disallowing an empty string `outputInput` value
fya @grouma
> Fix RTE when running with `--output=NONE`

- webdev/lib/src/serve/chrome.dart
- webdev/pubspec.yaml
This reverts commit 7e2cf753971c5228bd3e08d87dad366f8009cad8.
This seems to be causing extra flakiness, particularly on Windows, possibly from tests interfering with each other, so reverting until that can be fixed.
> Revert "Launch Chrome from the same directory (#764)"

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/debugger.dart
- dwds/test/chrome_proxy_service_test.dart
Fixes https://github.com/dart-lang/webdev/issues/782
- Breakpoint ids are now a combination of script id and line number.
- If you ask for a breakpoint which is already set we just return the old one (cached by id)
- I also cleaned up some ugly apis that duplicated the class name in the methods
> Multiple breakpoints

- dwds/lib/src/debugging/dart_scope.dart
- dwds/test/instance_test.dart
- dwds/test/variable_scope_test.dart
- example/web/scopes_main.dart
Closes #760 
This just suppresses the type arguments. Handling them correctly is harder, and it's not clear anything uses them. See #786
> Suppress type arguments on generic functions in stack frames

- dwds/lib/src/debugging/classes.dart
- dwds/lib/src/debugging/inspector.dart
- dwds/lib/src/debugging/instance.dart
- dwds/lib/src/debugging/libraries.dart
- dwds/lib/src/debugging/metadata.dart
- dwds/lib/src/debugging/modules.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/utilities/shared.dart
- dwds/test/fixtures/fakes.dart
- dwds/test/inspector_test.dart
- dwds/test/instance_test.dart
- dwds/test/variable_scope_test.dart
- Move `getLibrarySnippet` and `handleErrorIfPresent` into `shared.dart`
- Create new abstraction:
- `libraries.dart` for working with Dart libraries
- `classes.dart` for working with Dart classes
- Update `constructLibrary` (now within `libraries.dart`) to only construct the library and not cache any class information
- Update the `getClass` logic to lazily construct the class abstraction
- Update `AppInspector` to expose `debugger`, `remoteDebugger`, `instanceHelper`, `librariesHelper` and `classesHelper`
- Update `getObject` in `AppInspector` to now use all of the helpers
Closes https://github.com/dart-lang/webdev/issues/773
> Refactor AppInspector

- dwds/CHANGELOG.md
- dwds/lib/dwds.dart
- dwds/lib/src/handlers/injected_handler.dart
- dwds/test/debug_extension_test.dart
- dwds/test/handlers/injected_handler_test.dart
Some proxy servers don't rewrite the requestedUri, so allow the URL encoder to handle this scenario.
Also sneak in an update to a stale test expect. The logic has since changed and we should be checking for different embedded data.
> Url Encode $dartUriBase

- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- dwds/test/build/ensure_version_test.dart
Fixes https://github.com/dart-lang/webdev/issues/840
Technically this doesn't do a full build check because that actually gets complicated with respect to the client.js file - we need to run with `--delete-conflicting-outputs` which means we would have to regenerate all files including the JS file which would have a lot of unnecessary churn.
> add a version.dart file check

- dwds/lib/src/debugging/execution_context.dart
It's possible more execution contexts can be created while iterating through collected contexts. Also throw a state error if we can't find a context. This shouldn't happen in practice but will help us track down issues nonetheless.
> Fix concurrent modification

- dwds/lib/src/injected/client.js
- dwds/web/client.dart
I don't know if this is the best place for this, but I was having weird issues testing this with VS Code when running the base URI through their URL tunnelling. The URL that comes out has a trailing slash and this code would insert another (and the SSE Handler fails if it's `//$sseHandler`).
I could strip it in VS Code, but I think this URI will need to be run through the url-encoder anyway, so it would be better to handle it here than ensure all url-encoders don't introduce trailing slashes on the URIs (it's my understanding that for an otherwise-pathless URI they're the equivalent).
Note: The JS file has way more changes than just this, even though I ran it with v2.7-dev.0.0 as the header said it was previously run with - I'm not sure why (though I can strip the other changes from the …
> Tolerate trailing slash in base URI for SSE handler

- dwds/CHANGELOG.md
- dwds/lib/dwds.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
@grouma this was included in https://github.com/dart-lang/webdev/pull/823 but not the PR that landed (https://github.com/dart-lang/webdev/pull/825). Is it possible to support this so we can control which protocol to use from Flutter?
Right the VS Code debugger can't talk SSE (this may change in future) so this will be required to connect VS Code to the proxy. It already uses WS when launching Chrome (it's hard-coded `useSse: false` elsewhere in this file), but forces SSE when using the debug extension.
> Allow overriding SSE to WS when using debug extension

- dwds/lib/src/debugging/execution_context.dart
Remove the unnecessary `"` in `dwds/lib/src/debugging/execution_context.dart`
> Fix typo in execution_context.dart

- dwds/CHANGELOG.md
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
The goal is to allow users to enable both the debug extension and local debugging through `Alt + D` with a single configuration. Before this change, this was infeasible when the user provided a non `localhost` `hostname`.
> Always bind to localhost for the local debug workflow

- dwds/lib/dwds.dart
- dwds/test/debug_extension_test.dart
- dwds/test/fixtures/context.dart
- dwds/test/fixtures/server.dart
This switches to using the bound hostname (that comes from `HttpMultiServer`) when building the extension URI, so you can pass though the magic string `"any"` to bind to all local IPs (see #845).
It has a side-effect that binding to "localhost" may now also return `127.0.0.1` or `::1` (this is behaviour of `HttpMultiServer`) but it sounds like that shouldn't cause any issues.
@grouma I don't know if I put the test in the most appropriate place, so let me know if there's somewhere better. I also wasn't sure whether to test the hostname `!= 'any'` or against a reasonable set of expected values like this (I went with the latter assuming it's better to break on an unexpected value than checking only it wasn't "any"). 
Fixes #845.
> Use hostname that's bound in order to support "any" via HttpMultiServer

- dwds/CHANGELOG.md
- dwds/lib/data/build_result.dart
- dwds/lib/data/build_result.g.dart
- dwds/lib/data/serializers.dart
- dwds/lib/data/serializers.g.dart
- dwds/lib/dwds.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/injected/client.js
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- dwds/test/fixtures/server.dart
- dwds/web/client.dart
- webdev/lib/src/daemon/app_domain.dart
- webdev/lib/src/serve/webdev_server.dart
- webdev/lib/src/version.dart
- webdev/pubspec.yaml
- Create new `BuildResult` abstraction inside `package:dwds` and no longer rely on the one from `package:build_daemon`.
Towards https://github.com/dart-lang/webdev/issues/865
> Provide BuildResult

- dwds/lib/src/readers/proxy_server_asset_reader.dart
- dwds/test/fixtures/server.dart
- webdev/lib/src/serve/webdev_server.dart
These arguments may have been necessary at one point but are not required as the request is being serviced by a proxy handler.
> Remove unecessary arguments

- dwds/CHANGELOG.md
- dwds/lib/src/handlers/dev_handler.dart
There was no reason that `_servicesByAppId` should return a `Future<AppDebugServices>`. This was likely an artifact of a code refactor. Due to this, it was possible to cache a problematic future in the map which would result in unexpected failures when trying to connect through the Dart Debug Extension.
> Prevent server crash while using the extension after unsuccessfully trying to connect through a local debug instance

- dwds/CHANGELOG.md
- dwds/lib/src/handlers/dev_handler.dart
We gracefully handle debug errors through `Alt + D`. We should do the same for debug requests through the extension. Otherwise, issues can kill your development server.
> Gracefully handle debug request errors through the extension

- dwds/CHANGELOG.md
- dwds/lib/src/readers/proxy_server_asset_reader.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- dwds/test/fixtures/server.dart
- webdev/lib/src/serve/webdev_server.dart
This is technically a breaking change but given we just published `1.0.0` this should be a non-issue.
> Optional root for ProxyServerAssetReader

- dwds/CHANGELOG.md
- dwds/lib/dwds.dart
- dwds/lib/src/debugging/classes.dart
- dwds/lib/src/debugging/dart_scope.dart
- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/debugging/inspector.dart
- dwds/lib/src/debugging/instance.dart
- dwds/lib/src/debugging/libraries.dart
- dwds/lib/src/debugging/metadata.dart
- dwds/lib/src/debugging/modules.dart
- dwds/lib/src/handlers/injected_handler.dart
- dwds/lib/src/injected/client.js
- dwds/lib/src/loaders/legacy.dart
- dwds/lib/src/loaders/require.dart
- dwds/lib/src/loaders/strategy.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/utilities/shared.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- dwds/test/chrome_proxy_service_test.dart
- dwds/test/debugger_test.dart
- dwds/test/fixtures/fakes.dart
- dwds/test/fixtures/server.dart
- dwds/test/handlers/injected_handler_test.dart
- dwds/test/inspector_test.dart
- dwds/test/instance_test.dart
- dwds/web/client.dart
- webdev/lib/src/serve/webdev_server.dart
Towards https://github.com/dart-lang/webdev/issues/893
Collect module strategy and related loading logic into new `LoadStrategy` abstraction. This will allow us to  make an explicit contract for the `RequireStrategy`.
> LoadStrategy

- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/servers/extension_backend.dart
Looks like https://github.com/dart-lang/webdev/pull/876 caused some issues.
When you refresh the page we don't get an isolate destroy event (or there may be a race condition) so resetting breakpoints and other debug functionality is impacted.
Before adding back the keep-alive functionality we should test the refresh functionality and ensure we get proper destroy events.
cc @danytup
> Remove keep-alive

- dwds/lib/src/debugging/dart_scope.dart
- dwds/test/fixtures/debugger_data.dart
The number of scopes to skip is not deterministic, so skipping the first two scopes leads to the inclusion of a number of non-useful properties in some scenarios. Instead, filter scopes until the inclusion of the Dart SDK. Nested scopes should contain application logic.
Related: https://github.com/dart-lang/sdk/issues/40774
> Filter JS scope up to and including the inclusion of the Dart SDK

- dwds/debug_extension/pubspec.yaml
- dwds/lib/src/connections/app_connection.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/servers/extension_backend.dart
- dwds/pubspec.yaml
- dwds/test/devtools_test.dart
- dwds/test/fixtures/fakes.dart
- webdev/pubspec.yaml
@grouma This seems to solve the issue described in #901 (https://github.com/dart-lang/webdev/pull/901#issuecomment-586438132). The issue was that when DevTools is connected, `connectedInstanceId` is not-null so it wasn't destroying/re-creating the isolate (but it did when it was `null`). I was able to repro this in a test by copying the `destroys and recreates the isolate during a page refresh` test into `devtools_test` (or at least, I believe I have - it doesn't seem to complete without the fix, and passes after the fix - I'm not sure why it's not timing out though).
Does this seem like a reasonable fix (and also copying the test)?
(I don't know if all tests pass yet, I'm having some issues with a few locally - but they seem to fail before the change, so I'll see what happens o Travis).
> Destroy isolate during connect request even when there's a connected client

- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/handlers/injected_handler.dart
- dwds/lib/src/loaders/strategy.dart
- dwds/test/fixtures/fakes.dart
Elements of the Require Loader bootstrap are expected to be globally available, e.g. the [customModulePaths](https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/loaders/require.dart#L225). Previously we were injecting the bootstrap within the main module.
This change cleans up the injection logic so that the bootstrap is injected globally at the end. The injected client must occur inside the root module so I've added documentation to make that clear. I've also removed the logic which changes the hot restart handler as that is no longer used.
> Inject loader bootstrap at the root

- dwds/CHANGELOG.md
- dwds/lib/src/dwds_vm_client.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- Ensure we only return from a `hotRestart` after the corresponding `isolateStart` event
- Don't fail if the `hotRestart` falls back to a full reload
> Fixes to hotRestart

- dwds/lib/src/debugging/modules.dart
The recent change in module logic introduced a race condition in which we prematurely execute the evaluation to get the source to module mapping. This issue doesn't show up in our E2E tests because the applications are too small. All of the sources are already loaded by the time we execute the evaluation. Long term this won't be an issue as we'll forgo the evaluation and speak directly to the compiler to get the required metadata.
> Lazily get modules

- webdev/test/daemon/app_domain_test.dart
Let's see if skipping this test resolves the flakiness of Windows test.
Related to webdev/issues/924
> Skip flaky Window test

- dwds/lib/src/debugging/location.dart
- dwds/lib/src/services/expression_evaluator.dart
- fixed off-by-one error in translation of js location to dart locations
- fixed a typo in printing verbose messages
- made location printing concise and recognizable
Fixes #938
> Fix error in js-to-dart location lookup for eval

- dwds/CHANGELOG.md
- dwds/pubspec.yaml
Drops transitive dependency on pkg:package_resolver
> dwds: support latest pkg:shelf_packages_handler

- dwds/lib/src/debugging/dart_scope.dart
Recent SDK update brought changes in descriptions and types
of properties that were chosen not to be shown to the users,
and broke heuristics for calculation those fields.
Update those heuristics.
fixes build break:
https://travis-ci.org/github/dart-lang/webdev/builds/677981606
> Fix test break due to an SDK update

- dwds/lib/src/services/expression_evaluator.dart
- dwds/test/variable_scope_test.dart
A few redundant messages are showing in the error log, and a repeated "InternalError: InternalError: ..." message is shown on internal error coming from the frontend server. Remove them.
> remove unnecessary error messages in expression evaluation

- dwds/CHANGELOG.md
- dwds/lib/src/injected/client.js
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- dwds/test/fixtures/fakes.dart
- dwds/web/client.dart
Closes https://github.com/dart-lang/webdev/issues/962 and sneak in a forward fix to the latest `package:sse` change.
**To make our intentions explicit:**
We'll continue to support Edge as long as it continues to be minimal effort and the browser does not diverge significantly from Chrome.
> Support Edge

- dwds/lib/src/services/expression_evaluator.dart
Some objects (like formal parameter rootWidget below), even if captured on stack, 
currently appear as null on stack but can be evaluated in an expression correctly.
Do not substitute variable for its value if value is null.
For example:
```
class WidgetBinding {
void scheduleAttachRootWidget(Widget rootWidget) {
Timer.run(() {
attachRootWidget(rootWidget); // shows rootWidget as null
});
}
}
```
> Fix displaying objects in captures in expression evaluation

- .travis.yml
- frontend_server_client/CHANGELOG.md
- frontend_server_client/LICENSE
- frontend_server_client/README.md
- frontend_server_client/lib/frontend_server_client.dart
- frontend_server_client/lib/src/frontend_server_client.dart
- frontend_server_client/mono_pkg.yaml
- frontend_server_client/pubspec.yaml
This is just a skeleton, please specifically review the planned [SDK versioning policy](https://github.com/dart-lang/webdev/pull/972/files#diff-09108d6152121a2f9e03b46469bc0ff5R8) in the README.md file, which is how I propose we deal  with breaking changes in the frontend_server itself, now that we will have a _package_ which depends on its api.
@aam @alexmarkov  please add anybody else who cares about frontend_server in the sdk and the ability to do breaking changes in it.
cc @jonahwilliams
> initial setup for the new frontend server client package + sdk versioning policy

- dwds/CHANGELOG.md
- dwds/lib/src/connections/app_connection.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
We recently fixed an [issue](https://github.com/dart-lang/sse/pull/26) in `package:sse` that ensures the `sink.close` event fires. This highlighted an issue with our reconnection logic. We don't properly shutdown the existing connection upon reuse. Thus after the keep-alive timer completes, we would inadvertently destroy the existing isolate:
https://github.com/dart-lang/webdev/blob/e6491c5826e89d83b0fd3a6db732e920bc02e1ce/dwds/lib/src/handlers/dev_handler.dart#L250
Actively shutting down the connection resolves the issue as the corresponding keep-alive timer is killed:
https://github.com/dart-lang/sse/blob/e5cf68975e8e87171a3dc297577aa073454a91dc/lib/src/server/sse_handler.dart#L132
I wish I could provide a solid test for this but it's a race condition so can't come up with anything good …
> Shutdown connection upon reuse

- analysis_options.yaml
- dwds/lib/data/serializers.dart
- dwds/lib/src/connections/debug_connection.dart
- dwds/lib/src/debugging/execution_context.dart
- dwds/lib/src/debugging/inspector.dart
- dwds/lib/src/debugging/libraries.dart
- dwds/lib/src/debugging/webkit_debugger.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/handlers/injected_handler.dart
- dwds/lib/src/loaders/frontend_server_require.dart
- dwds/lib/src/readers/proxy_server_asset_reader.dart
- dwds/lib/src/servers/extension_backend.dart
- dwds/lib/src/servers/extension_debugger.dart
- dwds/lib/src/services/debug_service.dart
- dwds/lib/src/services/expression_evaluator.dart
- webdev/lib/src/daemon/app_domain.dart
Normalize imports:
- use relative imports with `lib/`
- add the relevant lint to the analysis_options file
I'm not sure if it's still the case (perhaps this changed with the CFE?), but historically, mixing `lib/` and package: self reference imports would create two separate libraries.
> normalize imports

- dwds/lib/src/debugging/classes.dart
- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/debugging/remote_debugger.dart
- dwds/lib/src/debugging/webkit_debugger.dart
- dwds/lib/src/servers/extension_debugger.dart
- dwds/pubspec.yaml
- dwds/test/fixtures/fakes.dart
- replace several uses of `sendCommand ()` with the typed equivalent calls in `package:webkit_inspector_protocol`
No issues were found, but this generally reduces the chance of typos.
> use package:webkit_inspector_protocol in more places

- dwds/lib/src/debugging/inspector.dart
- dwds/test/chrome_proxy_service_test.dart
- use a more terse name for isolates
This is a ~better match for how the VM assigns isolate names, and helps us with the isolate selectors display in DevTools.
> use a more terse name for isolates

- dwds/CHANGELOG.md
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- dwds/test/chrome_proxy_service_test.dart
- change the failure results for `getClassList` and `reloadSources `
Throwing something other than an `RPCError` from these methods is interpreted as a server crash by package:vm_service; it does get wrapped with an RPCError, but loses a bit of semantic intent (and does things like include a stack trace in the error message).
For the next version of `package:vm_service`, we'll be able to use constants for the RPCError failure codes.
> change the failure results for getClassList and reloadSources

- frontend_server_client/example/app/index.html
- frontend_server_client/example/web_client.dart
- frontend_server_client/lib/src/dartdevc_bootstrap_amd.dart
- frontend_server_client/lib/src/dartdevc_frontend_server_client.dart
- frontend_server_client/lib/src/frontend_server_client.dart
- frontend_server_client/pubspec.yaml
Also updates the web example with a repl so you can change the message and it will recompile the app, which you can reload and see the new message.
This bootstrapping mostly mirrors the flutter web bootstrapping code.
> add bootstrapping for amd to frontend_server_client

- frontend_server_client/lib/src/dartdevc_frontend_server_client.dart
- frontend_server_client/lib/src/frontend_server_client.dart
we need this internally, and it can be nice for debugging to pass the dart entrypoint from your sdk
> allow a custom frontend server path

- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/handlers/injector.dart
- dwds/test/handlers/injector_test.dart
As of https://github.com/dart-lang/webdev/pull/999 we no longer have a "root" `SseHandler`. Instead we create an `SseHandler` next to the entrypoint. We need to update the logic to handle the scenario where we may have multiple disjoint entrypoints.
> Create an SseHandler for each entrypoint

- dwds/CHANGELOG.md
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/test/chrome_proxy_service_test.dart
- use constants for stream names
- change `streamListen` to return an `RPCError` / error code `-32601` for streams that are not handled
- remove references to a closed issue
> `streamListen` changes

- dwds/lib/src/handlers/dev_handler.dart
- dwds/pubspec.yaml
- add logging for vm_service and chrome debugging traffic
- rev to a new version of `package: webkit_inspection_protocol` to use the `onSend` and `onReceive` APIs
- use the new `WipRuntime.onExecutionContextCreated` API (instead of filtering general eventStream events)
cc @grouma @DanTup
> add logging for vm_service and chrome debugging traffic

- dwds/lib/src/debugging/inspector.dart
- dwds/test/chrome_proxy_service_test.dart
- dwds/test/inspector_test.dart
- change what we report as the isolate's root library (instead of reporting the generated bootstrap library, we report the app entry point library)
Most of the change here is just changing which library we use when running tests.
DevTools uses the `isolate.rootLib` to know which file to open initially when debugging an app.
> change what we report as the isolate's root library

- dwds/lib/src/debugging/dart_scope.dart
- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/debugging/frame_computer.dart
- dwds/lib/src/debugging/instance.dart
- dwds/lib/src/debugging/metadata.dart
- dwds/lib/src/servers/extension_debugger.dart
- dwds/lib/src/services/expression_evaluator.dart
- dwds/lib/src/utilities/objects.dart
- dwds/pubspec.yaml
- dwds/test/debugger_test.dart
- dwds/test/extension_debugger_test.dart
- dwds/test/fixtures/debugger_data.dart
- webdev/pubspec.yaml
Optimize the backend calls we make for frame creation:
- rev to use the latest version of `package:webkit_inspection_protocol` (note: as package:test depends on webkit_inspection_protocol, this will select an older version of test until package:test is republished)
- use the `this` object from the JS frame instead of making a remote eval call
- don't iterate over the (very large) DDC closure scopes in JS frames
- add the synthetic 'return value' variable to a returned frame if its available (this isn't done by the VM implementation, but will be useful to add to the VM)
- we now display local variables in the order they appear in the method (instead of sorted lexically); this maps well to how other debuggers work
- fix an issue where the dart frame index wouldn't align with the js frame we …
> optimize the backend calls we make for frame creation

- dwds/CHANGELOG.md
- dwds/lib/src/injected/client.js
- dwds/web/client.dart
- dwds/web/reloader/require_restarter.dart
- dwds/web/run_main.dart
The injected client runs the main method by adding a script tag. If CSP is enforced this will fail as the script tag does not have a nonce as defined by the [spec](https://w3c.github.io/webappsec-csp/#grammardef-base64-value). Update the logic to include a nonce if one is available.
> Allow runMain to work with CSP enforced

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/inspector.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/test/chrome_proxy_service_test.dart
- implement the getMemoryUsage API call
- some misc fixes to the `VMTimeline` tests (looks like there was a likely copy paste error with the clearVMTimeline calls)
> implement the getMemoryUsage API call

- dwds/lib/src/servers/extension_debugger.dart
This is an error as of https://github.com/google/webkit_inspection_protocol.dart/pull/61
> Fix type error with GlobalObjectClearedEvents

- dwds/CHANGELOG.md
- dwds/lib/src/injected/client.js
- dwds/web/client.dart
We can get a mixed content error for URLs that start with `localhost`. Since there's no concern with adjusting all URLs that start with `localhost,` update the logic to do so.
> Fix Protocol for localhost URLs

- webdev/CHANGELOG.md
- webdev/lib/src/serve/dev_workflow.dart
- webdev/lib/src/version.dart
- webdev/pubspec.yaml
- Fix an issue where we would always build all directories when using the `serve` command
- Prep for publish
Closes https://github.com/dart-lang/webdev/issues/1023
> Don't always build everything with serve

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/classes.dart
- dwds/lib/src/debugging/inspector.dart
- dwds/lib/src/debugging/instance.dart
- dwds/lib/src/debugging/libraries.dart
- dwds/lib/src/debugging/metadata/class.dart
- dwds/lib/src/debugging/metadata/function.dart
- dwds/lib/src/debugging/metadata/provider.dart
- dwds/lib/src/debugging/modules.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- dwds/test/debugger_test.dart
- dwds/test/fixtures/fakes.dart
- dwds/test/metadata/class_test.dart
- webdev/pubspec.yaml
- Split `metadata.dart` into `metadata/function.dart` and `metadata/class.dart`
- Create abstract `MetadataProvider` which provides:
- Libraries
- Scripts and parts
- Modules
- Create `ChromeMetadataProvider` which collects metadata through a running application in Chrome
- Create boilerplate for `FileMetadataProvider` which will collect data through DDC output
- See https://dart-review.googlesource.com/c/sdk/+/144243
> Configurable Metadata Collection

- dwds/lib/src/services/chrome_proxy_service.dart
- use createId() when returning an ErrorRef (the `result.objectId` value won't be meaningful to the vm service client)
- move `getSupportedProtocols` in the source file to be next to related methods
@grouma
> use createId() when returning an ErrorRef

- dwds/CHANGELOG.md
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/pubspec.yaml
- dwds/test/chrome_proxy_service_test.dart
- return RPCError.kMethodNotFound from unimplemented methods
- fix https://github.com/dart-lang/webdev/issues/781
> return RPCError.kMethodNotFound from unimplemented methods

- dwds/CHANGELOG.md
- dwds/lib/src/injected/client.js
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- dwds/web/reloader/require_restarter.dart
The main function was prematurely called for a hot reload which could cause errors specifically with Flutter Web. Wait until after we call DDC's hot reload to call main.
Prepare for release and add missing changelog for:
https://github.com/dart-lang/webdev/pull/1055
Towards https://github.com/flutter/flutter/issues/59718
> Fix hot reloads

- dwds/CHANGELOG.md
- dwds/lib/src/injected/client.js
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- dwds/web/reloader/require_restarter.dart
Towards https://github.com/flutter/flutter/issues/60273
We previously used to call `runMain` on the server side after a `hotRestart` request. This resulted in the main method getting requested even with no module updates. We [aligned](https://github.com/dart-lang/webdev/pull/997) the `legacy` and the `require` module strategies to call `runMain` on the client side as a part of the `hotRestar` request. This resulted in the linked issue above.
> Hot Restart with no changed modules

- dwds/CHANGELOG.md
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
@grouma I noticed I'd only updated changelog/version for the Chrome extension in #1067, and not dwds. Wasn't sure whether to include `-dev` here or not though!
> Update dwds version/changelog for WebSocket support in debug backend

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/dart_scope.dart
- dwds/test/fixtures/debugger_data.dart
As of Dart SDK version `2.9.0-19.0.dev` the Dart library scope is of the form `import__`. Update the filtering logic to use this new scope name.
> Improve scope filtering heuristic

- dwds/CHANGELOG.md
- dwds/lib/dwds.dart
- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/debugging/location.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/services/debug_service.dart
- dwds/test/debugger_test.dart
- dwds/test/fixtures/server.dart
- dwds/test/reload_test.dart
- Use `setBreakpointsByUrl` to set breakpoints using a regex based on the module path
- Chrome now handles re-establishing breakpoints upon refresh so remove the corresponding deprecated argument
Closes https://github.com/dart-lang/webdev/issues/1076
> Set breakpoints by regex URL

- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/pubspec.yaml
Closes https://github.com/dart-lang/webdev/issues/1082
> Update to latest vm service

- dwds/pubspec.yaml
- frontend_server_client/pubspec.yaml
- frontend_server_common/pubspec.yaml
The dependency on file will block the roll to null-safe file, process, platform deps in the Flutter SDK, which required a major version bump due to the removal of record/replay functionality.
If this package was being used, it would be safe to increase the range to <= 7.0.0, but there were no uses I could find.
> remove file dependency

- dwds/test/devtools_test.dart
The `can not launch devtools for the same app in multiple tabs` test appears to be flaky because we attempt to launch DevTools before the page is fully loaded. There isn't a good asynchronous signal for this so as an alternative we wait for the page content to say `Hello World!`. This  closes https://github.com/dart-lang/webdev/issues/1084.
> Reduce devtools_test.dart flakiness

- dwds/CHANGELOG.md
- dwds/lib/src/dwds_vm_client.dart
- dwds/lib/src/services/debug_service.dart
- dwds/test/debug_service_test.dart
Creates a service extension, `_yieldControlToDDS`, which always returns
`Success`. This extension should place DWDS in single client mode so VM
service clients are required to connect through DDS.
See https://github.com/dart-lang/webdev/issues/1091
> Add initial DDS support

- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/debugging/frame_computer.dart
- dwds/lib/src/debugging/inspector.dart
- dwds/lib/src/debugging/location.dart
- dwds/lib/src/debugging/modules.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/services/expression_evaluator.dart
- dwds/test/dart_uri_test.dart
- dwds/test/debugger_test.dart
- dwds/test/fixtures/debugger_data.dart
- dwds/test/fixtures/fakes.dart
Sending all `scriptParsedEvent`s is on the critical path for DevTools IPL. These events are used to blackbox the SDK and translate paused frames to Dart. With this change, we no longer need all events, just the `scriptParsedEvent` for the Dart SDK. I'll follow this change by modifying the Dart Debug Extension to only send that single event.
> Remove frame dependency on ScriptID

- webdev/CHANGELOG.md
- webdev/lib/src/pubspec.dart
- webdev/lib/src/version.dart
- webdev/pubspec.yaml
- webdev/test/integration_test.dart
Once published this will resolve https://github.com/dart-lang/build/pull/2809.
Note this backs out changes in https://github.com/dart-lang/webdev/pull/1070.
I'll follow up with a dev release version of webdev.
> Rollback 2.6.0

- dwds/lib/src/debugging/metadata/module_metadata.dart
- Remove fileUris from metadata since they are not used.
> Remove fileUris from metadata

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/metadata/module_metadata.dart
- dwds/lib/src/debugging/metadata/provider.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/test/frontend_server_evaluate_test.dart
Update metadata in preparation for metadata version change in the SDK
- Update metadata version to 2.0.0
- Add support for version 2.0.0 and 1.0.0
- Log error on failure to read metadata
- Skip reading empty metadata
- Update changelog. 
**Note**
The original code ignored exceptions on metadata read so the debugger would start but fail to
set breakpoints or do expression evaluation later.  This change makes debugger fail to start if 
the metadata reading fails.
Related: https://github.com/dart-lang/sdk/issues/43458
> Update metadata version

- dwds/lib/src/debugging/frame_computer.dart
- dwds/lib/src/debugging/inspector.dart
- dwds/lib/src/debugging/location.dart
- dwds/lib/src/debugging/modules.dart
- dwds/lib/src/readers/asset_reader.dart
- dwds/lib/src/readers/frontend_server_asset_reader.dart
- dwds/lib/src/readers/proxy_server_asset_reader.dart
- dwds/lib/src/servers/devtools.dart
- dwds/lib/src/servers/extension_backend.dart
Since Dart 2.1, Future and Stream have been exported from dart:core
> Remove unused dart:async imports

- dwds/lib/dwds.dart
- dwds/lib/src/debugging/inspector.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/services/debug_service.dart
- dwds/lib/src/utilities/shared.dart
- dwds/pubspec.yaml
- dwds/test/chrome_proxy_service_test.dart
- dwds/test/fixtures/fakes.dart
- webdev/CHANGELOG.md
- webdev/lib/src/command/configuration.dart
- webdev/lib/src/command/serve_command.dart
- webdev/lib/src/serve/webdev_server.dart
- webdev/lib/src/version.dart
- webdev/pubspec.yaml
Users can prevent DDS from being spawned by providing the --disable-dds flag to `webdev serve`.
> Add capability to spawn a Dart Developer Service instance from DWDS and webdev serve

- dwds/lib/src/services/debug_service.dart
- dwds/lib/src/utilities/shared.dart
Corp hostnames are bound to IPv4 addresses, so attempting to bind to a hostname with `ipv6: true` causes an exception to be thrown.
> Make DDS bind to the provided hostname instead of localhost

- dwds/lib/src/debugging/metadata/provider.dart
- dwds/test/metadata_test.dart
We incorrectly removed the error handling in a previous PR. Add it back with a corresponding test.
> Handle metadata parse errors

- dwds/CHANGELOG.md
- dwds/lib/dwds.dart
This is actually required as DWDS will fail in unexpected ways if it is null.
> Require MetadataProvider

- dwds/lib/src/services/chrome_proxy_service.dart
I tried to create a corresponding test for this but it was difficult given that the root cause is due to a race condition. It appears that client of the service may issue a `destroyIsolate` call prior to the previous `createIsolate` being fully instantiated.
cc @jonahwilliams
> Handle null consoleSubscription

- dwds/CHANGELOG.md
- dwds/lib/dwds.dart
- dwds/lib/src/readers/asset_reader.dart
- dwds/lib/src/readers/frontend_server_asset_reader.dart
- dwds/lib/src/readers/proxy_server_asset_reader.dart
- dwds/test/debugger_test.dart
- dwds/test/fixtures/context.dart
- dwds/test/metadata_test.dart
- frontend_server_common/lib/src/asset_server.dart
- frontend_server_common/lib/src/devfs.dart
- webdev/CHANGELOG.md
- webdev/lib/src/serve/webdev_server.dart
proxyHandler is creating new http client if none is passed to it,
and this client is never closed, which causes the program to hang
in some scenarios - for example, in a coming expression evaluation
feature where the expression compiler worker is running in an
isolate, communicating with webdev isolate using send/receive
ports.
- pass an http client to all proxyHandlers
- close that client on exit
- cleanup running services on context.setup fail so to the
subsequent setup retries do not fail due to services stil
running.
> Close http connections on dwds and webdev_server exit

- webdev/lib/src/command/configuration.dart
- webdev/lib/src/command/serve_command.dart
- webdev/lib/src/command/shared.dart
Previously `disable-dds` flag was only available for `webdev serve` command only, but we run `dds` with other webdev commands as well. Move it to common flags instead.
> Make disable-dds flag shared for all webdev commands

- dwds/dart_test.yaml
- dwds/lib/src/services/expression_compiler_service.dart
- webdev/lib/src/command/daemon_command.dart
- webdev/test/e2e_test.dart
Previously, some of the responses to requests from VSCode were arriving out of order.
In this change:
- make sure requests and responses in expression compilation service match
- address latests minor CR comments from the initial expression evaluation PR
- make daemon logger not emit low-level messages in non-verbose mode
Closes: https://github.com/dart-lang/webdev/issues/1134
> Synchronize requests and responses to expression compilation service

- dwds/lib/src/debugging/frame_computer.dart
- dwds/test/debugger_test.dart
- dwds/test/fixtures/debugger_data.dart
- remove duplicate async frames
- remove any trailing async frame
This address issues seen in the debugger - due to how we calculate stack frames, we can create multiple adjacent async frame markers (and, can have a trailing async frame marker after all actual frames). In this image, they're the 'async gap' frames.
> remove duplicate async frames

- dwds/CHANGELOG.md
- dwds/lib/src/loaders/frontend_server_require.dart
- dwds/test/fixtures/context.dart
I don't think we can generically provide digests from `package:dwds`. However, with this callback support, Flutter Tools should be able to fully consume this abstraction and reduce the code duplication.
See https://github.com/flutter/flutter/pull/68235
> Support DigestProvider in FrontendServerRequireStrategyProvider

- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/services/expression_compiler_service.dart
- dwds/test/build_daemon_evaluate_test.dart
- dwds/test/fixtures/context.dart
- dwds/test/fixtures/logging.dart
- dwds/test/frontend_server_evaluate_test.dart
- fixtures/_test/lib/library.dart
- fixtures/_test/pubspec.yaml
- fixtures/_testPackage/lib/test_library.dart
- fixtures/_testPackage/pubspec.yaml
- fixtures/_testPackage/web/main.dart
- webdev/lib/src/logging.dart
- webdev/lib/src/serve/webdev_server.dart
Remove ddc asset handler, fixed logging issues
- Remove target from expression compiler service so it can work
with already defined asset server
- use already existing asset handler for ddc expression
compilation service
- remove "target" from ExpressionCompilerService.start
- make BuildRunnerRequire use server paths for dill paths
- add tests covering evaluation in libraries
- fix logging problems
- remove 'null's printed in logs
- remove double logging by only having one log record subscription
- emit all messages in verbose mode
- add test logging setup so we can control logging from dwds tests
> Remove ddc-specific asset server

- webdev/CHANGELOG.md
- webdev/README.md
- webdev/lib/src/daemon/app_domain.dart
- webdev/lib/src/pubspec.dart
- webdev/test/integration_test.dart
We probably should add a readme test to ensure the referenced SDK is updated.
> Remove Flutter Web references

- dwds/CHANGELOG.md
- dwds/lib/dwds.dart
This should have been exported when initially implemented.
Closes https://github.com/dart-lang/webdev/issues/1182
> Export AbsoluteImportUriException

- dwds/CHANGELOG.md
- dwds/lib/src/services/expression_compiler_service.dart
- dwds/test/expression_compiler_service_test.dart
Fixed incorrect location for libraries.json causing severe failure when running webdev with 
`--enable-expression-evaluation`, added test to make sure expression compiler service can run its basic operations
with no errors.
Closes: https://github.com/dart-lang/webdev/issues/1195
> Fixed incorrect location for libraries.json and added test

- dwds/CHANGELOG.md
- dwds/debug_extension/CHANGELOG.md
- dwds/debug_extension/build.yaml
- dwds/debug_extension/pubspec.yaml
- dwds/debug_extension/web/background.dart
- dwds/debug_extension/web/background.js
- dwds/debug_extension/web/manifest.json
- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/test/debugger_test.dart
We no longer need to black box the Dart SDK as we now leverage Chrome's skipList which essentially serve the same purpose. There is a very minor stepping performance regression as we don't send all cached skipLists but I intend to fix this in a follow up PR.
The blackbox logic was the remaining bit of logic that required the script parsed events. With that gone, we can now ignore the events entirely.
> Don't send scriptParsedEvents with skipList support

- frontend_server_client/CHANGELOG.md
- frontend_server_client/lib/src/frontend_server_client.dart
- frontend_server_client/lib/src/shared.dart
- frontend_server_client/pubspec.yaml
Looks like `package:file` wasn't actually used. Remove `package:uuid` and prepare to publish. Closes https://github.com/dart-lang/webdev/issues/1199
> Remove deps and prepare to publish

- README.md
- webdev/README.md
- Create a new top level README (no longer a symlink to the webdev version)
- Update the webdev README to not contain top level information
> New top level README

- fixtures/_webdevSmoke/web/scopes_main.dart
- fixtures/_webdevSoundSmoke/pubspec.yaml
- fixtures/_webdevSoundSmoke/web/index.html
- fixtures/_webdevSoundSmoke/web/main.dart
- webdev/CHANGELOG.md
- webdev/README.md
- webdev/lib/src/command/configuration.dart
- webdev/lib/src/command/shared.dart
- webdev/test/configuration_test.dart
- webdev/test/e2e_test.dart
Add support for `sound-null-safety` flag with the following behavior:
If provided, `package:build_runner` will be run with sound null safety support. If negated, `package:build_runner` will be run without sound null safety support. If  not provided, the default `package:build_runner` behavior is used.
Closes https://github.com/dart-lang/webdev/issues/1217
> Support sound null safety flag

- dwds/lib/src/events.dart
- dwds/test/events_test.dart
We weren't properly returning a broadcast stream and therefore it could not be listened to multiple times.
> Allow eventStream to be listened to multiple times

- dwds/CHANGELOG.md
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/services/expression_compiler.dart
- dwds/lib/src/services/expression_compiler_service.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- dwds/test/expression_compiler_service_test.dart
- dwds/test/fixtures/context.dart
- frontend_server_common/lib/src/frontend_server_client.dart
- webdev/lib/src/serve/webdev_server.dart
Before this change the `ExpressionCompilerService` would eagerly load the DDC SDK. However, we need to conditionally load the correct SDK based off null safety support. We will determine the null safety support from the DDC metadata files so we must lazily start the service after the entrypoint is determined.
> Lazily Initialize ExpressionService

- dwds/lib/src/services/chrome_proxy_service.dart
Blaze uses `.ddc` in the name of the kernel summary, and `.ddk` in the full dill file.
This change help pass correct name for summaries in google3 case only. 
Note that the change is temporary and makes sure that evaluation works with summary files,  as supported by the following changes in google3:
https://critique-ng.corp.google.com/cl/353115269
The hack is going to be removed after the google3 changes is checked in and the following issues are resolved in the SDK:
https://github.com/dart-lang/sdk/issues/43684
https://github.com/dart-lang/sdk/issues/44742
> Added temporary hack to allow google3 to find summaries

- dwds/CHANGELOG.md
- dwds/lib/src/services/expression_compiler_service.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
Some users of ExpressionCompilerService do not have the port at time of construction. Allow for `FutureOr` to lazily provide the port.
> FutureOr<int> port ExpressionCompilerService

- dwds/lib/src/debugging/metadata/module_metadata.dart
- dwds/lib/src/debugging/metadata/provider.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/test/build_daemon_evaluate_test.dart
- dwds/test/metadata_test.dart
- fixtures/_testPackageSound/lib/src/version.dart
- fixtures/_testPackageSound/lib/test_library.dart
- fixtures/_testPackageSound/pubspec.yaml
- fixtures/_testPackageSound/web/index.html
- fixtures/_testPackageSound/web/main.dart
- fixtures/_testSound/example/append_body/index.html
- fixtures/_testSound/example/append_body/main.dart
- fixtures/_testSound/example/hello_world/index.html
- fixtures/_testSound/example/hello_world/main.dart
- fixtures/_testSound/example/hello_world/part.dart
- fixtures/_testSound/lib/library.dart
- fixtures/_testSound/pubspec.yaml
- fixtures/_webdevSoundSmoke/pubspec.yaml
- fixtures/_webdevSoundSmoke/web/main.dart
- webdev/CHANGELOG.md
- webdev/README.md
- webdev/lib/src/command/configuration.dart
- webdev/lib/src/command/shared.dart
- webdev/test/configuration_test.dart
- webdev/test/e2e_test.dart
- Update metadata to include null safety option for a module
- Read null safety information from the module metadata and pass
it to ExpressionCompiler.initialize()
- Add contents to _webdevSoundSmoke to text evaluation in sound mode
- Added sound null safety tests for expression evaluation in dwds when using
build_web_compilers to compile.
- Changed `--sound-null-safety` flag to a `--null-safety=<sound, unsound, auto>`
to make its tri-state nature explicit
> Read null safety option from metadata

- dwds/lib/src/services/chrome_proxy_service.dart
Updated temporary guessing of summary location paths to work with sound null safety in google3.
> Updated google3 summary paths location

- dwds/CHANGELOG.md
- dwds/lib/src/injected/client.js
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- dwds/web/reloader/require_restarter.dart
When we add modules to the `_dirtyModule` `SplayTree` we add them in topological order. If we don't have order information, for example for SDK sources, we throw an exception. Previous this exception wasn't caught which would cause the hot restart to hang. Now we capture the exception and fall back on a full reload.
Fixes https://github.com/flutter/flutter/issues/74527
> Fix hot restarts with Flutter SDK sources

- dwds/CHANGELOG.md
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/services/debug_service.dart
Our internal infrastructure actively kills long standing connections after a set period of time. We work around this issue by providing keep-alive configs to `package:sse`. However, our configuration was either missing or invalid for certain situations. See included comment for further details.
> Update keep-alive configs

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/metadata/provider.dart
- dwds/lib/src/injected/client.js
- dwds/lib/src/loaders/build_runner_require.dart
- dwds/lib/src/loaders/frontend_server_require.dart
- dwds/lib/src/loaders/legacy.dart
- dwds/lib/src/loaders/require.dart
- dwds/lib/src/loaders/strategy.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- dwds/test/fixtures/fakes.dart
We would like to customize the URIs contained in the dependency map. Internally we would like to use absolute file paths while externally with `package:build_runner` we would like to use `HTTP` URIs. Add `moduleInfoForEntrypoint` as a part of the `LoadStrategy` to support his customization.
> ModuleInfo for Entrypoint in LoadStrategy

- dwds/CHANGELOG.md
- dwds/debug_extension/CHANGELOG.md
- dwds/debug_extension/pubspec.yaml
- dwds/debug_extension/web/background.dart
- dwds/debug_extension/web/background.js
- dwds/debug_extension/web/manifest.json
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/servers/extension_debugger.dart
Update extension such that:
- It has an internal set of extensions to communicate with
- It has an internal set of events on which to notify other extensions
- It supports the following methods through cross-extension communication
- `startDebugging` - initiates debugging on the current active tab
- `encodedUri` - returns the encoded VM service protocol URI for the provided tabID
- `sendCommand` - to send commands to the debugged tab
Testing this is gonna be gnarly. I'm hesitant to provide hooks specific for testing like we do for the[ extension debug tests](https://github.com/dart-lang/webdev/blob/master/dwds/test/debug_extension_test.dart). One possibility is to create another stub extension specific for testing this behavior but that seems pretty wonky. I'm open to suggestions. …
> Support cross-extension communication

- dwds/CHANGELOG.md
- dwds/lib/dwds.dart
- dwds/lib/src/services/debug_service.dart
We use `keepAlive` with `package:sse` as our internal proxy servers will actively kill connections after a set period of time. Keeping the `keepAlive` timeout too long causes issues if a user closes a debug session and tries to start a new one in the `keepAlive` window. Ideally, the Dart Debug Extension would send a close event. Or alternatively an implicit close event is sent as a part of the `package:sse` protocol.
> Update keepAlive configs

- dwds/debug_extension/CHANGELOG.md
- dwds/debug_extension/pubspec.yaml
- dwds/debug_extension/web/background.dart
- dwds/debug_extension/web/background.js
- dwds/debug_extension/web/manifest.json
The response from `dwds.startDebugging` never completes, even when Dart DevTools is successfully launched and we connect to the provided debug service URI. According to the Chrome Extension documentation,  if `sendResponse` is not called synchronously in the message handler, it will be invoked automatically. However that doesn't seem to be the case. Explicitly call the handler to better adhere to the API.
> Return cross extension debug response

- dwds/lib/dwds.dart
- dwds/lib/src/services/debug_service.dart
Reducing the `keepAlive` causes the connection to be flaky internally. Extend the timer to prevent flakiness knowing that relaunching in the 5 second window could cause issue. This gives more reason to implement https://github.com/dart-lang/sse/issues/44
> Extend keepAlive

- dwds/debug_extension/web/background.dart
- dwds/debug_extension/web/background.js
- dwds/lib/dwds.dart
- dwds/lib/sockets.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/handlers/injector.dart
- dwds/lib/src/injected/client.js
- dwds/lib/src/sockets.dart
- dwds/test/fixtures/server.dart
- dwds/test/handlers/injector_test.dart
- dwds/test/reload_test.dart
- dwds/web/client.dart
- dwds/web/reloader/manager.dart
This adds support for WebSockets for the injected client.
It does not yet implement any "keepalive". The WebSockets do their own keep-alive to keep the connection alive, but a page refresh will disconnect/reconnect the connection (although that seems to work fine in my testing - I could reload multiple times, and then trigger breakpoints).
I did see a disconnect when testing after leaving it for a while (I was AFK for > 10min), though I haven't done enough testing to fully understand that yet (it could've been the proxy drop it, or it could've been my WiFi). We could always add WS keepalives/reconnections later if this seems to be a problem.
I added a test that the injector is inserting the right scheme, ~~although I couldn't find if there are integration tests that fully test the …
> Support websockets for injected client

- dwds/lib/src/services/chrome_proxy_service.dart
We encounter an intermittent failure to start expression compiler that manifests as failing `getcwd` system call.
Waiting for the debugger to be ready before initializing the entrypoint fixes the problem - looks like there is a race condition between expression compiler isolate calling `getcwd` (in `Uri.base()` and other calls) and `runZoneGuarded` (in `debugger._initialize()`) somehow setting or loosing it for the current process and therefore the isolate as well.
This PR unblocks expression evaluation work. 
Created an issue to follow up more thoroughly: https://github.com/dart-lang/webdev/issues/1282
> Fix disappearing current directory during isolate creation

- dwds/CHANGELOG.md
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
> Support webkit inspection and prepare to publish

- dwds/lib/src/debugging/libraries.dart
Without `orElse`, `firstWhere` throws. We handle `null` appropriately.
> Fix default rootlib

- dwds/CHANGELOG.md
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/services/expression_compiler_service.dart
- dwds/test/reload_test.dart
Dart devtools sometimes gets erroneous isolate information from dwds in the middle of hot restart,
for example, `getIsolate` does not wait for initializations of the new isolate after restart and returns 
an isolate with null ID.
This seems to cause various issues after hot restart, including exceptions in debug console, non-working
layout explorer, and disabled breakpoints in the UI. While this PR does not solve all of them yet, it makes
sure that the new isolate is initialized before VM replies to the clients after hot restart:
- reset initialization completer on `destroyIsolate`.
- make all supported VM API wait for isolate initialization before proceeding.
- add expression evaluation tests after hot restart.
Towards: https://github.com/flutter/flutter/issues/74903
Closes: …
> Initialize new isolate after restart

- dwds/lib/src/debugging/instance.dart
- dwds/test/inspector_test.dart
- dwds/test/instance_test.dart
- example/web/scopes_main.dart
Related to https://github.com/dart-lang/sdk/issues/45387
The JS object has inherited fields represented as `Symbol`s. Do a best effort collection of these fields.
> Display inherited fields

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/metadata/provider.dart
- dwds/lib/src/dwds_vm_client.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/services/expression_compiler_service.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
This fixes failures observed in VSCode during hot restart while paused. 
- Let VM proxy server know hen isolate is about to be terminated for hot restart.
- Make VM proxy not send service registration events for the terminating isolate.
- Fix errors showing classes from dart:core library.
Towards: https://github.com/flutter/flutter/issues/74903
> Do not send service registration events on terminating isolate during hot restart

- fixtures/_test/pubspec.yaml
- fixtures/_testPackage/pubspec.yaml
- fixtures/_testPackageSound/pubspec.yaml
- fixtures/_testSound/pubspec.yaml
- fixtures/_webdevSmoke/pubspec.yaml
- fixtures/_webdevSoundSmoke/pubspec.yaml
- webdev/CHANGELOG.md
- webdev/lib/src/pubspec.dart
- webdev/lib/src/version.dart
- webdev/pubspec.yaml
- webdev/test/integration_test.dart
I expanded a couple other ranges in the package itself as well in an effort to start getting the example working on the latest build_runner, but this is ultimately blocked on dwds changes.
> allow the latest build_runner, build_web_compilers, and build_daemon

- dwds/lib/src/debugging/classes.dart
- dwds/test/chrome_proxy_service_test.dart
The Class object technically should not show inherited methods. However, since we do not provide a reference to the superClass it's impossible to get this information. For now, return all inherited methods until we have the correct information in the DDC metadata files.
> Show inherited methods in Class object

- dwds/lib/src/debugging/dart_scope.dart
- dwds/test/variable_scope_test.dart
These are variables introduced by the compiler and should not be
visible in debug tools.
This is building on a temporary fix that will be removed when we
switch to metadata based solution for knowing what variables should
be visible.
> Hide variables with names that start with '__t$'

- dwds/lib/src/debugging/classes.dart
- dwds/test/chrome_proxy_service_test.dart
`Object.getOwnPropertyNames` returns setters, getters and functions. We don't need to filter this list besides the constructor. Before this change calling `proto[method[i]]` could cause a runtime issue as we were actually calling the getter or setter.
> Fix error with getObject on a ClassRef

- dwds/CHANGELOG.md
- dwds/lib/src/services/expression_compiler_service.dart
- dwds/test/build_daemon_evaluate_test.dart
- dwds/test/events_test.dart
- dwds/test/expression_compiler_service_test.dart
- dwds/test/fixtures/logging.dart
- dwds/test/frontend_server_evaluate_test.dart
- dwds/test/restore_breakpoints_test.dart
Recent flakes in CI show failures to compile expressions due to
a failure to load full kernel files. The logs are missing messages
preceding the failure. This change adds a message on kernel load
failure and makes sure the messages are printed when a test fails.
- Add reporting to load kernel in ExpressionCompilerService
- Reset logwriter for each test. Previously the messages from a
failed test were lost because the group's logwriter was using
the invoker for that group in printOnFailure.
Helps: https://github.com/dart-lang/webdev/issues/1345
> Log failures to load kernel during eval

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/instance.dart
- dwds/lib/src/utilities/objects.dart
- example/web/scopes_main.dart
Fix problems uncovered after https://github.com/dart-lang/webdev/pull/1352
- Remove obfuscation from late fields. 
Closes: https://github.com/dart-lang/webdev/issues/1179
- Update example to run without throwing exceptions.
Related: https://github.com/dart-lang/sdk/issues/46646
> Remove obfuscation from late fields, update example to not crash

- dwds/CHANGELOG.md
- dwds/lib/src/readers/proxy_server_asset_reader.dart
- dwds/test/build_daemon_evaluate_test.dart
- dwds/test/chrome_proxy_service_test.dart
- dwds/test/events_test.dart
- dwds/test/fixtures/context.dart
- dwds/test/handlers/asset_handler_test.dart
- dwds/test/restore_breakpoints_test.dart
- webdev/lib/src/serve/webdev_server.dart
Limit number of simultaneous connections to prevent SocketExceptions.
Restricting number of connections on the client to 200 causes all the extra connections 
to buffer, and eventually connect when the number of active connections drops below
the limit. This prevents SocketExceptions that cause flakes in the CI.
Removing the `maxConnectionsPerHost` on the client in new tests will repro the issue.
Hopefully fixes flaky behavior in DDR as well (pending performance measurements).
Closes: https://github.com/dart-lang/webdev/issues/1345
> Fix intermittent broken sockets on connection to asset server.

- dwds/CHANGELOG.md
- dwds/lib/src/dwds_vm_client.dart
**Issue**
A race between the app hitting a breakpoint and a hot restart was causing hot restart to hang periodically.
The race sequence was as following:
- app hits a breakpoint
- dwds gets the isolate, its eventPaused shows "Resumed", so dwds removes the breakpoints but does
not resume the isolate.
- dwds issues hot restart command to the browser
- now the breakpoint has finished processing and notification is sent to the "Debug" event stream. 
As a result, the app is paused and hot restart hangs.
**Solution**
Pause the app (if it is not already paused) forcefully and wait for the either breakpoint or the pause event on 
the debug stream before hot restarting to prevent this from happening.
Closes: https://github.com/dart-lang/webdev/issues/1359
> Fix hot restart race by pausing the app before hot restart

- dwds/lib/src/debugging/debugger.dart
The debugger filters out native JS objects using the classRef's name. Since DDC will change this representation, we need to check for the new representation.
Checked that `Flutter run for web shows no native javascript objects in static scope` succeeds with and without https://dart-review.googlesource.com/c/sdk/+/199600.
> Add check for new JS object representation

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/inspector.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/services/expression_evaluator.dart
- dwds/test/build_daemon_evaluate_test.dart
Support VMService.evaluate  with scope by
- wrapping the expression in a function with scope keys as parameters
- compiling the wrapper
- and using chrome's Runtime.callFunctionOn to evaluate the compiled
call with arguments
Will be followed up with a cleanup of try/catch additions and removals
in SDK and dwds.
Note that passing scope to VMService.evaluateInFrame is not supported yet.
Closes:  #1336
> Support VMService.evaluate with scope

- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/debugging/instance.dart
- dwds/lib/src/debugging/metadata/provider.dart
- dwds/test/build_daemon_evaluate_test.dart
Fix bugs discovered in manual testing debugging on flutter apps:
We made sure that BoundVariables are not showing native JS objects, but  missed another case - BoundFields. 
Remove native JS objects from them as well, add tests.
Closes: https://github.com/dart-lang/webdev/issues/1366
In flutter, dart:ui is an included library (from web engine) that dwds does not have in the metadata. Add it manually.
Closes: https://github.com/dart-lang/webdev/issues/1365
> Do not show native JavaScript fields, include dart:ui library

- dwds/lib/src/services/chrome_proxy_service.dart
Revert to attaching the IsolateRef instead of the Isolate to the postEvent
and registerExtension events. The Isolate is much larger and was causing
systems to run out of memory when event traffic is high like in Flutter
where they are sent on every animation frame.
See: https://github.com/flutter/flutter/issues/87100
> Avoid OOM errors when event traffic is high

- dwds/test/variable_scope_test.dart
- example/web/scopes_main.dart
Tests to prevent regressions, for example, the following one caused by an update in SDK:
Related: https://github.com/dart-lang/webdev/issues/1372
> Add more tests for native JS types in variable windows

- dwds/lib/src/debugging/inspector.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/services/expression_compiler_service.dart
- dwds/test/build_daemon_evaluate_test.dart
- dwds/test/chrome_proxy_service_test.dart
- dwds/test/events_test.dart
- dwds/test/expression_compiler_service_test.dart
- dwds/test/fixtures/context.dart
- dwds/test/fixtures/logging.dart
- dwds/test/fixtures/server.dart
- dwds/test/frontend_server_evaluate_test.dart
- dwds/test/handlers/asset_handler_test.dart
- dwds/test/restore_breakpoints_test.dart
- frontend_server_common/lib/src/asset_server.dart
- frontend_server_common/lib/src/devfs.dart
- frontend_server_common/lib/src/devfs_content.dart
- frontend_server_common/lib/src/frontend_server_client.dart
- frontend_server_common/lib/src/resident_runner.dart
- frontend_server_common/lib/src/utilities.dart
- Log http requests to asset server in tests, log request exceptions
- Make setting up logger more convenient by providing default loggers
- Log exceptions and stack traces in default loggers
- Change frontend_server_common to use the same logging mechanism 
as the rest of the code
- Log build messages and frontend_server messages by default
- Do not log expression_compiler_worker messages by default yet
since it runs in an isolate and we cannot redirect stdout/stderr to logs.
Postpone redirecting output until expression_compiler_worker moves to
a process.
> Improve logging in tests

- dwds/CHANGELOG.md
- dwds/lib/src/services/debug_service.dart
- dwds/lib/src/utilities/shared.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- dwds/test/expression_compiler_service_test.dart
Retry finding new port and binding an http server to it to recover from errors when starting debug service.
Closes: https://github.com/dart-lang/webdev/issues/1378
Parent flutter issue: https://github.com/flutter/flutter/issues/84012
> Recover from used port errors when starting debug service

- frontend_server_client/CHANGELOG.md
- frontend_server_client/lib/src/frontend_server_client.dart
- frontend_server_client/pubspec.yaml
- frontend_server_client/test/frontend_sever_client_test.dart
Fixes https://github.com/dart-lang/webdev/issues/1386
Fixes https://github.com/dart-lang/webdev/issues/1383
> Force quit frontend server after one second, unskip tests

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/classes.dart
- dwds/lib/src/debugging/instance.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- Depend on `dds` version `2.1.1`.
- Depend on `vm_service` vesrion `7.2.0`.
- Prep to publish dwds.
Needed for: https://github.com/flutter/flutter/issues/86361
> Prep to publish dwds

- webdev/CHANGELOG.md
- webdev/README.md
- webdev/pubspec.yaml
Depend on latest dwds, fix typo
> Prep webdev for publishing

- dwds/test/fixtures/utilities.dart
- frontend_server_common/lib/src/utilities.dart
- webdev/lib/src/daemon_client.dart
- webdev/lib/src/pubspec.dart
- webdev/lib/src/util.dart
- webdev/test/daemon/utils.dart
- webdev/test/e2e_test.dart
- `pub.dart.shapshot` was removed starting from 2.15.0-49.0.dev
- replace it by `dartdev.dart.snapshot pub` in webdev and tests
- all versions 2.13.0 and higher contain this snapshot so
no need to check for sdk version as it is guaranteed to be
2.13.0 or higher by our min sdk constraints.
SDK commit: https://github.com/dart-lang/sdk/commit/ae81cd5dabe63f6b6dd2edc34a8583d2e772e7d6
> Do not use pub.dart.snapshot

- .github/workflows/dart.yml
- dwds/dart_test.yaml
- dwds/mono_pkg.yaml
- dwds/test/build/min_sdk_test.dart
- example/pubspec.yaml
- mono_repo.yaml
- tool/ci.sh
- webdev/dart_test.yaml
- webdev/mono_pkg.yaml
- webdev/test/build/min_sdk_test.dart
- Run webdev and dwds tests on stable and beta
- prevent breaks on latest stable
- prevent breaks on next SDK stable release
Related: https://github.com/dart-lang/webdev/issues/1390
Closes: https://github.com/dart-lang/webdev/issues/1393
> Add running tests on min SDK and current beta

- dwds/test/build_daemon_evaluate_test.dart
- dwds/test/fixtures/context.dart
- dwds/test/frontend_server_evaluate_test.dart
- Fix test break due to changed compiler error 
Make sure the test does not break due to such changes in the future.
-  Do not use pub directly in tests as it is deprecated.
> Fix test break due to changed compiler error, do not use pub directly

- dwds/CHANGELOG.md
- dwds/lib/src/dwds_vm_client.dart
- dwds/lib/src/events.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/services/debug_service.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- dwds/test/events_test.dart
Add metrics to track DevTools IPL and VM calls on the critical path to loading DevTools app.
In addition, differentiate between errors returning `ErrorRef` and exceptions from `evaluate` and `evaluateInFrame` calls.
Closes: https://github.com/dart-lang/webdev/issues/1403
> Add metrics for devtools IPL

- dwds/CHANGELOG.md
- dwds/lib/src/dwds_vm_client.dart
- dwds/test/events_test.dart
- Change to recognize pageReady dwds event from devtools
see: https://github.com/flutter/devtools/pull/3355
- Update tests
Closes: https://github.com/dart-lang/webdev/issues/1406
Note that this change needs https://github.com/flutter/devtools/pull/3346 to actually send devtools IPL events, will be a noop for earlier versions of devtools.
> Change to recognize pageReady dwds event from devtools

- dwds/CHANGELOG.md
- dwds/lib/dwds.dart
- dwds/lib/src/dwds_vm_client.dart
- dwds/lib/src/events.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/servers/extension_backend.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/services/debug_service.dart
- dwds/test/events_test.dart
Emit events containing more metrics:
- devtools load time
- hot restart time
- full reload time
- serve requests exceptions that we no longer crash on.
Helps: https://github.com/dart-lang/webdev/issues/1419
> Added more analytics

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/inspector.dart
- dwds/lib/src/debugging/libraries.dart
- dwds/test/chrome_proxy_service_test.dart
We used to return all script refs with a library object. Change that to only include script refs from the same library.
Closes: https://github.com/dart-lang/webdev/issues/1422
> Return only scripts included in a library for library object

- dwds/lib/src/debugging/debugger.dart
Static interop changes reorganize the type hierarchy such that interop objects are now reified as "LegacyJavaScriptObject". For more context, see this stack of changes that's in the pipeline: https://dart-review.googlesource.com/c/sdk/+/215949 (the relevant bits are in `sdk/lib/_internal/js_dev_runtime/private/interceptors.dart`).
> Modify JS object check for static interop

- dwds/CHANGELOG.md
- dwds/lib/src/servers/extension_backend.dart
We start extension backend http server with port 0, which creates flakes
in flutter web tests. Find an unused port instead.
Closes: https://github.com/dart-lang/webdev/issues/1450
> Reliably find unused port to start extension backend http service on

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/debugger.dart
- dwds/test/chrome_proxy_service_test.dart
If a client sets the optional parameters offset / count in getObject, but the object they are requesting has no length, then DWDS should ignore those parameters.
Fixes #1439
> Don't fetch range if the object has no length

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/classes.dart
- dwds/test/chrome_proxy_service_test.dart
- fixtures/_test/example/hello_world/main.dart
Work towards https://github.com/dart-lang/webdev/issues/1430
Include static member information for classes now that DDC is exposing static member names (see https://github.com/dart-lang/sdk/commit/cc9353ac46be41ab1bfd4b56f33d92d3ab5ad8e8).
> Include static member information for classes

- dwds/CHANGELOG.md
- dwds/lib/dwds.dart
- dwds/lib/src/handlers/injector.dart
- dwds/lib/src/services/expression_compiler_service.dart
- dwds/lib/src/utilities/dart_uri.dart
- Some scenarios require libraries.json to be a different path from the
SDK installation directory, update `DartUri` and `ExpressionCompilerService`
to allow for that.
- Fix a bug where `dartEmitDebugEvents` was set as a `String` instead of
`bool` in the injected client.
> Fixed issues discovered in integration

- dwds/lib/src/dwds_vm_client.dart
Will hopefully fix https://github.com/dart-lang/webdev/issues/1468. It's hard to reproduce in a dev environment. 
It looks like `devToolsStart` is being set in two places:
* https://github.com/dart-lang/webdev/blob/95b3fd8e6e705a0eaad9ddd06a6dbd235b8b59e4/dwds/lib/src/handlers/dev_handler.dart#L367
* https://github.com/dart-lang/webdev/blob/95b3fd8e6e705a0eaad9ddd06a6dbd235b8b59e4/dwds/lib/src/handlers/dev_handler.dart#L515
Both of which happen right before `_launchDevTools` is called. I believe this means `devToolsStart` is set when DevTools is launched programmatically (eg, by clicking on the Dart Debug Extension), but not when a user copy-pastes the link from their terminal.
> DWDS only sends events if it has stats

- dwds/CHANGELOG.md
- dwds/lib/src/utilities/dart_uri.dart
- dwds/test/dart_uri_test.dart
Emit a warning instead of crashing on missing libraries spec (libraries.json), add tests.
> Fix crash on missing libraries.json

- dwds/lib/src/debugging/debugger.dart
Fixes https://github.com/dart-lang/webdev/issues/1475
Uses the CDP [`Overlay.setPausedInDebuggerMessage`](https://chromedevtools.github.io/devtools-protocol/tot/Overlay/#method-setPausedInDebuggerMessage) method to show the following overlay above the user's application when they are paused at a breakpoint: 
The resume / step methods work as expected and resume / step within Dart DevTools.
> Shows an overlay "Paused in Dart DevTools" when paused at a breakpoint 

- dwds/debug_extension/pubspec.yaml
A couple of the dependencies were out of date, which caused the following error when running `dart pub get`. This PR updates them to match the versions in DWDS.
```
Resolving dependencies... (1.2s)
Because analyzer >=1.0.0 <1.1.0 depends on _fe_analyzer_shared ^16.0.0 and analyzer >=1.1.0 <1.2.0 depends on
_fe_analyzer_shared ^17.0.0, analyzer >=1.0.0 <1.2.0 requires _fe_analyzer_shared ^16.0.0 or ^17.0.0.
And because analyzer >=1.2.0 <1.3.0 depends on _fe_analyzer_shared ^18.0.0, analyzer >=1.0.0 <1.3.0 requires
_fe_analyzer_shared ^16.0.0 or ^17.0.0 or ^18.0.0.
Because analyzer >=1.4.0 <1.5.0 depends on _fe_analyzer_shared ^20.0.0 and analyzer >=1.3.0 <1.4.0 depends on
_fe_analyzer_shared ^19.0.0, analyzer >=1.3.0 <1.5.0 requires _fe_analyzer_shared ^19.0.0 or ^20.0.0.
Thus, analyzer …
```
> Update dependencies for the Dart Debug Extension

- dwds/CHANGELOG.md
- dwds/lib/dwds.dart
- dwds/lib/src/handlers/dev_handler.dart
A few customers requested the ability to launch Dart DevTools in the same Chrome window as their Dart application. Currently we only launch Dart DevTools from a different Chrome window, this adds the ability to launch it from the same window.
> Add option to launch DevTools in the same Chrome window

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/debugger.dart
Temporarily disables the "Paused" overlay until we check with Chrome DevTools team if there is a way to conditionally show it based on whether they have added their overlay. 
Currently what happens is (these can happen in any order):
- DWDS adds its overlay
- Chrome DevTools add its overlay
So we have two overlays (R, S are the resume, skip buttons)
`[Paused in Chrome DevTools R S]`
`[Paused R S]`
If a user hits "Resume" in the `[Paused in Chrome DevTools R S]`, it actually triggers the "Skip" below it, so instead of resuming the debugger skips.
> Disable the "Paused" overlay

- dwds/lib/dwds.dart
- dwds/lib/src/debugging/inspector.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/services/debug_service.dart
- dwds/lib/src/services/expression_compiler_service.dart
- dwds/lib/src/utilities/dart_uri.dart
- dwds/lib/src/utilities/sdk_configuration.dart
- dwds/pubspec.yaml
- dwds/test/dart_uri_test.dart
- dwds/test/debug_extension_test.dart
- dwds/test/expression_compiler_service_test.dart
- dwds/test/fixtures/context.dart
- dwds/test/sdk_configuration_test.dart
- Add SdkConfigurationInterface and a default implementation.
- Pass SdkConfiguration to dwds and ExpressionCompilerService.
- Add tests.
Note: this change will enable us to add debugging for scenarios where SDK files are generated and copied during the build.
> Support lazily created SDK configurations.

- dwds/test/events_test.dart
- dwds/test/fixtures/server.dart
Retry starting HttpServer in tests a few times to recover from a rare race condition.
Closes: https://github.com/dart-lang/webdev/issues/1514
> Fix flakes in tests due to race condition on finding a free port

- dwds/CHANGELOG.md
- dwds/lib/src/handlers/dev_handler.dart
- dwds/test/debug_extension_test.dart
- dwds/test/devtools_test.dart
This query parameter is used in Dart DevTools to track how how it was launched. This should give us metrics on the number of users launching Dart DevTools from the Dart Debug Extension.
> Adds an IDE query parameter to the Dart DevTools URL

- dwds/debug_extension/CHANGELOG.md
- dwds/debug_extension/pubspec.yaml
- dwds/debug_extension/web/background.dart
- dwds/debug_extension/web/background.js
- dwds/debug_extension/web/manifest.json
- dwds/debug_extension/web/panel.css
- dwds/debug_extension/web/panel.html
- dwds/debug_extension/web/panel.js
* Adds support for using the embedded Dart DevTools in Chrome DevTools in environments where the Dart app context (and therefore Dart app ID) is in a nested IFRAME 
* Also renames `_handleDevToolsOpen` to `_handleMessageFromPanelScript` for clarity.
* Makes the "Start debugging" button disabled while the panel is initially loading, and after a user clicks it and the embedded Dart DevTools is loading.
> Support embedded debugging experience in environments with nested Dart app ID

- dwds/CHANGELOG.md
- dwds/lib/dwds.dart
- dwds/lib/src/dwds_vm_client.dart
- dwds/lib/src/events.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/services/app_debug_services.dart
- dwds/test/events_test.dart
- Store dwdsStats on appServices for an app to make sure we are
updating an reporting the same stats for an app. Previously,
if the app services already existed, we would use incorrect
object to report the stats, causing incorrect times and missing
reports.
- Set the times on dwdsStats when debug request arrives to make
sure times are recorded only from the time when the user starts
debugging.
- Process `pageReady` events from any DevTools page, as DevTools
does not always show the debugger page first.
- Enabled previously skipped tests.
Closes:https://github.com/dart-lang/webdev/issues/1517
> Fix issues in DevTools load time reporting

- dwds/debug_extension/CHANGELOG.md
- dwds/debug_extension/pubspec.yaml
- dwds/debug_extension/web/debugger_panel.html
- dwds/debug_extension/web/devtools.js
- dwds/debug_extension/web/inspector_panel.html
- dwds/debug_extension/web/manifest.json
- dwds/debug_extension/web/panel.js
This is still just restricted to internal apps at the moment.
> Detect Flutter Web apps and embed inspector page for them 

- dwds/CHANGELOG.md
- dwds/debug_extension/pubspec.yaml
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/services/expression_evaluator.dart
- dwds/test/build_daemon_evaluate_test.dart
- dwds/test/frontend_server_evaluate_test.dart
- fixtures/_test/lib/deferred_library.dart
- fixtures/_testPackage/web/main.dart
- fixtures/_testPackageSound/web/main.dart
- fixtures/_testSound/lib/deferred_library.dart
- webdev/test/chrome_test.dart
Change error message on expression evaluation using deferred libraries from `NetworkError` to `LoadModuleError` with more readable details about the module name and path.
Closes: https://github.com/dart-lang/webdev/issues/1541
> Fix error message on expression evaluation  for module load error

- dwds/pubspec.yaml
- frontend_server_client/pubspec.yaml
- webdev/pubspec.yaml
- populate the pubspec `repository` fields for the webdev packages
> populate the pubspec repository fields

- dwds/debug_extension/CHANGELOG.md
- dwds/debug_extension/pubspec.yaml
- dwds/debug_extension/web/background.dart
- dwds/debug_extension/web/background.js
- dwds/debug_extension/web/manifest.json
Previously when a debug session was lost, we were simply closing the socket. This meant that the Dart DevTools panel wasn't aware of the disconnection. Now we notify the panel that the session has been lost , so that it will show the "Start debugging" / "Start inspecting" screen once more. 
Also did a bit of clean up to make things clearer.
> Dart Debug Extension gracefully handles disconnection 

- dwds/CHANGELOG.md
- dwds/lib/src/utilities/sdk_configuration.dart
Split SDK configuration validation into components to allow for scenarios that do not use all the components, for example,
flutter tools, which does not use the expression compiler service.
Helps: https://github.com/flutter/flutter/issues/101639
> Split SDK configuration validation into components

- dwds/CHANGELOG.md
- dwds/debug_extension/CHANGELOG.md
- dwds/debug_extension/web/background.dart
- dwds/debug_extension/web/background.js
- dwds/lib/src/servers/extension_debugger.dart
Seems to resolve b/231336802
We can get in a weird state with the Dart Debug Extension. If a user starts debugging, and detaches the debugger by closing the banner added by Chrome, we close the SSE socket client.
However, from DWDS, there can be a substantial delay before the SSE socket stream receives the "done" event, and therefore closes the actual SSE connection ([code](https://github.com/dart-lang/webdev/blob/master/dwds/lib/src/servers/extension_debugger.dart#L105)). 
If this done event is received AFTER the user has already starting debugging their application again, then we close their debug session while they are debugging. 
It seems like this is resolved if we send an event to notify DWDS that the debugger has been detached, and call `close` in response to that event. I'm not …
> Send an event notifying DWDS when the debugger is detached 

- dwds/debug_extension/CHANGELOG.md
- dwds/debug_extension/CONTRIBUTING.md
- dwds/debug_extension/web/background.dart
- dwds/debug_extension/web/background.js
Fixes https://github.com/dart-lang/webdev/issues/1506
Explicitly casts our tab list (which the compiler thought was `List<dynamic>`) to `List<Tab>`.
This is a known limitation of the Dart JS package (https://github.com/dart-lang/sdk/tree/master/pkg/js#list-instances-coming-from-javascript-will-always-be-listdynamic).
> Fix DDC compilation error for the Dart Debug Extension

- .gitattributes
Tag the github actions workflow and `tool/ci.sh` as `linguist-generated`
so that diff is collapsed by default. Changes in these files are not
easy or necessary to review, the changes in `mono_pkg.yml` files are the
important ones.
> Mark mono_repo outputs as generated

- frontend_server_client/CHANGELOG.md
- frontend_server_client/README.md
- frontend_server_client/pubspec.yaml
- remove a todo from the frontend_server_client readme
- rev the pubspec version (some changes had landed here since the last publish)
- add some std markdown badges to the readme
> remove a todo from the frontend_server_client readme

- frontend_server_client/CHANGELOG.md
- frontend_server_client/example/vm_client.dart
- frontend_server_client/example/web_client.dart
- frontend_server_client/lib/src/dartdevc_frontend_server_client.dart
- frontend_server_client/lib/src/frontend_server_client.dart
- frontend_server_client/pubspec.yaml
- frontend_server_client/test/frontend_sever_client_test.dart
Also fixes https://github.com/dart-lang/webdev/issues/1637.
This is a breaking API change, which I could revert if desired, but this allows us to get compiler output even if there is no output dill file.
> update frontend server compile api to always return a result, but have a nullable output dill

- dwds/lib/src/debugging/execution_context.dart
- dwds/lib/src/debugging/inspector.dart
Work towards https://github.com/flutter/flutter/issues/95916
We now catch any errors getting the `executionContext.id` in DWDS and add `severe` logs in that case. (Without catching the error it crashes `flutter_tools`). 
I also doubled the timeout for finding the next execution context, in case we weren't finding the execution context due to timeouts. Added some logging for when that occurs.
> Prevent `flutter_tools` crash when the Dart execution context cannot be found

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/location.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/loaders/frontend_server_require.dart
- dwds/lib/src/loaders/require.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/services/debug_service.dart
- dwds/lib/src/utilities/dart_uri.dart
- dwds/test/build_daemon_callstack_test.dart
- dwds/test/build_daemon_evaluate_test.dart
- dwds/test/dart_uri_test.dart
- dwds/test/evaluate_common.dart
- dwds/test/expression_compiler_service_test.dart
- dwds/test/fixtures/context.dart
- dwds/test/frontend_server_callstack_test.dart
- dwds/test/frontend_server_evaluate_test.dart
- fixtures/_testPackage/web/base_index.html
- fixtures/_testPackageSound/web/base_index.html
- frontend_server_common/lib/src/asset_server.dart
- frontend_server_common/lib/src/devfs.dart
- frontend_server_common/lib/src/frontend_server_client.dart
- frontend_server_common/lib/src/resident_runner.dart
- Update `frontend_server_common` infrastructure to behave similar to flutter tools
- Serve the app from a base directory if specified in index.html
- Add test code for index.html with base
- Pass the root instead of the tab url in several places, simplify `dart_uri.dart` to match
- Fix issues discovered in tests
Closes: https://github.com/dart-lang/webdev/issues/1657
> Run frontend server tests and fix failures

- dwds/lib/src/loaders/legacy.dart
Resolves the following error when a resource is not found:
```
Invalid argument(s): Response body "favicon.ico" must be a String or a Stream.
package:shelf/src/response.dart 212:8               new Response.notFound
package:dwds/src/loaders/legacy.dart 75:48          LegacyStrategy.handler.<fn>
package:dwds/src/handlers/injector.dart 126:61      DwdsInjector.middleware.<fn>.<fn>
```
> Stringify URL when resource is not found

- dwds/lib/src/debugging/location.dart
- dwds/lib/src/debugging/modules.dart
- dwds/test/debugger_test.dart
- dwds/test/location_test.dart
Migrate modules and locations to null safety
> Migrate modules and locations to null safety

- webdev/CHANGELOG.md
- webdev/lib/src/version.dart
- webdev/pubspec.yaml
Work towards https://github.com/dart-lang/webdev/issues/1632
In https://github.com/dart-lang/webdev/pull/1633, we updated the `vm_service` version required by DWDS. Before releasing DWDS, we should release Webdev with a pin on the older version of DWDS. Otherwise, the moment we release DWDS, Webdev users will get the following error:
```
Because every version of dwds at {{new version}} depends on vm_service ^9.0.0 and webdev depends on vm_service ^8.3.0, dwds at {{new version}} is forbidden.
So, because webdev depends on dwds at {{new version}, version solving failed.
```
> Prep Webdev 2.7.10 release 

- dwds/lib/src/handlers/dev_handler.dart
Fixes a bug introduced by https://github.com/dart-lang/webdev/pull/1658
That change modified a parameter in `DebugService.start` from the full URL to only the root. We were correctly passing this when the debug service was started normally, but not when it was started from the Dart Debug Extension.
> Fix file serving bug when using the Dart Debug Extension

- dwds/debug_extension/CHANGELOG.md
- dwds/debug_extension/pubspec.yaml
- dwds/debug_extension/web/manifest.json
Version was bumped up one to many (current version is `1.29`, next release is `1.30`).
> Prepare Dart Debug Extension for release

- dwds/lib/src/services/expression_compiler_service.dart
- dwds/test/expression_compiler_service_test.dart
Add type check for responses from expression compiler worker
Related: https://github.com/dart-lang/webdev/pull/1693 (see CR comments)
> Add type check for responses from expression compiler worker

- .github/workflows/dart.yml
- frontend_server_client/example/app/index.html
- frontend_server_client/example/vm_client.dart
- frontend_server_client/example/web_client.dart
- frontend_server_client/mono_pkg.yaml
- frontend_server_client/pubspec.yaml
- frontend_server_client/test/example/vm_client_test.dart
- frontend_server_client/test/example/web_client_test.dart
- tool/ci.sh
Fixes https://github.com/dart-lang/webdev/issues/1546
There are definitely some hacky-ish things here in terms of the routing, but it works and that isn't the focus of the example.
> fix the example frontend server web app

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/services/chrome_proxy_service.dart
Make `ChromeProxyService.getStack` wait for the debugger to perform initial resume operation.
This avoids race conditions on isolate start if `getStack` is called too soon.  
See failures in https://github.com/dart-lang/webdev/pull/1701 tests on windows for examples:
> Fix getStack race conditions on isolate start

- dwds/lib/src/debugging/libraries.dart
- dwds/test/chrome_proxy_service_test.dart
- dwds/test/fixtures/context.dart
I did not refactor away the null-assert !s added by the Dart migration tool. Because this is a test, the null-assert !s should catch any regressions if something we expect to be non-null returns null.
> Migrate `chrome_proxy_service_test` to null-safety

- dwds/test/frontend_server_breakpoint_test.dart
- dwds/test/frontend_server_callstack_test.dart
- dwds/test/reload_test.dart
- dwds/test/restore_breakpoints_test.dart
- dwds/test/run_request_test.dart
- dwds/test/variable_scope_test.dart
Migrates the following tests to null-safety:
```
test/run_request_test.dart
test/frontend_server_callstack_test.dart
test/restore_breakpoints_test.dart
test/variable_scope_test.dart
test/frontend_server_breakpoint_test.dart
test/reload_test.dart
```
> Migrate a handful of tests to null-safety

- frontend_server_common/CHANGELOG.md
- frontend_server_common/lib/src/frontend_server_client.dart
- frontend_server_common/pubspec.yaml
This flag is true by default in the frontend server currently, so no change in behavior is expected.
Towards: https://github.com/dart-lang/webdev/issues/1692
> Remove passing --debugger-module-names to frontend server in tests

- dwds/debug_extension/tool/build_extension.sh
- dwds/test/fixtures/context.dart
Follow-up to https://github.com/dart-lang/webdev/pull/1717
Pass in working directory to `Process.run` instead of switching directories to build.
> Pass working directory to `Process.run` when building debug extension in tests

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/utilities/dart_uri.dart
- dwds/test/dart_uri_test.dart
- fixtures/_testCircular1/lib/library1.dart
- fixtures/_testCircular1Sound/lib/library1.dart
- fixtures/_testCircular2/lib/library2.dart
- fixtures/_testCircular2Sound/lib/library2.dart
Latest changes to `DartUri` do not allow schemes such as `google3:`, which breaks automatic rolls into google3.
- Handle `google3:` uris in `DartUri`
- Add tests
> Update DartUri to handle more urls

- dwds/test/chrome_proxy_service_test.dart
- dwds/test/devtools_test.dart
Opened an issue to investigate the flake: https://github.com/dart-lang/webdev/issues/1749
> Disable flaky tests on windows

- webdev/CHANGELOG.md
- webdev/lib/src/logging.dart
- webdev/lib/src/pubspec.dart
- webdev/lib/src/util.dart
- webdev/lib/src/version.dart
- webdev/pubspec.yaml
Work towards https://github.com/dart-lang/webdev/issues/1640
> Start migration of WebDev to null-safety

- frontend_server_client/CHANGELOG.md
- frontend_server_client/lib/src/frontend_server_client.dart
- frontend_server_client/pubspec.yaml
https://dart-review.googlesource.com/c/sdk/+/231334 introduced passing additional sources to `gen_kernel`.
This PR exposes this option in the `FrontendServerClient` so that it can be invoked from pub/dartdev which uses this API.
> Support `--source` in `FrontendServerClient`

- webdev/test/build/min_sdk_test.dart
- webdev/test/chrome_test.dart
- webdev/test/configuration_test.dart
- webdev/test/daemon/app_domain_test.dart
- webdev/test/daemon/daemon_domain_test.dart
- webdev/test/daemon/launch_app_test.dart
- webdev/test/daemon/utils.dart
- webdev/test/e2e_test.dart
- webdev/test/integration_test.dart
- webdev/test/readme_test.dart
- webdev/test/test_utils.dart
- webdev/test/utils_test.dart
> Migrate webdev tests to null safety

- webdev/bin/webdev.dart
- webdev/lib/src/command/daemon_command.dart
- webdev/lib/src/command/serve_command.dart
- webdev/lib/src/daemon/app_domain.dart
- webdev/lib/src/serve/dev_workflow.dart
- webdev/lib/src/webdev_command_runner.dart
Closes #1640 
Migrate the last unmigrated libraries from `lib/` as well as the binary.
> Migrate remaining webdev libraries

- dwds/CHANGELOG.md
- dwds/pubspec.yaml
- frontend_server_common/pubspec.yaml
`package:file` needs to be updated to the latest version before releasing DWDS and webdev due to https://github.com/dart-lang/sdk/issues/49647
> Update `package:file` to latest version

- dwds/web/client.dart
This has no effect because unsafe_html is unignorable.
> Remove // ignore: unsafe_html.

- dwds/analysis_options.yaml
- dwds/debug_extension/tool/update_dev_files.dart
- dwds/debug_extension_mv3/tool/update_dev_files.dart
- dwds/lib/src/services/batched_expression_evaluator.dart
Update analysis options in dwds
- exclude generated build files from analysis
- add `unawaited futures` linter
> Update analysis options in dwds

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/debugging/instance.dart
- dwds/lib/src/services/expression_evaluator.dart
- dwds/test/evaluate_common.dart
- fixtures/_testPackage/web/main.dart
- fixtures/_testPackageSound/web/main.dart
If `dwds` cannot find class metadata for a type mentioned in the `instanceRef`, `vm_service.getObject` fails with a null cast error when trying to get the objects's properties (when populating bound variables).
Make sure we check for null values when we populate the bound variables.
Closes: https://github.com/dart-lang/webdev/issues/1783
> Fix null cast error on expression evaluation with missing class metadata

- webdev/CHANGELOG.md
- webdev/lib/src/version.dart
- webdev/pubspec.yaml
Use local dwds in webdev to make sure we run e2e tests against current dwds version.
> Use local dwds in webdev

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/inspector.dart
- dwds/test/inspector_test.dart
Fixes https://github.com/dart-lang/webdev/issues/1781
See https://github.com/flutter/flutter/issues/114727#issuecomment-1307949198 for details
> Log entire exception message instead of first line

- dwds/CHANGELOG.md
- dwds/lib/src/services/expression_compiler_service.dart
- webdev/CHANGELOG.md
- webdev/lib/src/command/configuration.dart
- webdev/lib/src/command/shared.dart
- webdev/lib/src/serve/webdev_server.dart
Add `--enable-experiment` flag to webdev commands and pass it to the expression compiler worker.
Closes: https://github.com/dart-lang/webdev/issues/1790
Replaces: https://github.com/dart-lang/webdev/pull/1792
> Add --enable-experiment flag to webdev commands

- frontend_server_client/CHANGELOG.md
- frontend_server_client/lib/src/frontend_server_client.dart
- frontend_server_client/pubspec.yaml
https://dart-review.googlesource.com/c/sdk/+/264842 introduces passing `--native-assets` to `gen_kernel`.
This PR exposes this option in the `FrontendServerClient` so that it can be invoked from pub/dartdev which uses this API.
> Support `--native-assets` in `FrontendServerClient`

- dwds/debug_extension_mv3/web/background.dart
- dwds/debug_extension_mv3/web/detector.dart
- dwds/debug_extension_mv3/web/lifeline_connection.dart
- dwds/debug_extension_mv3/web/lifeline_ports.dart
- dwds/debug_extension_mv3/web/logger.dart
- dwds/debug_extension_mv3/web/messaging.dart
- dwds/debug_extension_mv3/web/storage.dart
- dwds/debug_extension_mv3/web/web_api.dart
Instead of each file separately setting their logger, have a single `logger` that can be used everywhere.
> Add a `logger` to the MV3 debug extension

- fixtures/_test/pubspec.yaml
- fixtures/_testCircular1/pubspec.yaml
- fixtures/_testCircular1Sound/pubspec.yaml
- fixtures/_testCircular2/pubspec.yaml
- fixtures/_testCircular2Sound/pubspec.yaml
- fixtures/_testCircular2Sound/web/main.dart
- fixtures/_testPackage/pubspec.yaml
- fixtures/_testPackageSound/pubspec.yaml
- fixtures/_testSound/pubspec.yaml
- fixtures/_webdevSmoke/pubspec.yaml
Also runs the migration tool on `testCircular1Sound` and `testCircular2Sound` because it was complaining those weren't migrated.
> Updates the `fixture` package `pubspecs` so it is clear what shouldn't be migrated to null-safety

- dwds/lib/dart_web_debug_service.dart
- dwds/lib/src/injected/client.js
- dwds/test/handlers/injector_test.dart
- dwds/test/puppeteer/extension_test.dart
- dwds/web/client.dart
The global variable was incorrectly called `isInternalDartBuild` not `isInternalBuild`
> Fix global variable `isInternalBuild` in injected client

- dwds/debug_extension_mv3/web/debug_session.dart
Small refactor of the `DebugSession`:
- it both listens to and sends events to the SSE/WS connection 
- it can send any event, not just `ExtensionEvent`s
> `DebugSession` listens to events instead of just sending events

- dwds/CHANGELOG.md
- dwds/lib/dart_web_debug_service.dart
- dwds/lib/data/debug_info.dart
- dwds/lib/data/debug_info.g.dart
- dwds/lib/src/handlers/injector.dart
- dwds/lib/src/injected/client.js
- dwds/test/handlers/injector_test.dart
- dwds/test/puppeteer/extension_test.dart
- dwds/web/client.dart
This will be used to determine which panels to load in the Dart Debug Extension.
> Injected client adds `isFlutterApp` to global window object

- dwds/debug_extension_mv3/web/storage.dart
- dwds/test/puppeteer/extension_test.dart
* `DebugInfo` for an app is saved in `session` storage, so it does not persist across sessions
* `DevToolsOpener` setting is saved in `local` storage, so it persists across sessions
See https://developer.chrome.com/docs/extensions/reference/storage/#type-StorageArea for details on `session` vs `local` storage
> Can save storage objects in both `session` and `local` storage

- dwds/pubspec.yaml
- dwds/test/puppeteer/extension_test.dart
- dwds/test/puppeteer/lifeline_test.dart
- dwds/test/puppeteer/test_utils.dart
The `Worker` type is now visible in `package:puppeteer` (https://github.com/xvrh/puppeteer-dart/issues/198)
This PR refactors to the Puppeteer tests to remove some code duplication now that we have access to the `Worker` type.
> Refactor puppeteer tests to use `Worker` type

- dwds/debug_extension_mv3/web/background.dart
- dwds/debug_extension_mv3/web/chrome_api.dart
- dwds/debug_extension_mv3/web/debug_session.dart
- dwds/debug_extension_mv3/web/manifest.json
- dwds/debug_extension_mv3/web/storage.dart
- dwds/test/puppeteer/extension_test.dart
- dwds/test/puppeteer/js_functions.js
Navigating away from the Dart app or closing the Dart app while it is being debugged detaches the debugger and closes Dart DevTools.
> Gracefully handle debugger disconnect events

- dwds/test/puppeteer/extension_test.dart
Fixes the following error when running the extension test locally:
```
Evaluation failed: TypeError: Cannot read properties of undefined (reading 'windowId')
at __puppeteer_evaluation_script__:3:18
package:puppeteer/src/page/execution_context.dart 169:11  ExecutionContext._evaluateInternal
===== asynchronous gap ===========================
package:puppeteer/src/page/execution_context.dart 76:20   ExecutionContext.evaluate
===== asynchronous gap ===========================
test/puppeteer/extension_test.dart 239:11                 _getWindowId
===== asynchronous gap ===========================
test/puppeteer/extension_test.dart 167:30                 main.<fn>.<fn>.<fn>
```
> Small fix to the extension test

- dwds/test/build_daemon_breakpoint_test.dart
- dwds/test/build_daemon_callstack_test.dart
- dwds/test/build_daemon_circular_evaluate_test.dart
- dwds/test/build_daemon_evaluate_test.dart
- dwds/test/chrome_proxy_service_test.dart
- dwds/test/dart_uri_file_uri_test.dart
- dwds/test/debug_extension_test.dart
- dwds/test/evaluate_circular_common.dart
- dwds/test/evaluate_common.dart
- dwds/test/events_test.dart
- dwds/test/fixtures/context.dart
- dwds/test/frontend_server_breakpoint_test.dart
- dwds/test/frontend_server_callstack_test.dart
- dwds/test/frontend_server_circular_evaluate_test.dart
- dwds/test/frontend_server_evaluate_test.dart
- dwds/test/package_uri_mapper_test.dart
- dwds/test/readers/frontend_server_asset_reader_test.dart
- dwds/test/readers/proxy_server_asset_reader_test.dart
- dwds/test/reload_test.dart
- dwds/test/utils/version_compatibility.dart
- fixtures/_testCircular1Sound/pubspec.yaml
- frontend_server_common/lib/src/devfs.dart
- frontend_server_common/pubspec.yaml
Work towards https://github.com/dart-lang/webdev/issues/1818
This addresses the first task, and is primarily to unblock the broken CI tests at head. It fixes what is fairly non-trivial to fix, and disables tests that will take more work.
> Update tests that are incompatible with `3.0.0`

- dwds/test/package_uri_mapper_test.dart
Fixes https://github.com/dart-lang/webdev/issues/1834
Adds running `dart pub upgrade` to the `setUpAll` step to ensure that `.dart_tool/package_config.json` exists.
> Fix `package_uri_file_mapper_test` on Linux

- dwds/test/dart_uri_file_uri_test.dart
- dwds/test/fixtures/context.dart
Work towards https://github.com/dart-lang/webdev/issues/1842
Addresses 2) of the above:
> We are treating the default TestContext directory as a relative directory from the current path. However, we are not doing the same for a directory that is passed in as a parameter (we assume that it is an absolute directory, although none of them are actually absolute. See for example [dart_uri_file_uri_test](https://github.com/dart-lang/webdev/blob/db5ed71d53def2d3642da247cf80dd393ceef2b9/dwds/test/dart_uri_file_uri_test.dart#L16))
This PR treats all directory / file paths in `TestContext` as relative paths.
> File paths in `TestContext` are relative, not absolute

- dwds/test/build/ensure_version_test.dart
- dwds/test/debug_extension_test.dart
- dwds/test/devtools_test.dart
- dwds/test/fixtures/context.dart
- dwds/test/package_uri_mapper_test.dart
**Work towards https://github.com/dart-lang/webdev/issues/1846 (flakiness caused by test timeouts):**
* Our `devtools_test` keeps timing out during CI testing. It already has a timeout limit of 5 minutes, so instead of increasing the timeout, this PR skips it with follow up work to schedule it on a cron job. 
* The `debug_extension_test` also keeps timing out, this PR increases the timeout to 2 minutes.
**Work towards https://github.com/dart-lang/webdev/issues/1842 (flakiness cause by file path issues):**
* Instead of assuming the current directory is the `dwds` directory in `TestContext`, determine the `dwds` directory and use that to create the various test directory paths.
> Fix flaky CI tests

- .github/workflows/dart.yml
- dwds/mono_pkg.yaml
- dwds/test/dart_uri_file_uri_test.dart
- dwds/test/fixtures/context.dart
- dwds/test/fixtures/utilities.dart
- dwds/test/package_uri_mapper_test.dart
- dwds/test/readers/frontend_server_asset_reader_test.dart
- tool/ci.sh
Addresses the task "DWDS tests should be sharded into groups (currently they take much longer than the other CI actions)" by breaking the DWDS tests into 4 groups, all of which are run on Linux / Windows, and with the stable and dev Dart SDKs:
- extension tests only
- test shard 1
- test shard 2
- test shard 3 
- Updates the logic for how we are computing the DWDS path, and moves it (and a helper function to create an absolute path given a relative path to DWDS) to the shared test `utilities` file, so that they can be used by tests that aren't using `TestContext`.
> Shard DWDS tests and fix CI test flakiness

- dwds/test/fixtures/context.dart
- dwds/test/inspector_test.dart
- dwds/test/instance_test.dart
- dwds/test/reload_test.dart
- dwds/test/variable_scope_test.dart
Work towards https://github.com/dart-lang/webdev/issues/1845
We have a few tests across DWDS that are serving an `index.html` and a `main.dart` file from different directories. This is confusing and was (I'm guessing) unintentional. This changes those tests so the files are being served from the same directory.
> Tests should serve`main.dart` and `index.html` from the same directory

- dwds/debug_extension_mv3/web/debug_session.dart
- dwds/pubspec.yaml
- dwds/web/client.dart
The ability to provide an optional debug key was added in https://github.com/dart-lang/sse/pull/67
This debug key identifies the SSE connection and can be used to debug SSE connection issues.
> Set a debug key for the injected client and Dart Debug Extension SSE clients

- analysis_options.yaml
The old strong-mode options are deprecated (https://github.com/dart-lang/sdk/commit/166c54b4d94b4fe12849339bfc11e5694d4fe892, https://github.com/dart-lang/sdk/issues/50679) in favor of new strict modes (https://github.com/dart-lang/sdk/issues/33749).
> Replace deprecated implicit-casts option with strict-casts option

- analysis_options.yaml
- dwds/CHANGELOG.md
- dwds/lib/src/dwds_vm_client.dart
- dwds/lib/src/events.dart
Fix crash on processing devtools event.
Closes: https://github.com/dart-lang/webdev/issues/1874
> Fix crash on processing devtools event

- dwds/test/devtools_test.dart
- dwds/test/fixtures/context.dart
- dwds/test/reload_test.dart
The `reload_tests` were disabled because they were timing out. This fixes the timeouts by making sure that the file that is edited (to trigger a reload), is reset after each test case.
> Re-enable `reload_tests`

- dwds/CHANGELOG.md
- dwds/test/evaluate_common.dart
- dwds/test/fixtures/context.dart
- fixtures/_test/pubspec.yaml
- fixtures/_testCircular1/pubspec.yaml
- fixtures/_testCircular2/pubspec.yaml
- fixtures/_testPackage/pubspec.yaml
- fixtures/_webdevSmoke/pubspec.yaml
- webdev/CHANGELOG.md
- webdev/lib/src/command/shared.dart
- webdev/test/e2e_test.dart
Prepare for dart 3.0 alpha breaking changes:
- Use special branch of build_web_compilers for weak null safety tests.
- Remove passing unneeded `--(no)-sound-null-safety` to build daemon and build_web_compilers.
- Build daemon detects null safety mode  automatically from the pubspec and dart annotations of the project.
- Add tests to verify that every test suite runs in the intended null safety mode.
Towards: https://github.com/dart-lang/webdev/issues/1878
> Prepare for dart 3.0 alpha breaking changes

- dwds/debug_extension_mv3/web/storage.dart
This fixes an error that was showing up for the MV3 debug extension. The error wasn't affecting any functionality, just logging to the console.
> [MV3] Check if storage object exists before trying to read properties

- dwds/debug_extension_mv3/web/debug_session.dart
Fixes the following error on detaching the debugger if Dart DevTools wasn't opened in a separate tab (eg, if it is open in Chrome DevTools or if we are debugging from an IDE). The field should be nullable and non-final instead of late and final, since it only gets set if we have an open DevTools tab.
```
background.dart.js:4574 Uncaught LateInitializationError: Field 'devToolsTabId' has not been initialized.
at Object.wrapException (background.dart.js:950:17)
at Object.throwExpression (background.dart.js:964:15)
at Object.throwLateFieldNI (background.dart.js:1750:16)
at background.dart.js:8480:29
at _wrapJsFunctionForAsync_closure.$protected (background.dart.js:3362:15)
at _wrapJsFunctionForAsync_closure.call$2 (background.dart.js:11658:12)
at Object._asyncStartSync …
```
> [MV3] Fix late initialization error on debugger detach

- dwds/test/devtools_test.dart
Work towards https://github.com/dart-lang/webdev/issues/1888
> Re-enable most test cases in `devtools_test`

- fixtures/_test/example/append_body/main.dart
- fixtures/_test/example/hello_world/main.dart
- fixtures/_test/example/hello_world/part.dart
- fixtures/_test/lib/deferred_library.dart
- fixtures/_test/lib/library.dart
- fixtures/_testCircular1/lib/library1.dart
- fixtures/_testCircular2/lib/library2.dart
- fixtures/_testCircular2/web/main.dart
- fixtures/_testPackage/lib/src/test_part.dart
- fixtures/_testPackage/lib/test_library.dart
- fixtures/_testPackage/web/main.dart
- fixtures/_webdevSmoke/web/main.dart
- fixtures/_webdevSmoke/web/scopes_main.dart
New analyzer error was recently added: https://github.com/dart-lang/sdk/issues/50694
We should ignore it for our legacy non null-safe fixtures that we are using to test backwards compatibility.
> Ignore `illegal_language_version_override` for non null-safe fixtures

- dwds/test/devtools_test.dart
Follow-up to https://github.com/dart-lang/webdev/pull/1881
One of the recently re-enabled test cases failed for the last 2/3 CI runs on Windows (see https://github.com/dart-lang/webdev/actions/runs/3914484820/jobs/6691618089) This PR disables that test on Windows for now.
> Skip flaky `devtools_test` case on Windows

- dwds/CHANGELOG.md
- dwds/debug_extension/pubspec.yaml
- dwds/debug_extension_mv3/pubspec.yaml
- dwds/pubspec.yaml
- example/pubspec.yaml
- fixtures/_test/pubspec.yaml
- fixtures/_testCircular1/pubspec.yaml
- fixtures/_testCircular1Sound/pubspec.yaml
- fixtures/_testCircular2/pubspec.yaml
- fixtures/_testCircular2Sound/pubspec.yaml
- fixtures/_testPackage/pubspec.yaml
- fixtures/_testPackageSound/pubspec.yaml
- fixtures/_testSound/pubspec.yaml
- fixtures/_webdevSmoke/pubspec.yaml
- fixtures/_webdevSoundSmoke/pubspec.yaml
- frontend_server_client/CHANGELOG.md
- frontend_server_client/pubspec.yaml
- frontend_server_client/test/frontend_sever_client_test.dart
- frontend_server_common/pubspec.yaml
- webdev/CHANGELOG.md
- webdev/pubspec.yaml
Update max dart SDK constraint to <4.0.0.
Towards: https://github.com/dart-lang/webdev/issues/1878
> Allow dart SDK <4.0.0

- dwds/CHANGELOG.md
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/pubspec.yaml
- webdev/CHANGELOG.md
- webdev/pubspec.yaml
Update vm_service to version 10.0.0
Towards:  https://github.com/dart-lang/webdev/issues/1912
> Update vm_service to version 10.0.0

- dwds/CHANGELOG.md
- dwds/lib/src/services/expression_compiler_service.dart
- fixtures/_webdevSoundSmoke/web/scopes.html
- fixtures/_webdevSoundSmoke/web/scopes_main.dart
- webdev/CHANGELOG.md
- webdev/test/daemon/utils.dart
Fixed CI breaks in main channel after the unsound summaries were deleted from the SDK.
See: https://github.com/dart-lang/webdev/pull/1916
> Validate only needed summaries in expression_compiler_service

- .github/workflows/dart.yml
- dwds/mono_pkg.yaml
- dwds/pubspec.yaml
- tool/ci.sh
Work towards https://github.com/flutter/flutter/issues/119084
Removes the change to the SDK constraint in https://github.com/dart-lang/webdev/pull/1927
This was necessary for 16.0.3, but shouldn't be necessary for 16.0.2+1
FYI @christopherfujino
> Revert SDK constraint for DWDS

- dwds/CHANGELOG.md
- dwds/lib/src/services/batched_expression_evaluator.dart
- dwds/test/evaluate_common.dart
Work towards https://github.com/flutter/flutter/issues/119084
- Handle the case where `list.ObjectId` is `null` in `batched_expression_evaluator.dart` (copies the fix on head, which is https://github.com/dart-lang/webdev/blame/master/dwds/lib/src/services/batched_expression_evaluator.dart#L132-L137)
- Adds a test case for the error handling
FYI @christopherfujino
> Handle case where `list.objectId` is `null` in `batched_expression_evaluator.dart`

- dwds/test/evaluate_common.dart
Related to https://github.com/flutter/flutter/issues/119084
Copies the test case from https://github.com/dart-lang/webdev/pull/1930 over to our main branch to catch any regressions.
> Patch in the test case from the DWDS `16.0.2+1` release

- README.md
- example/pubspec.yaml
- update the readme to use a markdown table
This aligns with some of our other monorepos (and will be easier to maintain - it's the output of `mono_repo readme`).
> update the readme to use a markdown table

- dwds/debug_extension_mv3/web/debug_session.dart
- dwds/debug_extension_mv3/web/panel.dart
- dwds/debug_extension_mv3/web/utils.dart
- dwds/lib/data/devtools_request.dart
- dwds/lib/data/devtools_request.g.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/injected/client.js
- dwds/test/puppeteer/extension_test.dart
In the MV2 extension, DWDS could tell whether a `DevToolsRequest` was for embedding in Chrome DevTools (`uriOnly=true`). It would then set the `ide` query parameter to `ChromeDevTools` if embedded, or `DebugExtension` if not. See https://github.com/dart-lang/webdev/pull/1522
In the MV3 extension, all `DevToolsRequests` have `uriOnly=true`. Therefore, we handle adding the `ide` query parameter from the extension and not from DWDS.
> [MV3 Debug Extension] Extension sets the `ide` query parameter for the DevTools URI

- dwds/debug_extension_mv3/web/static_assets/inspector_panel.html
The `panel.dart` expects us to have a `landingPage` and `loadingSpinner`
> [MV3 Debug Extension] Add missing elements and IDs to inspector panel

- dwds/debug_extension_mv3/web/background.dart
- dwds/debug_extension_mv3/web/debug_session.dart
- dwds/debug_extension_mv3/web/lifeline_ports.dart
I hadn't run the `lifeline_test` in a while, so didn't realize I had regressed the keep-alive connection. This PR updates the logic so the test works again.
> [MV3 Debug Extension] Fix lifeline connection logic

- dwds/debug_extension_mv3/web/background.dart
- dwds/debug_extension_mv3/web/chrome_api.dart
- dwds/debug_extension_mv3/web/debug_session.dart
- dwds/debug_extension_mv3/web/lifeline_ports.dart
- dwds/debug_extension_mv3/web/utils.dart
Work towards https://github.com/dart-lang/webdev/issues/1950
> [MV3 Debug Extension] Update Chrome APIs to be backwards compatible with MV2

- dwds/debug_extension_mv3/web/chrome_api.dart
- dwds/debug_extension_mv3/web/utils.dart
- dwds/test/puppeteer/extension_test.dart
- dwds/test/puppeteer/test_utils.dart
Uses `printOnFailure` to log the most recent messages logged to the service worker or chrome devtools console for debugging purposes.
Also fixes some test failures.
> [MV3 Debug Extension] Print `console` messages on test failure

- dwds/debug_extension_mv3/web/background.dart
- dwds/debug_extension_mv3/web/devtools.dart
- dwds/debug_extension_mv3/web/logger.dart
- dwds/debug_extension_mv3/web/utils.dart
* Turns `isDevMode` into a `getter`
* Make sure it caches the value before returning
> [MV3 Debug Extension] Fix `isDevMode` getter

- dwds/debug_extension_mv3/web/panel.dart
Makes the variables in `panel.dart` private.
> [MV3 Debug Extension] Variables in `panel.dart` should be private

- dwds/CHANGELOG.md
- dwds/debug_extension_mv3/web/debug_session.dart
- dwds/lib/dart_web_debug_service.dart
- dwds/lib/src/handlers/injector.dart
- dwds/test/fixtures/server.dart
- dwds/test/handlers/injector_test.dart
- dwds/test/puppeteer/extension_test.dart
Support Bolt workflow for the new debug extension. The Dart frame is embedded in an IFRAME, so we need to make sure to connect to the correct frame. 
**See https://github.com/dart-lang/webdev/issues/1779#issuecomment-1441012185 for details on why there is no test (added TODO).**
> [MV3 Debug Extension] Support Bolt workflow

- dwds/debug_extension_mv3/web/panel.dart
Created a new template just for debug extension issues, and switched the "file a bug link" to that template.
> [MV3 Debug Extension] Use the new Dart Debug Extension bug template

- .github/ISSUE_TEMPLATE/dwds.md
- .github/ISSUE_TEMPLATE/frontend_server_client.md
- .github/ISSUE_TEMPLATE/webdev.md
- .github/labeler.yml
- .github/workflows/pull_request_label.yml
- contribute issue templates
- contribute a pull request labeling workflow
@annagrin @elliette 
This will add `package:` labels to PRs that effect those package's files, and will show allow people to specify which package an issue is for in the 'new issue' page.
> contribute issue templates and pull request labeling

- dwds/CHANGELOG.md
- dwds/lib/src/services/expression_evaluator.dart
- dwds/test/expression_evaluator_test.dart
- dwds/test/fixtures/context.dart
Allow expression evaluation on a frame with an empty scope.
Closes: https://github.com/dart-lang/webdev/issues/1997
> Fix expression evaluation failures on empty scopes

- dwds/debug_extension_mv3/web/background.dart
Follow up to https://github.com/dart-lang/webdev/pull/1991
Include page reloads as a navigation event that should be ignored when determining whether a user has navigated away from the Dart app
> [MV3 Debug Extension] Ignore page reloads for detecting navigation away from app

- .github/labeler.yml
- .github/workflows/publish.yaml
- re-enable publishing automation, and update the config to listen for PR label changes (this will let us support the new `publish-ignore-warnings` label to suppress publish dry-run warnings)
- address https://github.com/dart-lang/webdev/issues/1995
- tweak the PR labeling workflow slightly (use `type-infra` instead of `infra`)
> update publishing automation integration

- .github/ISSUE_TEMPLATE/dart_debug_extension.md
- .github/labeler.yml
Follow up to https://github.com/dart-lang/webdev/pull/1979
> Create a Dart Debug Extension issue template

- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/test/chrome_proxy_service_test.dart
Fixes https://github.com/Dart-Code/Dart-Code/issues/4414#issuecomment-1450374486
When listening to a stream, DDS does a streamListen on the VMService. If the VMService, doesn't recognize the stream it will respond with `kInvalidParams`. This lets DDS know that the stream is nonstandard, [so it can handle the events for that stream on it's own.](https://dart-review.googlesource.com/c/sdk/+/275121/4/pkg/dds/lib/src/stream_manager.dart#226)
This PR changes DWDS to behave like the VMService in this regard. Fixing this will allow us to streamListen on custom streams using DWDS.
> Fix for listening to custom streams in DWDS.

- dwds/debug_extension_mv3/web/debug_session.dart
- dwds/test/puppeteer/extension_test.dart
- dwds/test/puppeteer/fake_app/main.js
Follow-up to https://github.com/dart-lang/webdev/issues/2025, fixes the underlying issue. 
Allows users on older versions of DWDS (`>18.0.0`) to still authenticate with the Dart Debug Extension.
> [MV3 Debug Extension] Fix authentication issue for the Dart Debug Extension

- dwds/pubspec.yaml
- dwds/test/fixtures/server.dart
- dwds/test/instances/record_inspection_test.dart
- webdev/CHANGELOG.md
- webdev/lib/src/command/build_command.dart
- webdev/lib/src/command/daemon_command.dart
- webdev/lib/src/command/serve_command.dart
- webdev/lib/src/daemon/app_domain.dart
- webdev/lib/src/pubspec.dart
- webdev/lib/src/serve/webdev_server.dart
- webdev/pubspec.yaml
- webdev/test/chrome_test.dart
- webdev/test/integration_test.dart
Update build_daemon constraint check to `^4.0.0` to match the latest build_runner constraint requirements.
Closes: https://github.com/dart-lang/webdev/issues/2028
Closes: https://github.com/dart-lang/webdev/issues/1939
Related: https://github.com/dart-lang/webdev/pull/2031 (disables broken chrome tests)
Related: https://github.com/dart-lang/webdev/issues/2033 (disables broken record tests)
**Details**
This is one is a part of 3 unrelated CI breaks:
- build runner constraint broken by build_daemon update (current)
https://github.com/dart-lang/webdev/issues/2028  
https://github.com/dart-lang/webdev/pull/2029 (current)
- record type matching broken by SDK update: 
https://github.com/dart-lang/webdev/issues/2033
https://github.com/dart-lang/webdev/pull/2032 
-  chrome tests broken by …
> Update build_daemon constraint and log errors

- .github/workflows/dart.yml
- tool/ci.sh
- update to the latest mono_repo generated CI
- switch back to using the latest publish version of the setup-dart action
> update to the latest mono_repo generated CI

- webdev/test/integration_test.dart
Work towards https://github.com/dart-lang/webdev/issues/2050
Also cleans up the test a little by saving the pubspec.yaml contents to a variable that can be re-used.
> Skip failing webdev `integration_test` cases

- dwds/lib/src/debugging/dart_scope.dart
- dwds/test/instances/patterns_inspection_test.dart
- fixtures/_experimentSound/web/main.dart
Fixes https://github.com/dart-lang/webdev/issues/2060
Work towards https://github.com/dart-lang/webdev/issues/2056
See screenshots below:
-  `name` is not shown (this matches the behavior of `vm_service`)
- `count` is `null` (as expected)
- `first` and `second` are not shown (as expected)
-  `name` is shown and is `null` (does not match `vm_service` implementation!)
- `first` and `second` are shown as `null` (not expected!)
> Don't show non-instantiated variables

- tool/release.dart
A script to automate most of the manual steps of releasing `webdev` / `dwds` was recently added:
* https://github.com/dart-lang/webdev/pull/2049
As were `pubspec_override.yaml` files (this was so we wouldn't have to comment-out our dependency overrides when publishing):
* https://github.com/dart-lang/webdev/pull/2048
Reading through comments on https://github.com/dart-lang/pub/pull/3782, it seems `pubspec_overrides` **are** used during publishing. 
Therefore, this PR updates our release script to comment out the overrides when publishing, and un-comment them when resetting the packages after publishing.
> Update the release script to take into account `pubspec_overrides.yaml`

- dwds/analysis_options.yaml
- dwds/debug_extension_mv3/web/background.dart
- dwds/debug_extension_mv3/web/cross_extension_communication.dart
- dwds/debug_extension_mv3/web/debug_session.dart
- dwds/debug_extension_mv3/web/lifeline_connection.dart
- dwds/debug_extension_mv3/web/messaging.dart
- dwds/debug_extension_mv3/web/panel.dart
- dwds/debug_extension_mv3/web/utils.dart
- Follow-up to https://github.com/dart-lang/webdev/pull/2055 (responding to @jacob314's comments there)
- Work towards https://github.com/dart-lang/webdev/issues/2053
> Dart Code Metrics follow-up

- .github/workflows/daily_testing.yml
- dwds/dart_test.yaml
- dwds/test/chrome_proxy_service_test.dart
Final step in https://github.com/dart-lang/webdev/issues/2093 (besides updating documentation)
- Adds a Github workflow to run any DWDS tests tagged `daily` everyday at 8 AM PST
- Currently the only test is `chrome_proxy_service_test`, which will catch any breakages to DWDS from the VM Service
> Run `chrome_proxy_service_test.dart` everyday at 8 AM PST

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/classes.dart
- dwds/lib/src/debugging/dart_scope.dart
- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/debugging/inspector.dart
- dwds/lib/src/debugging/instance.dart
- dwds/lib/src/debugging/libraries.dart
- dwds/lib/src/debugging/metadata/class.dart
- dwds/lib/src/services/batched_expression_evaluator.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/services/expression_evaluator.dart
- dwds/lib/src/utilities/domain.dart
- dwds/test/debugger_test.dart
- dwds/test/evaluate_common.dart
- dwds/test/expression_evaluator_test.dart
- dwds/test/fixtures/fakes.dart
- dwds/test/inspector_test.dart
- dwds/test/instances/instance_inspection_common.dart
- dwds/test/instances/instance_inspection_test.dart
- dwds/test/instances/instance_test.dart
- dwds/test/instances/record_type_inspection_test.dart
- dwds/test/instances/type_inspection_test.dart
- dwds/test/metadata/class_test.dart
- fixtures/_testPackageSound/pubspec.yaml
In this PR:
- Modify class metadata to determine an object's runtime type kind
- Modify instance.dart to convert from runtime objects to instances better
- show types concisely 
- all types are shown as instances of `core:Type` class
- print the type name correctly
- no internal type representation details
- matches vm display of types
- show native JavaScript types and errors as objects of their type
- Move getProperties from debugger to inspector
- cache runtime kinds of classRefs to support better runtime object type detection
- Add type inspection tests
**Before**
**After**
*VSCode* (consistent with VM)
*DevTools* (consistent with VM)
Closes: https://github.com/dart-lang/webdev/issues/2086
Towards: https://github.com/dart-lang/webdev/issues/1949
> Hide internal implementation details in type objects

- dwds/debug_extension_mv3/build.yaml
Actual fix for the broken Dart Debug Extension builder based on the comment in https://github.com/dart-lang/webdev/pull/2116#issuecomment-1546435028
> Dart Debug Extension builder fix

- dwds/pubspec.yaml
- dwds/test/debug_extension_test.dart
- dwds/test/devtools_test.dart
Work towards https://github.com/dart-lang/webdev/issues/2114
The extension tests are testing the old extension anyways, I need to update to using the puppeteer tests anyways (see https://github.com/dart-lang/webdev/pull/2100).
> Disable tests using webdriver

- .github/workflows/changelog_reminder.yml
- .github/workflows/daily_testing.yml
- .github/workflows/dcm.yml
- .github/workflows/release_reminder.yml
Copies the changes over from https://github.com/dart-lang/webdev/pull/2104, but excludes `dart.yaml` updates. 
See https://github.com/dart-lang/webdev/pull/2112 for the reasoning
> Manually update dependencies 

- .github/dependabot.yml
The dependabot PRs update the `dart.yaml` file, which is generated by `mono_repo generate`.  That means for every dependabot PR, the `mono_repo validate` step fails (`dart.yaml` no longer matches what it would be if it were generated).
See https://github.com/dart-lang/webdev/pull/2104 for example
Therefore the dependabot PRs should not update the `dart.yaml` file.
> Try to fix dependabot PRs

- dwds/CHANGELOG.md
- dwds/lib/shared/batched_stream.dart
I noticed in my expression evaluation experiments that changing the delay in batched stream to 100ms from 200ms does not always change how often the batches are emitted, due to waiting time for the next event being  greater than the delay.
Fix that by making the duration we use for waiting for a new event a fraction of the batch delay.
Not adding tests since the behavior is not supposed to change, only the timing.
> Check for new events more often in batched stream.

- dwds/test/web/batched_stream_test.dart
Test 'Batched stream controller | emits batches' from `batched-stream-test.dart` is flaky on windows. Disable for now to unblock PRs.
Opened an issue to address the flake:  https://github.com/dart-lang/webdev/issues/2126
> Disable flaky test on windows

- dwds/lib/src/readers/proxy_server_asset_reader.dart
Fixes b/284033857 when combined with cl/537127416 
Notifies the code runner that a request has come from DWDS instead of from Chrome.
> Include `requested-by = DWDS` header in ProxyServerAssetReader

- dwds/debug_extension_mv3/web/manifest_mv2.json
- dwds/debug_extension_mv3/web/manifest_mv3.json
From Chrome extension documentation (https://developer.chrome.com/docs/extensions/reference/tabs/#perms):
>The "tabs" permission
> This permission does not give access to the chrome.tabs namespace. Instead, it grants an extension the ability to call [tabs.query()](https://developer.chrome.com/docs/extensions/reference/tabs/#method-query) against four sensitive properties on [tabs.Tab](https://developer.chrome.com/docs/extensions/reference/tabs/#type-Tab) instances: url, pendingUrl, title, and favIconUrl.
Therefore we don't need the permission since we are not calling `tabs.query` against any of those properties.
> Remove tabs permission for the Dart Debug Extension

- webdev/test/installation_test.dart
We keep hitting the timeout limit on CI
> Double the timeout for the webdev installation test

- .github/workflows/dcm.yml
Follow up to https://github.com/dart-lang/webdev/pull/2135
Currently the DCM workflow is running against the last commit on the master branch, not on the PR branch
From reading https://github.com/orgs/community/discussions/25191#discussioncomment-3246770, I believe github.event.pull_request.head.sha is what we want.
> Use `github.event.pull_request.head.sha` as PR reference in DCM workflow

- dwds/.gitignore
- dwds/pubspec.yaml
- dwds/test/puppeteer/extension_test.dart
We recently removed the `tabs` permission for the debug extension: https://github.com/dart-lang/webdev/pull/2136
This is because we weren't using the permission in the extension itself, however we were using it in the tests. 
This PR:
- refactors the tests so that we don't require the `tabs` permission
- updates to the newest version of puppeteer
Work towards https://github.com/dart-lang/webdev/issues/1787
> Fix the Puppeteer tests for the Debug Extension

- dwds/debug_extension_mv3/pubspec.yaml
- dwds/debug_extension_mv3/web/chrome_api.dart
- dwds/debug_extension_mv3/web/debug_session.dart
- dwds/debug_extension_mv3/web/manifest_mv2.json
- dwds/debug_extension_mv3/web/manifest_mv3.json
See details in https://bugs.chromium.org/p/chromium/issues/detail?id=1469092
This PR skips forwarding events that will cause a crash to Chrome, and instead displays a warning to the user:
FYI @DanTup
> Dart Debug Extension: don't forward events to Chrome that will cause a crash

- dwds/test/devtools_test.dart
- dwds/test/events_test.dart
Work towards https://github.com/dart-lang/webdev/issues/2181
I'm guessing these test failures are due to the recent DevTools release (especially since the events we are missing are coming from Devtools, eg: https://github.com/flutter/devtools/blob/a65774257de3a186022412391af90cb5e1a17759/packages/devtools_app/lib/src/screens/debugger/debugger_screen.dart#L199)
Need to do more debugging, but currently running these tests locally isn't possible due to a Chrome regression: https://bugs.chromium.org/p/chromium/issues/detail?id=1466427
> Skip flaky `events_test.dart`

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- dwds/test/chrome_proxy_service_test.dart
- dwds/test/devtools_test.dart
- dwds/test/events_test.dart
- dwds/test/fixtures/context.dart
Hotfix for current Flutter beta crasher: https://github.com/flutter/flutter/issues/132160
FYI @christopherfujino @DanTup
> Preparation for hotfix release 19.0.1+1

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/test/chrome_proxy_service_test.dart
- dwds/test/fixtures/context.dart
Work towards https://github.com/flutter/flutter/issues/132160
Apply the fix from https://github.com/dart-lang/webdev/pull/2186 to DWDS main
> Fix Flutter crash by catching WipError on resume and mapping to RPC error

- dwds/lib/src/handlers/dev_handler.dart
- dwds/test/events_test.dart
The `events_test` was disabled in https://github.com/dart-lang/webdev/pull/2182
Now that the Chromedriver regression has been resolved (https://bugs.chromium.org/p/chromium/issues/detail?id=1466427), I was able to figure out what was going wrong.
The latest DevTools release has added a new "home" screen (see screenshot below). For web apps, we want to auto-open the debugger panel instead, which is where the `DEBUGGER_READY` and `DEVTOOLS_LOAD` events get emitted.
> Re-enable `events_test` with fix

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- dwds/test/chrome_proxy_service_test.dart
- dwds/test/devtools_test.dart
- dwds/test/events_test.dart
- dwds/test/fixtures/context.dart
Follow up to https://github.com/dart-lang/webdev/pull/2186
This is a hotfix for the **next** Flutter beta (which has version `19.0.2`, not `19.0.1`)
Work towards https://github.com/flutter/flutter/issues/132160
> Preparation for hotfix release 19.0.2+1

- dwds/CHANGELOG.md
- dwds/pubspec.yaml
- frontend_server_common/pubspec.yaml
- test_common/pubspec.yaml
Needed for https://github.com/flutter/flutter/pull/123260.
> Update `file` dependency.

- dwds/CHANGELOG.md
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
Resolve version compatibility issues with `package:file` so that DWDS can be updated in `flutter_tools`. 
See https://github.com/flutter/flutter/pull/123260#issuecomment-1674001623
> Prepare DWDS for release to version 20.0.1

- fixtures/_webdevSoundSmoke/pubspec.yaml
Packages rolled into the Dart SDK via DEPS need to have non-colliding package names.
Bug: b/297182119
> Fix conflicting webdev smoke package names.

- dwds/CHANGELOG.md
- dwds/lib/src/loaders/legacy.dart
- dwds/lib/src/loaders/require.dart
- dwds/lib/src/loaders/strategy.dart
- dwds/test/fixtures/fakes.dart
- dwds/test/load_strategy_test.dart
Simplifies the logic added in https://github.com/dart-lang/webdev/pull/2203 to no longer require an app entrypoint to determine the package config path
> Pass the package config directly to the load strategy instead of depending on an app entrypoint

- .github/workflows/dart.yml
- dwds/CHANGELOG.md
- dwds/debug_extension/pubspec.yaml
- dwds/debug_extension_mv3/pubspec.yaml
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/services/debug_service.dart
- dwds/lib/src/utilities/objects.dart
- dwds/pubspec.yaml
- example/pubspec.yaml
- fixtures/_experimentSound/pubspec.yaml
- fixtures/_test/pubspec.yaml
- fixtures/_testCircular1/pubspec.yaml
- fixtures/_testCircular1Sound/pubspec.yaml
- fixtures/_testCircular2/pubspec.yaml
- fixtures/_testCircular2Sound/pubspec.yaml
- fixtures/_testPackage/pubspec.yaml
- fixtures/_testPackageSound/pubspec.yaml
- fixtures/_testSound/pubspec.yaml
- fixtures/_webdevSmoke/pubspec.yaml
- fixtures/_webdevSoundSmoke/pubspec.yaml
- frontend_server_client/CHANGELOG.md
- frontend_server_client/pubspec.yaml
- frontend_server_client/test/frontend_sever_client_test.dart
- frontend_server_common/pubspec.yaml
- test_common/pubspec.yaml
- tool/ci.sh
- tool/pubspec.yaml
- webdev/CHANGELOG.md
- webdev/lib/src/pubspec.dart
- webdev/pubspec.yaml
Update SDK constraints for most packages to the first `dev` release of 3.2.0 since the stable 3.1.0 release doesn't actually include the DDC debugger runtime API changes, but will allow for package resolution with the `3.1.0-...-dev` constraint and a 3.1.0 SDK. This will prevent that.
Others are updated to stable releases.
Issue reference: https://github.com/dart-lang/sdk/issues/53459
> Update SDK constraints for Dart 3.0 and 3.1 stable releases

- fixtures/_webdevSmoke/pubspec.yaml
- fixtures/_webdevSoundSmoke/pubspec.yaml
- webdev/CHANGELOG.md
- webdev/lib/src/serve/webdev_server.dart
- webdev/lib/src/version.dart
- webdev/pubspec.yaml
Prepares a Webdev hotfix to resolve the Dart SDK versioning issue found in https://github.com/dart-lang/sdk/issues/53459
> Prepare `3.0.7+1` hotfix release for Webdev

- .github/workflows/dart.yml
Looks like a bunch of bot PRs are failing due to outdated monorepo config - run `dart pub global run mono_repo generate` to update.
> Run monorepo generate

- dwds/lib/src/utilities/dart_uri.dart
Follow up to https://github.com/dart-lang/webdev/pull/2200
> Clear the map of relative URIs on `DartUri.clear()`

- webdev/CHANGELOG.md
- webdev/README.md
- webdev/lib/src/command/shared.dart
This flag is confusing now that `webdev` requires a Dart 3 SDK which doesn't support unsound null safety. To reduce this confusion, this PR hides the `--null-safety` flag from the output help messages.
I was going to remove use of the flag entirely, but I wasn't sure if the flag is still used internally somehow. Let me know if it doesn't need to be wired up and I'd be happy to remove it :)
> [webdev] Hide `--null-safety` option

- dwds/lib/src/services/batched_expression_evaluator.dart
This is cleanup work required to start enforcing this with static analysis, as per https://github.com/dart-lang/sdk/issues/53253.
Real quick this issue is that this code is unsafe:
```dart
void f(Completer<int> c, int? i) {
Future<int>.value(i); // Ouch!
c.complete(i);        // Ouch!
}
```
This change should be a no-op. Adding this explicit null-assert ensures that any exception is thrown right at the null-assert.
---
<details>
- Contributions to our repos should follow the [Dart style …
> Avoid passing a nullable value to Future<nn-type>.value or Completer<nn-type>.completer.

- dwds/CHANGELOG.md
- dwds/lib/src/services/chrome_proxy_service.dart
Updates the interface to include the optional parameter added in https://dart-review.googlesource.com/c/sdk/+/321660
> Update interface for `ChromeProxyService.getSourceReport`

- dwds/CHANGELOG.md
- dwds/lib/src/config/tool_configuration.dart
- dwds/lib/src/handlers/injector.dart
- dwds/lib/src/injected/client.js
- dwds/test/fixtures/context.dart
- dwds/test/fixtures/server.dart
- dwds/test/puppeteer/extension_common.dart
- dwds/test/puppeteer/test_utils.dart
- dwds/web/client.dart
Add a `workspaceName` parameter to DWDS on start up, which will be used to determine which dart tab to connect to from Cider.
> Add a new workspaceName parameter to DWDS on start up

- dwds/debug_extension_mv3/web/debug_session.dart
- dwds/lib/src/handlers/dev_handler.dart
When it receives a request to start debugging, DWDS sends the debug URI to the Dart Debug Extension, which then sends it to Cider.
> Rename `plainUri` to `debugUri` and send it to the extension

- dwds/debug_extension_mv3/pubspec.yaml
- dwds/debug_extension_mv3/web/manifest_mv2.json
- dwds/debug_extension_mv3/web/manifest_mv3.json
This is the version that supports debugging from Cider
> Prepare the Dart Debug Extension for release to version 1.36

- dwds/debug_extension_mv3/web/utils.dart
- dwds/test/puppeteer/extension_common.dart
We were including `/debugger` in the path, which meant that we were loading the debugger panel instead of the inspector panel.
> Fix issue with the embedded inspector panel

- dwds/test/dart_uri_test.dart
- dwds/test/debug_extension_test.dart
- dwds/test/debug_service_test.dart
- dwds/test/debugger_test.dart
- dwds/test/devtools_test.dart
- dwds/test/events_test.dart
- dwds/test/expression_evaluator_test.dart
- dwds/test/fixtures/context.dart
- dwds/test/fixtures/fakes.dart
- dwds/test/fixtures/server.dart
- dwds/test/fixtures/utilities.dart
- dwds/test/handlers/injector_test.dart
- dwds/test/location_test.dart
- dwds/test/metadata_test.dart
- dwds/test/puppeteer/test_utils.dart
- dwds/test/reload_test.dart
- dwds/test/skip_list_test.dart
Follow up to https://github.com/dart-lang/webdev/pull/2231
> Refactor tests to handle new `ToolConfiguration`

- dwds/debug_extension_mv3/pubspec.yaml
- dwds/debug_extension_mv3/web/cider_connection.dart
- dwds/debug_extension_mv3/web/manifest_mv2.json
- dwds/debug_extension_mv3/web/manifest_mv3.json
Previously we were sending a JSON string to Cider. Cider actually expects the message to be a JS object, so now we are passing a JS object that looks like:
```
{
key: 'CIDER_DART',
json: [[the original json string]]
}
```
> Cider expects messages from a Chrome extension to be a JS object, not a string

- webdev/test/e2e_test.dart
Test-only change.
Adding a test that will catch bugs like https://github.com/dart-lang/sdk/issues/53459 once we have testing of webdev with stable  SDK: https://github.com/dart-lang/webdev/issues/2226
> Add evaluation test to webdev to catch issues with runtime debugging API

- .github/workflows/daily_stable_testing.yml
Fixes https://github.com/dart-lang/webdev/issues/2226
This PR adds a Github workflow to run the Webdev tests with the Dart stable SDK on a daily cron job. 
The workflow:
- Sets up the Dart stable SDK
- Runs `dart pub global activate webdev` to get the latest Webdev compatible with the stable SDK
- Gets the activated Webdev version
- Checks out the Webdev repo at the commit for that version tag
- Runs all the Webdev tests at that commit
This means that any tests added after the Webdev release was cut will not be included (so the test case added in https://github.com/dart-lang/webdev/pull/2250 won't be run as part of the stable testing until the current dev version of Webdev is the version activated for the Dart stable SDK).
Example workflow run: …
> Run the Webdev tests daily with the Dart stable SDK

- dwds/lib/src/dwds_vm_client.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/services/debug_service.dart
- dwds/pubspec.yaml
- dwds/pubspec_overrides.yaml
- dwds/test/build_daemon_breakpoint_test.dart
- dwds/test/build_daemon_callstack_test.dart
- dwds/test/chrome_proxy_service_test.dart
- dwds/test/evaluate_circular_common.dart
- dwds/test/events_test.dart
- dwds/test/fixtures/context.dart
- dwds/test/frontend_server_breakpoint_test.dart
- dwds/test/frontend_server_callstack_test.dart
- dwds/test/instances/common/instance_inspection_common.dart
- dwds/test/instances/common/patterns_inspection_common.dart
- dwds/test/instances/common/record_inspection_common.dart
- dwds/test/instances/common/record_type_inspection_common.dart
- dwds/test/instances/common/test_inspector.dart
- dwds/test/instances/common/type_inspection_common.dart
- dwds/test/refresh_test.dart
- dwds/test/restore_breakpoints_test.dart
- dwds/test/run_request_test.dart
- webdev/CHANGELOG.md
- webdev/pubspec.yaml
Since `package:vm_service` is still `^12.0.0`, imports of `vm_service` have been modified to hide duplicate symbols that are now surfaced via `package:vm_service_interface`.
> Add dependency on `package:vm_service_interface`

- dwds/debug_extension_mv3/web/background.dart
- dwds/debug_extension_mv3/web/chrome_api.dart
- dwds/debug_extension_mv3/web/copier.dart
- dwds/debug_extension_mv3/web/manifest_mv2.json
- dwds/debug_extension_mv3/web/manifest_mv3.json
- dwds/debug_extension_mv3/web/messaging.dart
- dwds/debug_extension_mv3/web/static_assets/styles.css
Expose a keyboard shortcut to copy the Dart app's ID. When copied, shows a banner at the bottom of the page notifying the user that the app ID has been copied.
> Expose a keyboard shortcut to copy the Dart app ID

- dwds/debug_extension_mv3/web/static_assets/styles.css
DDR places a banner at the bottom of a Dart app, which was blocking our banner when a user tried to copy the Dart app ID. 
Instead, this PR has the banner appear/disappear from the top of the page.
> [Polish] Add banner to the top of the page instead of the bottom

- dwds/debug_extension_mv3/pubspec.yaml
- dwds/debug_extension_mv3/web/manifest_mv2.json
- dwds/debug_extension_mv3/web/manifest_mv3.json
This version includes the functionality to copy the app ID to the clipboard
> Prepare the Dart Debug Extension for release to version 1.38

- dwds/debug_extension_mv3/web/background.dart
- dwds/debug_extension_mv3/web/copier.dart
- dwds/debug_extension_mv3/web/debug_session.dart
- dwds/debug_extension_mv3/web/manifest_mv2.json
- dwds/debug_extension_mv3/web/manifest_mv3.json
- dwds/debug_extension_mv3/web/static_assets/styles.css
- dwds/debug_extension_mv3/web/utils.dart
Follow up fix for https://github.com/dart-lang/webdev/issues/2278
Instead of injecting HTML/CSS into the webpage, instead show a Chrome notification.
> Show a Chrome notification when the app ID has been copied instead of a banner

- dwds/lib/src/handlers/dev_handler.dart
- removes no longer necessary code
- makes sure that the "launch devtools" event is sent when the debug extension starts debugging
> Remove old code from before the new Dart Debug Extension

- dwds/debug_extension_mv3/pubspec.yaml
- dwds/debug_extension_mv3/web/cider_connection.dart
- dwds/debug_extension_mv3/web/debug_session.dart
- dwds/debug_extension_mv3/web/manifest_mv3.json
> Notify Cider when connection is successful 

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/classes.dart
Work towards https://github.com/dart-lang/webdev/issues/2297
> Fix `cast` error when debugging from VSCode

- test_common/lib/test_sdk_configuration.dart
CI was hanging on my PR (https://github.com/dart-lang/webdev/actions/runs/7224561961/job/19690368821?pr=2307) and it looks like this change will fix it.
> Fix TestSdkConfigurationProvider.dispose

- dwds/test/instances/class_inspection_test.dart
- fixtures/_experimentSound/web/main.dart
Adds a test for https://github.com/dart-lang/webdev/issues/2297
Ideally we should throw an exception in the case that the class is non-existent (instead of returning an empty class representation) but first we should make sure the clients are handling the exception.
> Add a test for `Class` inspection 

- .github/workflows/dart.yml
- dwds/CHANGELOG.md
- dwds/lib/src/debugging/classes.dart
- dwds/lib/src/debugging/location.dart
- dwds/lib/src/version.dart
- dwds/mono_pkg.yaml
- dwds/pubspec.yaml
- dwds/test/inspector_test.dart
- dwds/test/instances/class_inspection_test.dart
- dwds/test/instances/common/instance_common.dart
- dwds/test/variable_scope_test.dart
- fixtures/_experimentSound/web/main.dart
- frontend_server_client/test/frontend_sever_client_test.dart
- test_common/lib/utilities.dart
- test_common/pubspec.yaml
- tool/ci.sh
- webdev/mono_pkg.yaml
We would like to hotfix this version of DWDS into Flutter stable to resolve https://github.com/dart-lang/webdev/issues/2297
This hotfix cherry-picks the following changes on top of DWDS version 21.0.0:
- https://github.com/dart-lang/webdev/pull/2303
- https://github.com/dart-lang/webdev/pull/2310
I've disabled testing against the main branch of the Dart SDK for DWDS. The Github action is incorrectly pulling an old version of Dart (from November) from https://storage.googleapis.com/dart-archive/channels/be/raw/latest instead of https://storage.googleapis.com/dart-archive/channels/main/raw/latest
> Prepare a hotfix release of DWDS 21.0.0+1

- .github/workflows/dart.yml
- dwds/CHANGELOG.md
- dwds/lib/src/debugging/classes.dart
- dwds/lib/src/debugging/location.dart
- dwds/lib/src/version.dart
- dwds/mono_pkg.yaml
- dwds/pubspec.yaml
- dwds/test/inspector_test.dart
- dwds/test/instances/class_inspection_test.dart
- dwds/test/instances/common/instance_common.dart
- dwds/test/variable_scope_test.dart
- fixtures/_experimentSound/web/main.dart
- frontend_server_client/test/frontend_sever_client_test.dart
- test_common/lib/utilities.dart
- test_common/pubspec.yaml
- tool/ci.sh
- webdev/mono_pkg.yaml
- webdev/test/e2e_test.dart
We would like to hotfix this version of DWDS into Flutter beta to resolve https://github.com/dart-lang/webdev/issues/2297
This has the same changes as https://github.com/dart-lang/webdev/pull/2319, with the only difference being this is a hotfix on top of 22.1.0 (which is on Flutter beta) instead of 21.0.0 (which is on Flutter stable)
> Prepare a hotfix release of DWDS  22.1.0+1 

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/dart_scope.dart
- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/debugging/inspector.dart
- dwds/test/inspector_test.dart
- dwds/test/variable_scope_test.dart
- fixtures/_test/example/scopes/main.dart
Fixes https://github.com/dart-lang/webdev/issues/2316, https://github.com/dart-lang/webdev/issues/2340
Filter out internal type representations and type fields from the new DDC type system.
> Filter out internal type properties from the new DDC type system

- dwds/CHANGELOG.md
- dwds/lib/dart_web_debug_service.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/test/chrome_proxy_service_test.dart
- dwds/test/fixtures/context.dart
Work towards https://github.com/flutter/devtools/issues/5265, https://github.com/dart-lang/webdev/issues/2257
This is part of a series of changes to fix the "phantom breakpoints" issue described here: https://github.com/dart-lang/webdev/issues/2257#issuecomment-1942909830
> Implement `setFlag` for 'pause_isolates_on_start'

- frontend_server_client/mono_pkg.yaml
- frontend_server_client/test/frontend_server_client_test.dart
Disable the `frontend_server_client_test` on windows. 
This test has begun failing with a timeout error, see https://github.com/dart-lang/webdev/actions/runs/8034050792
> Disable `frontend_server_client_test` on windows

- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/pubspec.yaml
- dwds/test/chrome_proxy_service_test.dart
- dwds/test/debug_service_test.dart
- dwds/test/fixtures/utilities.dart
- webdev/pubspec.yaml
- webdev/test/integration_test.dart
The skipped tests will be re-enabled with https://github.com/dart-lang/webdev/pull/2388, but I'm still working on getting all the tests passing in that PR
> Fix broken tests on head due to Dart SDK update

- dwds/lib/src/loaders/strategy.dart
- dwds/lib/src/utilities/dart_uri.dart
The library root and package config loader are necessary to support test debugging internally.
> Add `libraryRoot` and `packageConfigLoader` to the `LoadStrategy`

- dwds/lib/src/debugging/debugger.dart
Accidentally submitted `print` statements in https://github.com/dart-lang/webdev/pull/2371, this simply removes them. 
Follow-up will be to add a lint that catches this.
> Remove accidentally committed `print` statements

- dwds/lib/dart_web_debug_service.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/test/chrome_proxy_service_test.dart
Follow up to https://github.com/dart-lang/webdev/pull/2373
The `debugConnection` method (in which we were listening to the `pauseIsolatesOnStartStream`) is actually only called from test code. 🤦‍♀️ 
This allows us to actually access the `pause_isolates_on_start` flag value in the `Dwds` class.
Work towards https://github.com/flutter/devtools/issues/7231
> Fix reading `pause_isolates_on_start` value from the DWDS

- webdev/test/integration_test.dart
Fixes https://github.com/dart-lang/webdev/issues/2404,  https://github.com/dart-lang/webdev/issues/2050
Whenever pub updates the failure messages for proper package validation, this integration test fails because we are checking string messages that come from `pub`, not `webdev`. This removes validating that the messages from pub are what is expected, since we don't control those messages in the first place (and therefore shouldn't be testing them).
> Webdev integration_test should not check for string messages that come from pub

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/debugging/frame_computer.dart
- dwds/test/debugger_test.dart
Fixes https://github.com/dart-lang/webdev/issues/2407
> Catch errors when calculating frames in the stack trace

- .github/workflows/dcm.yml
This is equivalent to what Devtools did a while back: https://github.com/flutter/devtools/pull/6703
It ensures that we don't get new DCM failures on PRs when DCM is updated
> Pin DCM to latest version

- frontend_server_common/lib/src/frontend_server_client.dart
- frontend_server_common/lib/src/uuid.dart
- frontend_server_common/pubspec.yaml
- remove the dep on `package:uuid`
This will make the repo a little easier to bring into the sdk repo.
---
<details>
- Changes to packages require [corresponding …
> remove the dep on package:uuid

- dwds/lib/dart_web_debug_service.dart
- dwds/lib/src/handlers/dev_handler.dart
Follow up to https://github.com/dart-lang/webdev/pull/2418
In google3, the buildSettings are not actually created until the app's entrypoint is loaded, which means that this was throwing a null-pointer exception. 
Instead, we send the dwds launch event only once we have a debug connection with the app (which ensures that we have loaded the entrypoint).
> Move DWDS launch event

- dwds/CHANGELOG.md
- dwds/lib/dart_web_debug_service.dart
- dwds/lib/src/connections/app_connection.dart
- dwds/lib/src/dwds_vm_client.dart
- dwds/lib/src/handlers/dev_handler.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/test/chrome_proxy_service_test.dart
- dwds/test/reload_test.dart
I was putting together a doc about the many places we wait for a `resume` event after either a hot-restart or a page-refresh when `pauseIsolatesOnStart` is `true`, and realized that I had missed waiting for the `resume` event for page refreshes when running an app with `flutter_tools`. 
I then realized that the solution implemented for waiting for a `resume` event after a page-refresh for internal apps (https://github.com/dart-lang/webdev/pull/2398 and cl/626138927) could be modified to work for both `flutter_tools` and internal apps. These modifications are in this PR.
Before this change:
- DWDS exposed a method `shouldPauseIsolatesOnStart` which could be called by a client (flutter_tools, DDR) to determine whether or not to immediately call DWDS' `runMain` method after an app connection …
> Wait for a `resume` event to run the `main()` method after a page refresh

- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/debugging/frame_computer.dart
Follow-up to https://github.com/dart-lang/webdev/pull/2408, where we began logging frame calculation errors.
When this happens, it seems that a lot of frames are unable to be calculated, not just a few (see screenshot below). This PR adds logic to keep track of the error count, and log that instead (to avoid spamming the console).
> Log a single error message when async or sync frame calculation fails

- dwds/lib/src/dwds_vm_client.dart
This is a workaround for a Cider bug, see b/342668928 for details.
> Register a restart handler directly over the VM service connection

- dwds/lib/src/dwds_vm_client.dart
Follow up to https://github.com/dart-lang/webdev/pull/2437
Ideally web developers should be able to choose whether the "restart" button from Cider triggers a hot restart or a page reload (this is because hot-restart is not supported for all internal web apps). 
This changes the `ext.dwds.restart` service extension to trigger a hot-restart, and adds `ext.dwds.reload` which will trigger a page reload.
> Add a reload handler along with a restart handler

- dwds/CHANGELOG.md
- dwds/lib/src/services/chrome_proxy_service.dart
Fixes https://github.com/dart-lang/sdk/issues/55860
DAP is waiting for a `kPausePostRequest` after restarting to know to resume the isolate. DWDS was never sending this event, so the app was never resumed: https://github.com/dart-lang/sdk/blob/6549a66a50c7a732e51df68322c604936057ecea/pkg/dds/lib/src/dap/isolate_manager.dart#L644
> Send a `kPausePostRequest` after restarting to notify clients to resume

- dwds/CHANGELOG.md
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/test/chrome_proxy_service_test.dart
Fixes https://github.com/dart-lang/sdk/issues/55859
FYI @DanTup
> Implement the VM service `getFlagList` API

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/dart_scope.dart
- dwds/test/variable_scope_test.dart
Some variables created by DDC that are not present in the original source code were being shown by the debugger in the local scope.
Update the regular expression used to detect temporary variable names. It has been simplified to: if the variable starts with 't$' or contains '$35' then it should be hidden.
DDC names it's temporary variables to start with the characters `t$`. Hiding all of these does hide some valid variable names that could appear in the original source, but that is the status quo and not being changed here. In addition some names that are created by the CFE and added to the program contain an illegal character '#' which DDC replaces as '$35'. Variables with this sequence in the name can't appear in the original source so we hide them as well.
This should hide variables …
> Hide more temporary variables when debugging

- dwds/debug_extension/tool/build_extension.dart
Fixes https://github.com/dart-lang/webdev/issues/2450
> Remove remaining MV2 logic

- dwds/test/instances/common/instance_inspection_common.dart
Fixes tests that break due to https://dart-review.googlesource.com/c/sdk/+/373327
DDC now represents `_HashSet` object as `LinkedSet` in its internal representation (no implementation changes).
> Fixing Set runtime type names in DDC

- dwds/test/instances/common/instance_inspection_common.dart
- dwds/test/instances/common/test_inspector.dart
DDC Sets Impls are now in `dart:_js_helper` (like with Maps) instead of `dart:collection`.
> Updating test expectations for DDC Set implementations.

- dwds/test/instances/common/test_inspector.dart
- dwds/test/instances/common/type_inspection_common.dart
Also fixes an additional failing test condition.
Follow up to https://github.com/dart-lang/webdev/pull/2458
> Remove unused variable

- dwds/test/devtools_test.dart
This test is currently failing for unknown reasons and needs to be investigated.
See https://github.com/dart-lang/webdev/issues/2462
> Disable 'Injected client can not launch devtools for the same app in multiple tabs'

- dwds/test/build_daemon_ddc_and_canary_evaluate_test.dart
- dwds/test/expression_compiler_service_common.dart
- dwds/test/expression_compiler_service_ddc_and_canary_test.dart
- dwds/test/frontend_server_ddc_and_canary_evaluate_test.dart
DDC hot reload requires a new module format. This is represented by the intersection of the DDC module format and canary. In order to make sure the new format is tested, this changes replicates any existing expression evaluation tests to use the DDC module format and canary.
> Expand expression evaluation tests to also test DDC module format + canary

- dwds/CHANGELOG.md
- dwds/lib/src/services/debug_service.dart
- dwds/lib/src/utilities/server.dart
- dwds/pubspec.yaml
This is part of the effort to stop shipping DDS via Pub.
> [ DWDS ] Spawn DDS in a process rather than using package:dds

- dwds/lib/src/debugging/dart_scope.dart
- dwds/test/variable_scope_test.dart
- fixtures/_testSound/example/scopes/main.dart
The Dart web team recently updated DDC's async lowering to be more similar to that of dart2js. The previous lowering did not correctly implement the Dart language's async/await semantics causing divergences in code's behavior between production and development.
The new lowering creates a state machine that simulates the control flow from the Dart code. This lowering flattens the async function's body removing the scopes established by the Dart code (normally JS's scopes act as a proxy for Dart's scopes). To get around this we introduce scope objects that we use to manually reconstruct the original scopes.
For debugging purposes we want to make all the variables in these scope objects available as they are all user-declared variables in the source code. So to achieve this we unpack the …
> Add variable support for new DDC async lowering

- frontend_server_client/test/frontend_server_client_test.dart
I believe that the issue causing the timeouts was fixed in https://github.com/dart-lang/sdk/commit/69b801f73f7b26adb661257ecab862eca6dcf7dd.
Fixes: https://github.com/dart-lang/webdev/issues/2377
> Re-enable skipped frontend_server_client test cases

- dwds/test/chrome_proxy_service_test.dart
- fixtures/_testSound/example/hello_world/main.dart
This fixes breakages from an incoming change to update how DDC represents generic types. 
The old code here was manually invoking Dart constructors from JS; this broke when we changed their APIs to accept an RTI. The new scheme evals a top-level object (initialized with the correct state).
Old breaks: https://github.com/dart-lang/webdev/actions/runs/10285790803/job/28464927549
> Updating Chrome Proxy Service tests to avoid manually invoking generic Dart constructors.

- dwds/lib/src/debugging/instance.dart
The vm_service [Instance](https://github.com/dart-lang/sdk/blob/main/pkg/vm_service/lib/src/vm_service.dart#L4621) spec specifies that the `length` property specifies that `length` should be the number of non-static fields for plain objects. In order to align with the VM we've updated the DDC debugger API to include this value of `length` on plain objects.
However, [`getProperties`](https://github.com/dart-lang/webdev/blob/main/dwds/lib/src/debugging/inspector.dart#L578) is assuming that if a length is provided then it should do a range check with the provided `offset` and `count`. This was causing the `getProperties` code to exit early with no value. 
To fix this we only pass the `length` to `getProperties` if the `kind` of the object being inspected is not a plain object. Plain objects …
> Fix getProperties invocation passing length for all objects.

- dwds/CHANGELOG.md
- dwds/lib/src/services/chrome_proxy_service.dart
This is needed to land the SDK CL that checks in package:vm_service_interface 2.0.0, because this is needed to make the g3-cbuild-try job pass.
> [DWDS] Account for the optional parameters that will be added in package:vm_service_interface 2.0.0

- dwds/CHANGELOG.md
- webdev/CHANGELOG.md
- webdev/lib/src/command/build_command.dart
- webdev/lib/src/command/daemon_command.dart
- webdev/lib/src/command/serve_command.dart
- webdev/lib/src/command/shared.dart
- webdev/lib/src/pubspec.dart
#2496 
I think we should consider also doing #2497.
> Webdev: Look for pubspec.yaml next to .dart_tool/package_config.json instead of only current dir

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/inspector.dart
Replaced deprecated code `this.__proto__` from js code with Object.getPrototypeOf(this).
https://github.com/dart-lang/webdev/issues/2118
> replace deprecated __proto__ from js code

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/metadata/module_metadata.dart
- dwds/lib/src/debugging/metadata/provider.dart
- dwds/lib/src/loaders/ddc.dart
- dwds/lib/src/loaders/ddc_library_bundle.dart
- dwds/lib/src/loaders/strategy.dart
- dwds/test/fixtures/fakes.dart
- dwds/test/metadata_test.dart
DDC library bundle format does not provide module names as part of the ModuleMetadata.
- To support this discrepancy, a flag is added to MetadataProvider to either use the module name or the module path to identify the module.
- createProvider is added so LoadStrategys can create MetadataProviders based on whether the module format uses the module name.
- Cleans up some getters and methods in LoadStrategy implementations so that getters are grouped together.
> Add option to not use module name in MetadataProvider

- dwds/CHANGELOG.md
- dwds/lib/src/injected/client.js
- dwds/pubspec.yaml
- dwds/web/client.dart
- dwds/web/reloader/ddc_restarter.dart
- dwds/web/reloader/manager.dart
- dwds/web/reloader/require_restarter.dart
- dwds/web/run_main.dart
flutter_tools uses v1.1.0, so DWDS needs to support that version before release. This includes:
- not using helpers.dart, which is deprecated.
- not using HtmlElement, which is deprecated.
- not using HttpRequest, which is deprecated, and instead using package:http to do HTTP requests.
- passing a JS value to innerHTML as it now accepts JSAny.
client.dart is recompiled with the same Dart version used before.
> Migrate to package:web v1.1.0

- dwds/CHANGELOG.md
- dwds/lib/src/handlers/socket_connections.dart
- dwds/lib/src/services/debug_service.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- dwds/test/build/ensure_version_test.dart
- updates to be forward compatible with changes to package:shelf_web_socket
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTIN …
> updates to be forward compatible with changes to package:shelf_web_socket

- dwds/test/instances/common/patterns_inspection_common.dart
A bug recently uncovered in DDC required renaming some variables (primarily around patterns) to avoid declarations from shadowing each other incorrectly. 'a' is now 'a$' as it is the second case that declares a Dart variable named 'a'.
> Update pattern test to account for new DDC JS variable naming

- dwds/CHANGELOG.md
- dwds/lib/src/services/batched_expression_evaluator.dart
- dwds/test/expression_evaluator_test.dart
- dwds/test/fixtures/fakes.dart
If a single subexpression throws in a batched request, the whole batch fails. DevTools is using this API to evaluate all the fields/getters on an Object. If any of those getters throw, all the queried members fail to show information.
Instead if the initial batched request fails we can retry each request as individual expression evals. This will correctly surface errors for the subexpression that throws and the proper values for all the other subexpressions.
See #2551
> [dwds] Add unbatching retry mechanism for failing batched expression evals

- dwds/test/build/min_sdk_test.dart
- webdev/test/build/min_sdk_test.dart
It looks like the environment field is correctly analyzed as never possibly null with a newer version of Dart. This fixes Dart CI.
> Handle unnecessary_non_null_assertion and invalid_null_aware_operator

- dwds/CHANGELOG.md
- dwds/debug_extension/web/chrome_api.dart
- dwds/debug_extension/web/cider_connection.dart
- dwds/debug_extension/web/copier.dart
- dwds/debug_extension/web/debug_info.dart
- dwds/debug_extension/web/detector.dart
- dwds/debug_extension/web/devtools.dart
- dwds/debug_extension/web/messaging.dart
- dwds/debug_extension/web/panel.dart
- dwds/debug_extension/web/popup.dart
- dwds/debug_extension/web/storage.dart
- dwds/debug_extension/web/utils.dart
- dwds/debug_extension/web/web_api.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- example/web/main.dart
- fixtures/_experimentSound/web/main.dart
- fixtures/_testCircular2Sound/web/main.dart
- fixtures/_testHotRestart2Sound/web/main.dart
- fixtures/_testPackageSound/web/main.dart
- fixtures/_testSound/example/append_body/main.dart
- fixtures/_testSound/example/hello_world/main.dart
- fixtures/_webdevSoundSmoke/web/main.dart
Dart web libraries are now deprecated. This triggers a lint which we fail on. We should migrate these to dart:js_interop and package:web, but for now, ignore to make CI happy.
This also moves the CHANGELOG, pubspec, and version.dart files to 24.4.0-wip, which is needed for proper_release_test to pass.
> Add ignores for deprecated web libraries with a TODO and move dwds to 24.4.0-wip

- test_common/lib/test_sdk_configuration.dart
webdev/test/e2e_test.dart was failing due to paths with spaces not being handled correctly.
Related issue: https://github.com/dart-lang/webdev/issues/2556
Fixes https://github.com/dart-lang/sdk/issues/59784
> Rename copied SDK directory prefix from 'sdk copy' to 'sdk_copy'

- dwds/CHANGELOG.md
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
24.3.3 has just been published. This resets the version to a WIP version.
> Reset DWDS to 24.3.4-wip

- dwds/CHANGELOG.md
- dwds/lib/src/injected/client.js
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- dwds/test/common/chrome_proxy_service_common.dart
- dwds/web/client.dart
- dwds/web/reloader/ddc_library_bundle_restarter.dart
- dwds/web/reloader/ddc_restarter.dart
- dwds/web/reloader/manager.dart
- dwds/web/reloader/require_restarter.dart
- dwds/web/reloader/restarter.dart
- Modifies the Chrome proxy service to call a callback that the injected client has setup in order to do a hot reload.
- This callback forwards to the restarter.
- This restarter reads from a path that Flutter tools sets up beforehand in order to fetch the changed sources and their associated libraries.
- Issues a hot reload to DDC using that data.
- Reassembles the Flutter engine to render a frame if the extension exists.
- Returns a ReloadReport on whether or not this operation succeeded.
cc @jyameo
> [dwds] Implement hot reload and publish 24.3.4

- webdev/CHANGELOG.md
- webdev/lib/src/serve/utils.dart
- webdev/lib/src/serve/webdev_server.dart
- webdev/lib/src/version.dart
- webdev/pubspec.yaml
- Update `dwds` constraint to `24.3.5`.
- Added a utility method to locate `package_config.json` and set it in the `loadStrategy`.
> set packageConfigPath and update DWDS version to 24.3.5

- .github/workflows/publish.yaml
This is needed in order for packages to be published.
> Add pull request and id-token write permissions to publish.yaml

- dwds/CHANGELOG.md
- dwds/lib/dart_web_debug_service.dart
- dwds/lib/src/handlers/injector.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
Updated DWDS to include a boolean flag that enables debugging support when set to true (default behavior). This flag will enable us to support running a Flutter app on a `web-server` with the new DDC library bundle format. However, it will not support debugging, as debugging features are not compatible with this configuration.
- Related to https://github.com/dart-lang/sdk/issues/60289
> Updated DWDS to include a boolean flag that enables debugging support when set to true

- dwds/CHANGELOG.md
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- webdev/CHANGELOG.md
- webdev/README.md
- webdev/lib/src/command/configuration.dart
- webdev/lib/src/command/shared.dart
- webdev/lib/src/pubspec.dart
- webdev/test/installation_test.dart
- webdev/test/integration_test.dart
- Adds an `--offline` flag which is useful for sandbox/networkless build systems such as Nix.
---
<details>
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding …
> Add offline mode

- dwds/CHANGELOG.md
- dwds/lib/dart_web_debug_service.dart
- dwds/lib/src/handlers/injector.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
Renamed boolean flag in DWDS Injector from `enableDebuggingSupport` to `injectDebuggingSupportCode `. 
- Follows this PR: https://github.com/dart-lang/webdev/pull/2601
- Required for this PR: https://github.com/flutter/flutter/pull/165700
- Related to https://github.com/dart-lang/sdk/issues/60289
> Renamed boolean flag in DWDS Injector

- dwds/CHANGELOG.md
- dwds/lib/src/injected/client.js
- dwds/lib/src/loaders/frontend_server_strategy_provider.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- dwds/web/client.dart
- dwds/web/reloader/ddc_library_bundle_restarter.dart
- dwds/web/reloader/ddc_restarter.dart
- dwds/web/reloader/manager.dart
- dwds/web/reloader/require_restarter.dart
- dwds/web/reloader/restarter.dart
https://github.com/dart-lang/sdk/issues/60186
Breakpoints are currently broken when doing a hot reload when files change. They either are not re-mapped or point to the wrong location. For now, we should disable them in the changed libraries. In order to do this, we split the hot reload implementation into 2 in order to get the list of changed libraries. The call to hot reload will later use the cached list to call out to the embedder.
Note that this likely won't change any behavior. New JS files already don't have breakpoints, so this PR should be mostly about cleaning up bookkeeping.
> [dwds] Split hot reload callback into 2, disable breakpoints in changed files, and publish 24.3.10

- dwds/test/common/chrome_proxy_service_common.dart
"shared context Step Into goes to the next Dart location" in `test/chrome_proxy_service_ddc_library_bundle_test.dart`
Issue: https://github.com/dart-lang/webdev/issues/2617
> [gardening] Temporarily skip failing test case

- webdev/test/e2e_test.dart
These e2e tests have been extremely flaky requiring many retries (these tests are configured to have 3 retries each) and still sometimes failing.
See failing job here:
https://github.com/dart-lang/webdev/actions/runs/15444512522/job/43470375587
Failures all occur due to the missing "Succeeded" message from the build runner logs. Sometimes the build runner process ends without printing this success message:
https://github.com/dart-lang/build/blob/master/build_runner_core/lib/src/generate/build.dart#L216
The updated messages all appear directly before the "Succeeded" message would and indicate the last expected action was successful.
Associated issue: https://github.com/dart-lang/webdev/issues/2489
> Update e2e_test expectation to look for more consistent message.

- dwds/lib/src/handlers/injector.dart
One path used utf8, the other used codeUnits
Better to do it once, correctly
> [dwds] DRY up MD5/etag logic

- dwds/test/instances/common/class_inspection_common.dart
- dwds/test/instances/common/dot_shorthands_common.dart
- dwds/test/instances/common/patterns_inspection_common.dart
- dwds/test/instances/common/record_inspection_common.dart
- dwds/test/instances/common/record_type_inspection_common.dart
- dwds/test/instances/common/test_inspector.dart
- dwds/test/instances/common/type_inspection_common.dart
- dwds/test/instances/dot_shorthands_amd_canary_test.dart
- dwds/test/instances/dot_shorthands_amd_test.dart
- dwds/test/instances/dot_shorthands_ddc_library_bundle_test.dart
- fixtures/_experimentSound/web/main.dart
- webdev/test/tls_test.dart
This PR adds tests that ensure that expression evaluation and single-stepping interact with dot shorthands as expected.
Fixes: https://github.com/dart-lang/sdk/issues/59874
> Add tests covering the ability to debug dot shorthands

- dwds/CHANGELOG.md
- dwds/lib/src/debugging/debugger.dart
- dwds/lib/src/debugging/inspector.dart
- dwds/lib/src/debugging/libraries.dart
- dwds/lib/src/debugging/location.dart
- dwds/lib/src/debugging/metadata/module_metadata.dart
- dwds/lib/src/debugging/metadata/provider.dart
- dwds/lib/src/debugging/modules.dart
- dwds/lib/src/debugging/skip_list.dart
- dwds/lib/src/injected/client.js
- dwds/lib/src/loaders/ddc_library_bundle.dart
- dwds/lib/src/loaders/strategy.dart
- dwds/lib/src/services/chrome_proxy_service.dart
- dwds/lib/src/version.dart
- dwds/pubspec.yaml
- dwds/test/debugger_test.dart
- dwds/test/expression_evaluator_test.dart
- dwds/test/fixtures/context.dart
- dwds/test/fixtures/fakes.dart
- dwds/test/fixtures/utilities.dart
- dwds/test/location_test.dart
- dwds/test/metadata_test.dart
- dwds/test/skip_list_test.dart
- dwds/web/reloader/ddc_library_bundle_restarter.dart
- dwds/web/reloader/ddc_restarter.dart
- dwds/web/reloader/manager.dart
- dwds/web/reloader/require_restarter.dart
- dwds/web/reloader/restarter.dart
- frontend_server_common/lib/src/devfs.dart
Many of the caches we computed on the original load need to be invalidated. Previously, we pessimistically tore down the caches and reinitialized them. With this PR, a ModifiedModuleReport is computed that allows us to only invalidate and recompute information for modules/libraries that were either deleted or reloaded.
Specifically, the caches in `MetadataProvider`, `Modules`, `Locations`, `SkipLists`, `AppInspector`, and `LibraryHelper` are now specially invalidated and recomputed. 
Removes an existing option to use the module URI instead of the module name in the `MetadataProvider`. This option is not relevant until we can unify this change across the ecosystem.
Fixes https://github.com/dart-lang/webdev/issues/2628.
> Invalidate caches after a hot reload

- dwds/test/instances/common/instance_common.dart
- dwds/test/instances/common/patterns_inspection_common.dart
- dwds/test/instances/common/record_type_inspection_common.dart
- dwds/test/instances/common/type_inspection_common.dart
- test_common/lib/utilities.dart
- webdev/test/e2e_test.dart
These calls to `dartSdkIsAtLeast` all refer to old SDK versions and therefore no longer require being checked.
> Remove stale calls to dartSdkIsAtLeast.

- .github/workflows/dart.yml
- dwds/test/fixtures/context.dart
- dwds/test/hot_restart_breakpoints_test.dart
This fixes flakes on the CI for dwds/test/hot_restart_breakpoints_test.dart where a few tests would fail because the ChromeDriver hadn't started up properly yet --- it seemingly takes 200-500 ms for the first launch on github actions.
The test itself was also changed slightly to not give a late initialization error when/if the test times out.
> Fix CI flake in dwds/test/hot_restart_breakpoints_test.dart

- dwds/test/fixtures/project.dart
- dwds/test/instances/common/dot_shorthands_common.dart
- fixtures/_experiment/web/main.dart
- fixtures/_test_dot_shorthands/pubspec.yaml
- fixtures/_test_dot_shorthands/web/index.html
- fixtures/_test_dot_shorthands/web/main.dart
Fixes https://github.com/dart-lang/webdev/issues/2638
Fields are cached after their first execution. When debugging, this means we may not hit the body of the field when using the AMD module format. The DDC library bundle format always has a getter for fields, however, even with the cached value.
To make the test consistent for all formats, we should avoid any previous executions of the field by using an evaluate call instead of a periodic timer in main.
This requires moving the dot shorthands test to its own fixture.
> Use evaluate instead of periodic timer to test dot shorthands
