dart-lang/webdev

.travis.yml
=> Use full VMs on Travis

webdev/test/e2e_test.dart
https://github.com/dart-lang/build/issues/1033 was fixed in build_runner v0.8.9
=> Remove work-around for fixed build_runner issue

webdev/CHANGELOG.md, webdev/README.md, webdev/lib/src/command/build_command.dart, webdev/lib/src/command/command_base.dart, webdev/lib/src/command/serve_command.dart
=> Add default values for output flag.

webdev/CHANGELOG.md, webdev/build.yaml, webdev/dart_test.yaml, webdev/lib/src/version.dart, webdev/lib/src/webdev_command_runner.dart, webdev/pubspec.yaml, webdev/test/ensure_build_test.dart
Fixes https://github.com/dart-lang/webdev/issues/84
=> Add --version to CLI, prepare to release v1

webdev/CHANGELOG.md, webdev/pubspec.yaml
Closes https://github.com/dart-lang/webdev/issues/104
=> Update pubspec and changelog for 2.0.0

webdev/test/handlers/build_results_handler_test.dart
closes https://github.com/dart-lang/webdev/issues/116
=> Reduce AppVeyor flakiness

webdev/lib/src/command/serve_command.dart
Fixes https://github.com/dart-lang/webdev/issues/124
=> Unhide the serve command

.travis.yml, dwds/CHANGELOG.md, dwds/LICENCE, dwds/bin/proxy.dart, dwds/mono_pkg.yaml, dwds/pubspec.yaml, dwds/test/proxy_test.dart, tool/travis.sh
Just gets things started, no actual impl here yet
I added just a couple deps which I know we will have to use eventually, can remove them if we want.
I also added a skeleton for the binary itself and a test, so that I could set up travis.
=> set up skeleton for dwds

dwds/lib/src/chrome_proxy_service.dart, dwds/pubspec.yaml, dwds/test/chrome_proxy_service_test.dart, dwds/test/proxy_test.dart, webdev/lib/src/serve/chrome.dart, webdev/test/chrome_test.dart
Fixes https://github.com/dart-lang/webdev/issues/131
Progress towards https://github.com/dart-lang/webdev/issues/132 as well.
=> Add vm service skeleton

.travis.yml, dwds/mono_pkg.yaml, example/mono_pkg.yaml, webdev/mono_pkg.yaml
This should speed up presubmits a bit and save on resources
=> group analyzer and dartfmt tasks on travis into a single job

dwds/lib/src/chrome_proxy_service.dart, dwds/lib/src/helpers.dart, dwds/test/chrome_proxy_service_test.dart
Part of https://github.com/dart-lang/webdev/issues/158
=> Implement the VM stream, and setName and setVMName

dwds/lib/src/chrome_proxy_service.dart, dwds/pubspec.yaml, dwds/test/chrome_proxy_service_test.dart
Implements basic pause/resume events, part of https://github.com/dart-lang/webdev/issues/166.
=> Implement part of the Debug stream

webdev/README.md, webdev/lib/src/command/build_command.dart, webdev/lib/src/command/serve_command.dart, webdev/lib/src/command/shared.dart, webdev/pubspec.yaml
We have some long descriptions which will otherwise wrap awkwardly in
typical terminal widths.
=> Wrap usage to terminal width

dwds/lib/src/chrome_proxy_service.dart, dwds/pubspec.yaml
feel free to merge this upon approval
=> update to the latest vm_service_lib

webdev/lib/src/serve/daemon_client.dart
Closes https://github.com/dart-lang/webdev/issues/216
=> Consistent pub / dart version

webdev/lib/src/serve/injected/client.dart, webdev/lib/src/serve/injected/client.js
onKeyPress doesn't appear to work properly on linux chrome
=> fix key listeners to use onKeyDown again

webdev/lib/src/serve/handlers/dev_handler.dart, webdev/test/serve/injected/devtools_test.dart
Fixes https://github.com/dart-lang/webdev/issues/227
=> give an explicit error when trying to launch devtools without the --debug flag

dwds/lib/src/chrome_proxy_service.dart
Specifically for evals this will show the actual runtime error message as well as the expression that we attempted to eval.
I also refactored out a large method into smaller methods since I needed to create some local variables that would have had the same name.
=> add better error handling for failures in calls to chrome devtools

webdev/CHANGELOG.md, webdev/lib/src/command/serve_command.dart
Closes https://github.com/dart-lang/webdev/issues/226
=> Only serve web by default

example/web/main.dart, webdev/README.md, webdev/lib/src/command/configuration.dart, webdev/lib/src/command/serve_command.dart, webdev/test/readme_test.dart, webdev/test/serve/injected/reload_test.dart
Fixes https://github.com/dart-lang/webdev/issues/140
cc @kevmoo
=> Add --auto=<option> args which replace --hot-restart and --live-reload

webdev/lib/src/serve/handlers/dev_handler.dart
Stores the connected app ID instead of the service instance which plays nicer with daemon.
=> Fix failure when refreshing the app in daemon mode

dwds/CHANGELOG.md, dwds/pubspec.yaml, webdev/lib/src/version.dart, webdev/pubspec.yaml
I'll publish DWDS as soon as this goes in and follow up with Webdev.
=> Prep to publish alpha

webdev/lib/src/daemon/app_domain.dart
Fixes one of my integration tests 😄
=> Fix typo "Restared" -> "Restarted"

webdev/lib/src/serve/injected/client.js, webdev/web/client.dart
Module names don't have the trailing `.ddc` in kernel mode so we need to look them up slightly differently.
=> fix hot reload in kernel mode

.travis.yml, tool/travis.sh, webdev/CHANGELOG.md, webdev/dart_test.yaml, webdev/lib/src/serve/debugger/webdev_vm_client.dart, webdev/lib/src/serve/injected/client.js, webdev/lib/src/version.dart, webdev/mono_pkg.yaml, webdev/pubspec.yaml, webdev/test/daemon/app_domain_test.dart, webdev/test/daemon/daemon_domain_test.dart, webdev/test/serve/injected/devtools_test.dart, webdev/test/serve/injected/fixtures/web/main.dart, webdev/test/serve/injected/reload_test.dart, webdev/web/client.dart, webdev/web/promise.dart
Fixes https://github.com/dart-lang/webdev/issues/252
=> support invoking the ext.flutter.disassemble extension method before a hot restart

example/pubspec.yaml, webdev/lib/src/pubspec.dart, webdev/test/integration_test.dart
Closes https://github.com/dart-lang/webdev/issues/123
=> Only show daemon issues if build_runner is valid

dwds/test/chrome_proxy_service_test.dart, dwds/test/test_context.dart, webdev/test/serve/injected/fixtures/web/main.dart
Main motivation is so that I can mess with the setup to make it faster without interfering with test changes. If it works well, might parameterize it as an option to the tests.
=> Split the setup out of the proxy service test

.travis.yml, dwds/mono_pkg.yaml, dwds/pubspec.yaml, example/mono_pkg.yaml, example/pubspec.yaml, tool/travis.sh, webdev/lib/src/serve/handlers/dev_handler.dart, webdev/mono_pkg.yaml
Only run dartfmt on dev
For "oldest" SDK – run analyzer without errors for hints/warnings
=> Fix dartfmt of travis

analysis_options.yaml, webdev/lib/src/serve/data/connect_request.dart, webdev/lib/src/serve/data/connect_request.g.dart, webdev/lib/src/serve/data/devtools_request.dart, webdev/lib/src/serve/data/devtools_request.g.dart, webdev/lib/src/serve/data/run_request.dart, webdev/lib/src/serve/data/run_request.g.dart, webdev/pubspec.yaml
Update all code, add associated lint
=> Use latest pkg:built_value_generator which generates new func syntax

dwds/CHANGELOG.md, dwds/lib/service.dart, dwds/pubspec.yaml, dwds/test/chrome_proxy_service_test.dart, dwds/test/debug_service_test.dart, dwds/test/test_context.dart, webdev/CHANGELOG.md, webdev/lib/src/serve/handlers/dev_handler.dart, webdev/lib/src/version.dart, webdev/pubspec.yaml, webdev/test/serve/injected/devtools_test.dart
=> Add a required auth token to web socket uris

dwds/CHANGELOG.md, dwds/lib/src/chrome_proxy_service.dart, dwds/pubspec.yaml, dwds/test/chrome_proxy_service_test.dart
Closes https://github.com/dart-lang/webdev/issues/269
=> Support setExceptionPauseMode

webdev/README.md, webdev/lib/src/command/configuration.dart, webdev/lib/src/command/serve_command.dart
Fixes https://github.com/dart-lang/webdev/issues/275
=> default to use --launch-in-chrome with --debug

webdev/lib/src/command/daemon_command.dart
Fixes https://github.com/dart-lang/webdev/issues/268
=> shut down the daemon if it fails to start up fully

webdev/CHANGELOG.md, webdev/lib/src/pubspec.dart, webdev/lib/src/version.dart, webdev/pubspec.yaml, webdev/test/integration_test.dart
Fixes https://github.com/dart-lang/webdev/issues/277
I also bumped the version for the next alpha release
=> allow build_web_compilers 2.x

webdev/CHANGELOG.md, webdev/lib/src/serve/injected/client.js, webdev/lib/src/version.dart, webdev/pubspec.yaml, webdev/web/reloading_manager.dart
Fixes https://github.com/dart-lang/webdev/issues/285
=> Fix NPE in client.js

webdev/lib/src/daemon/app_domain.dart
Towards https://github.com/dart-lang/webdev/issues/282
=> Log restart events to app.log

webdev/CHANGELOG.md, webdev/lib/src/command/daemon_command.dart, webdev/lib/src/version.dart, webdev/pubspec.yaml
Closes https://github.com/dart-lang/webdev/issues/282
=> Log messages through daemon.log

webdev/lib/src/serve/handlers/dev_handler.dart
fixes https://github.com/dart-lang/webdev/issues/295
=> handle failures to set up the debug service

webdev/lib/src/serve/handlers/dev_handler.dart
Closes https://github.com/dart-lang/webdev/issues/287
=> Open DevTools in a new window

webdev/lib/src/command/serve_command.dart
Towards https://github.com/dart-lang/webdev/issues/329
=> Correctly parse build options

webdev/lib/src/serve/injected/client.js, webdev/pubspec.yaml, webdev/web/client.dart
Fixes #318 
Gives an alert if you do an `alt+d` but is otherwise silent.
=> don't attempt to connect to devtools from non-chrome browsers

.travis.yml, dwds/dart_test.yaml, dwds/example/hello_world/main.dart, dwds/lib/src/chrome_proxy_service.dart, dwds/test/chrome_proxy_service_test.dart, example/mono_pkg.yaml, mono_repo.yaml, webdev/pubspec.yaml
We still can't get static fields/methods or determine if things are const, I filed https://github.com/dart-lang/sdk/issues/36802 to capture some of that.
=> support getting fields for classes

analysis_options.yaml, webdev/CHANGELOG.md, webdev/lib/src/pubspec.dart, webdev/lib/src/version.dart, webdev/pubspec.yaml, webdev/test/integration_test.dart
Towards https://github.com/dart-lang/webdev/issues/359
=> Detect flutter or flutter_test deps and fail eagerly

webdev/lib/src/command/daemon_command.dart
Closes https://github.com/dart-lang/webdev/issues/362
Related to https://github.com/dart-lang/sdk/issues/23074
=> Delay process signal cancellation

appveyor.yml, webdev/lib/src/command/daemon_command.dart, webdev/lib/src/daemon/daemon.dart, webdev/test/serve/chrome_test.dart, webdev/test/serve/injected/injected_fixture.dart
Closes https://github.com/dart-lang/webdev/issues/145
=> Enable Windows testing

dwds/lib/src/dart_uri.dart
Beginnings of a class for converting different representations of a Dart source file
=> Beginnings of a class for converting different representations of a Dart source file

webdev/lib/src/serve/dev_workflow.dart
Towards https://github.com/dart-lang/build/issues/2268
=> Add a line after a build completes

dwds/lib/src/chrome_proxy_service.dart, dwds/pubspec.yaml
=> Add getMemoryUsage, new VM protocol function

webdev/CHANGELOG.md, webdev/lib/src/serve/utils.dart, webdev/lib/src/serve/webdev_server.dart
This should close https://github.com/dart-lang/webdev/issues/412
=> Use HttpMultiServer

webdev/lib/src/serve/dev_workflow.dart
Looks like this logic got lost in the shuffle.
=> Fix Horizontal Line - Account for log level

webdev/CHANGELOG.md, webdev/lib/src/command/serve_command.dart, webdev/lib/src/version.dart, webdev/pubspec.yaml, webdev/test/integration_test.dart
Fixes https://github.com/dart-lang/webdev/issues/385
=> Add an error if there is no directory to serve

dwds/test/test_context.dart, webdev/lib/src/serve/utils.dart, webdev/test/serve/injected/injected_fixture.dart
I believe on AppVeyor we provide a port that isn't suitable for chromedriver. Adding retry logic.
=> Fix AppVeyor Flakiness

dwds/lib/src/chrome_proxy_service.dart, dwds/lib/src/debugger.dart, dwds/test/chrome_proxy_service_test.dart
Still could use tests, but at least other tests exercise it in cleanup.
=> Remove breakpoint

webdev/CHANGELOG.md, webdev/lib/src/serve/injected/client.js, webdev/web/client.dart
Fixes https://github.com/dart-lang/webdev/issues/441
Previously we would always compare against the original state of the app and not the state as of the last hot restart.
=> Fix module diffing/reloading for hot restart

.travis.yml, dwds/mono_pkg.yaml
Closes https://github.com/dart-lang/webdev/issues/353
=> No longer pass -j 1

webdev/lib/src/serve/debugger/webdev_vm_client.dart, webdev/test/serve/injected/injected_fixture.dart, webdev/test/serve/screenshot_test.dart
Fixes https://github.com/dart-lang/webdev/issues/447
=> add ext.webdev.screenshot service extension

dwds/lib/src/handlers/dev_handler.dart
- This is to differentiate between injected SSE handler and Dart Debug Extension SSE handler.
=> Renamed connections to injectedConnections.

dwds/lib/data/devtools_request.dart, dwds/lib/data/devtools_request.g.dart
- This is for background of Dart Debug Extension to send the tab URL to DevHandler.
=> Added tabUrl to DevToolsRequest.

dwds/lib/dwds.dart, dwds/lib/src/handlers/dev_handler.dart, dwds/lib/src/services/chrome_proxy_service.dart, dwds/lib/src/services/debug_service.dart, dwds/test/fixtures/context.dart, dwds/test/fixtures/server.dart
WipDebugger should not be exposed in dwds. It will be created in ChromeProxyService.
=> Removed WipDebugger from dwds.

dwds/lib/src/connections/debug_connection.dart, dwds/lib/src/handlers/dev_handler.dart, dwds/lib/src/services/chrome_proxy_service.dart, dwds/lib/src/services/debug_service.dart, dwds/test/chrome_proxy_service_test.dart, dwds/test/fixtures/context.dart, dwds/test/variable_scope_test.dart
- The purpose is to remove ChromeConnection from ChromeProxyService.
=> Moved logic for creating debugger up to DevHandler.

dwds/debug_extension/web/background.dart, dwds/debug_extension/web/background.js, dwds/lib/data/extension_request.dart, dwds/lib/data/extension_request.g.dart, dwds/lib/src/servers/extension_debugger.dart, dwds/test/extension_debugger_test.dart
- All console events caught in background are now handled with other debugger events (e.g. `Debugger.paused`, `Debugger.resumed`, ...).
- Implemented `eventStream` in `ExtensionDebugger`. This is to handle debugger events.
=> Supported Chrome debugger events.

dwds/debug_extension/web/background.dart, dwds/debug_extension/web/background.js, dwds/lib/data/extension_request.dart, dwds/lib/data/extension_request.g.dart, dwds/lib/data/serializers.dart, dwds/lib/data/serializers.g.dart, dwds/lib/src/servers/extension_debugger.dart, dwds/test/extension_debugger_test.dart
- This is to avoid the complexity of having to serialize parameters of all shapes. One example is when adding a breakpoint, the parameter includes location which is a map.
=>  Changed type of commandParams field of ExtensionRequest to String.

dwds/lib/src/servers/extension_debugger.dart, dwds/test/extension_debugger_test.dart
- Closed sink and streams on error.
- Implemented a getter for scripts.
=> Handled tearing down connections.

dwds/test/chrome_proxy_service_test.dart, dwds/test/fixtures/context.dart, dwds/test/inspector_test.dart
Only instantiate one `ChromeProxyService` for use in tests
=> Use one ChromeProxyService

dwds/debug_extension/web/background.dart, dwds/debug_extension/web/background.js, dwds/lib/src/debugging/remote_debugger.dart, dwds/lib/src/handlers/dev_handler.dart, dwds/lib/src/servers/extension_debugger.dart, dwds/lib/src/services/debug_service.dart, dwds/test/extension_debugger_test.dart
- Cleaned the state of the extension after the app tab is closed.
- Implemented `onClose` for `ExtensionDebugger`.
- Cleaned up after `onClose` in `DevHandler`.
=> Handled Dart Debug Extension state when app tab is closed.

dwds/lib/src/servers/extension_debugger.dart, dwds/lib/src/services/debug_service.dart
- `evaluate` is called when a page is reloaded.
=> Handled reloading app when debugging with the extension.

dwds/debug_extension/web/background.dart, dwds/debug_extension/web/background.js
This is to display a message when `Cancel` is clicked.
=> Handled debugger closed by user.

dwds/debug_extension/web/manifest.json, dwds/lib/src/handlers/dev_handler.dart, dwds/lib/src/services/debug_service.dart
=> useSse if debugging with extension

dwds/test/chrome_proxy_service_test.dart
Mostly manifests when running the tests with Chrome headful
=> Fix race condition in refresh test

webdev/CHANGELOG.md, webdev/lib/src/version.dart, webdev/pubspec.yaml
=> release webdev 2.5.0

dwds/CHANGELOG.md, dwds/lib/src/debugging/debugger.dart, dwds/lib/src/debugging/inspector.dart, dwds/lib/src/debugging/instance.dart, dwds/lib/src/services/chrome_proxy_service.dart, dwds/pubspec.yaml
Closes https://github.com/dart-lang/webdev/issues/592
Closes https://github.com/dart-lang/webdev/issues/588
Closes https://github.com/dart-lang/webdev/issues/587
=> Default some required fields

dwds/test/reload_test.dart
Closes https://github.com/dart-lang/webdev/issues/468
=> Enable skipped Windows tests

_test/pubspec.yaml, dwds/test/chrome_proxy_service_test.dart
Closes https://github.com/dart-lang/webdev/issues/527
=> Fix charset tests

dwds/debug_extension/web/background.dart, dwds/debug_extension/web/background.js, dwds/test/debug_extension_test.dart, dwds/test/fixtures/context.dart
- The developer key is needed to run tests locally.
=> Added E2E tests for Dart Debug Extension.

dwds/debug_extension/web/background.dart, dwds/debug_extension/web/background.js, dwds/debug_extension/web/manifest.json
=> Dart Debug Extension alerts when app is not running

dwds/CHANGELOG.md, dwds/lib/src/debugging/inspector.dart, dwds/pubspec.yaml, dwds/test/chrome_proxy_service_test.dart
This should address https://github.com/dart-lang/webdev/issues/620
=> Add DeclaredType to initial library construct

dwds/lib/src/services/debug_service.dart
=> Close subscription when debug service is stopped.

dwds/CHANGELOG.md, dwds/lib/src/connections/debug_connection.dart, dwds/lib/src/debugging/debugger.dart, dwds/lib/src/debugging/inspector.dart, dwds/lib/src/debugging/instance.dart, dwds/lib/src/dwds_vm_client.dart, dwds/lib/src/services/chrome_proxy_service.dart, dwds/lib/src/services/debug_service.dart, dwds/lib/src/utilities/domain.dart, dwds/lib/src/utilities/shared.dart, dwds/lib/src/utilities/wrapped_service.dart, dwds/pubspec.yaml, dwds/test/fixtures/fakes.dart
Closes https://github.com/dart-lang/webdev/issues/586
=> [WIP] Verify vm protocol objects

dwds/CHANGELOG.md, dwds/lib/src/debugging/debugger.dart, dwds/lib/src/debugging/inspector.dart, dwds/lib/src/debugging/instance.dart, dwds/lib/src/handlers/dev_handler.dart
- Set `exceptionPauseMode`
- Remove some completed TODOs and some duplicate TODOs
Closes https://github.com/dart-lang/webdev/issues/630
=> Set exceptionPauseMode

dwds/CHANGELOG.md, dwds/pubspec.yaml
Closes https://github.com/dart-lang/webdev/issues/634
=> Depend on the latest DevTools

webdev/lib/src/serve/dev_workflow.dart
=> Handled IPv6 localhost for --debug

dwds/CHANGELOG.md, dwds/lib/src/handlers/dev_handler.dart, dwds/lib/src/injected/client.js, dwds/web/client.dart
Closes https://github.com/dart-lang/webdev/issues/637
=> Fix hot restart race condition

dwds/lib/src/services/chrome_proxy_service.dart, dwds/test/chrome_proxy_service_test.dart
Closes https://github.com/dart-lang/webdev/issues/640
=> Implement getFlagList

dwds/lib/dwds.dart, dwds/lib/src/handlers/dev_handler.dart
=> Make DebugConnection from Dart Debug Extension available for Flutter Tools

dwds/CHANGELOG.md, dwds/lib/src/injected/client.js, dwds/pubspec.yaml, dwds/web/client.dart
Closes https://github.com/dart-lang/webdev/issues/610.
Note that the error / stackTrace is not useful in this context so I do not anticipate any issues with this change.
=> Handle SSE client errors

dwds/CHANGELOG.md, dwds/lib/dwds.dart, dwds/lib/src/handlers/dev_handler.dart, dwds/pubspec.yaml, dwds/test/fixtures/context.dart, dwds/test/fixtures/server.dart, dwds/test/reload_test.dart, webdev/CHANGELOG.md, webdev/lib/src/serve/webdev_server.dart, webdev/pubspec.yaml
Closes https://github.com/dart-lang/webdev/issues/647
=> Fix reload / refresh logic when not debugging

dwds/CHANGELOG.md, dwds/lib/src/debugging/sources.dart
Related to https://github.com/dart-lang/webdev/issues/647
Unfortunately I can't provide a solid test given that this is a race condition.
=> Quick refresh fix

example/web/main.dart, example/web/scopes_main.dart, webdev/lib/src/serve/chrome.dart
The lack of these is causing Travis to fail.
=> Use more const constructors

dwds/CHANGELOG.md, dwds/lib/src/services/chrome_proxy_service.dart, dwds/pubspec.yaml
Towards https://github.com/dart-lang/webdev/issues/655
=> Handle null description

dwds/lib/dwds.dart
Prevent null boolean expression.
=> Default serve DevTools value

dwds/CHANGELOG.md, dwds/lib/src/debugging/sources.dart, dwds/lib/src/utilities/dart_uri.dart, dwds/test/dart_uri_test.dart
- Conditionally run the record URI logic
- Support DDK source map extensions
- Parse Google3 URI schemes
=> DDK Source Maps and Google3 fixes

dwds/CHANGELOG.md, dwds/lib/src/debugging/debugger.dart
Fixes https://github.com/dart-lang/webdev/issues/691
=> fix handling of chrome pause events when we have no app loaded

dwds/lib/src/debugging/debugger.dart, dwds/lib/src/debugging/instance.dart, dwds/test/fixtures/fakes.dart
=> Fix two null errors in toJson of vm protocol objects

dwds/CHANGELOG.md, dwds/pubspec.yaml, dwds/web/reloader/manager.dart
Part of https://github.com/dart-lang/webdev/issues/697
=> dont try to create a new isolate if the hot restart fails

dwds/lib/src/debugging/debugger.dart, dwds/lib/src/debugging/inspector.dart, dwds/lib/src/debugging/sources.dart, dwds/lib/src/utilities/dart_uri.dart, dwds/test/chrome_proxy_service_test.dart, dwds/test/dart_uri_file_uri_test.dart, dwds/test/dart_uri_test.dart, dwds/test/variable_scope_test.dart
Not cleaned up for review yet, just want to run it through Travis.
=> Fixing some Windows problems

dwds/lib/src/debugging/debugger.dart, dwds/test/debugger_test.dart, dwds/test/fixtures/fakes.dart
=> Wrap a zone exception handler around our Chrome event handlers

dwds/CHANGELOG.md, dwds/lib/data/isolate_events.dart, dwds/lib/data/isolate_events.g.dart, dwds/lib/data/run_request.dart, dwds/lib/data/run_request.g.dart, dwds/lib/src/debugging/inspector.dart, dwds/lib/src/handlers/dev_handler.dart, dwds/lib/src/injected/client.js, dwds/lib/src/services/chrome_proxy_service.dart, dwds/lib/src/services/debug_service.dart, dwds/pubspec.yaml, dwds/test/chrome_proxy_service_test.dart, dwds/test/run_request_test.dart, dwds/web/client.dart, dwds/web/reloader/manager.dart
- Promote the `AppConnection` abstraction to be used more throughout the dev_handler
- This allows us to remove unnecessary data from some of the client requests
- Pass `AppConnection` to the `createIsolate` request
- Add `AppConnection` to the `AppInspector`
- Use `AppConnection`'s run state to correctly resume while "paused" at start
- Add corresponding test
Closes https://github.com/dart-lang/webdev/issues/716
=> Better Resuming

dwds/CHANGELOG.md, dwds/lib/dwds.dart
towards https://github.com/dart-lang/webdev/issues/737
=> expose the ChromeDebugException class

dwds/CHANGELOG.md, dwds/lib/dwds.dart, dwds/lib/src/handlers/dev_handler.dart
Towards https://github.com/flutter/flutter/issues/40535
=> Expose app connection exception

dwds/test/chrome_proxy_service_test.dart
Related to: https://github.com/dart-lang/webdev/issues/721
=> Skip flaky test

webdev/lib/src/daemon/app_domain.dart
Adds proper support for multiple serve directories in daemon mode.
While unused it would allow it before but only would respond to app connection requests from the first server - this keeps the support and listens for app connections on all servers.
=> support multiple serve dirs and apps in daemon mode

dwds/CHANGELOG.md, dwds/lib/src/debugging/debugger.dart, dwds/test/chrome_proxy_service_test.dart
Closes https://github.com/dart-lang/webdev/issues/739
=> Set pauseBreakpoints

dwds/lib/src/debugging/debugger.dart, dwds/test/chrome_proxy_service_test.dart
Closes https://github.com/dart-lang/webdev/issues/740
Towards https://github.com/dart-lang/webdev/issues/756
=> Throw proper error for breakpoints

webdev/lib/src/serve/chrome.dart, webdev/pubspec.yaml
…l/14 and a version 0.1.5 published that contains it
=> Launch Chrome from the same directory

dwds/CHANGELOG.md, dwds/pubspec.yaml
Forgot to add a changelog entry for https://github.com/dart-lang/webdev/pull/768
=> Prep to publish

dwds/CHANGELOG.md, dwds/lib/src/debugging/modules.dart, dwds/pubspec.yaml
- Add support for the legacy module system
- Clean up logic so that the module key and values are consistent
=> Legacy module support

dwds/CHANGELOG.md, dwds/lib/src/debugging/instance.dart, dwds/pubspec.yaml, dwds/test/instance_test.dart, example/web/scopes_main.dart
=> Handle Map values that are JSON-serializable in JS (e.g. list of int)

webdev/CHANGELOG.md, webdev/lib/src/command/daemon_command.dart, webdev/test/integration_test.dart
Closes https://github.com/dart-lang/webdev/issues/765
=> Update daemon pubspec validation

dwds/CHANGELOG.md, dwds/lib/src/debugging/inspector.dart, dwds/lib/src/debugging/instance.dart, dwds/lib/src/utilities/conversions.dart, dwds/pubspec.yaml, dwds/test/chrome_proxy_service_test.dart
=> Handle getObject for primitives properly

dwds/lib/src/debugging/inspector.dart, dwds/lib/src/services/chrome_proxy_service.dart, dwds/test/fixtures/fakes.dart
Related: https://github.com/dart-lang/webdev/issues/798
Closes: https://github.com/dart-lang/webdev/issues/793
=> Ignore disableBreakpoints

dwds/CHANGELOG.md, dwds/debug_extension/web/background.dart, dwds/debug_extension/web/background.js, dwds/debug_extension/web/manifest.json, dwds/lib/dwds.dart, dwds/lib/src/handlers/dev_handler.dart, dwds/lib/src/handlers/injected_handler.dart, dwds/pubspec.yaml, dwds/test/debug_extension_test.dart, dwds/test/fixtures/context.dart, dwds/test/fixtures/server.dart, dwds/test/handlers/injected_handler_test.dart
- Update the extension to expect an embedded URI instead of composing one from parts
- Add support of an optional argument that provides support of encoding remote URLs
- Encode the extension URI and corresponding debug service URI
=> Support encoding URLs

dwds/CHANGELOG.md, dwds/lib/src/debugging/classes.dart, dwds/test/inspector_test.dart, dwds/test/instance_test.dart, example/web/scopes_main.dart
Closes https://github.com/dart-lang/webdev/issues/795
=> Fix getObject with generic classes

webdev/lib/src/serve/chrome.dart, webdev/pubspec.yaml
Let's see if this works after #770
=> Retry Launch Chrome from the same directory

dwds/CHANGELOG.md, dwds/lib/dwds.dart, dwds/lib/src/debugging/debugger.dart, dwds/lib/src/dwds_vm_client.dart, dwds/lib/src/handlers/dev_handler.dart, dwds/lib/src/services/chrome_proxy_service.dart, dwds/lib/src/services/debug_service.dart, dwds/pubspec.yaml, dwds/test/fixtures/context.dart, dwds/test/fixtures/server.dart, dwds/test/restore_breakpoints_test.dart
Temporary solution to: https://github.com/flutter/devtools/issues/1263
=> Restore Breakpoints

dwds/debug_extension/web/background.dart, dwds/debug_extension/web/background.js, dwds/debug_extension/web/manifest.json
Closes https://github.com/dart-lang/webdev/issues/794
=> Close connection on error

dwds/CHANGELOG.md, dwds/lib/dwds.dart, dwds/lib/src/debugging/modules.dart, dwds/lib/src/handlers/dev_handler.dart, dwds/pubspec.yaml, dwds/test/debug_extension_test.dart, webdev/CHANGELOG.md, webdev/lib/src/serve/webdev_server.dart
Closes https://github.com/dart-lang/webdev/issues/669
=> Optionally serve DevTools with the Dart Debug Extension

.travis.yml, dwds/mono_pkg.yaml, tool/travis.sh, webdev/mono_pkg.yaml
This should help catch these earlier before running all the other tests.
=> run build tests during analyze/format stage

dwds/debug_extension/CHANGELOG.md, dwds/debug_extension/pubspec.yaml, dwds/debug_extension/web/background.dart, dwds/debug_extension/web/background.js, dwds/lib/src/debugging/execution_context.dart
Looks like we weren't properly handling errors with the debug extension workflow.
See:
https://developer.chrome.com/extensions/debugger#method-sendCommand
=> Handle remote errors

dwds/debug_extension/web/manifest.json
This was missed in https://github.com/dart-lang/webdev/pull/852
=> Update Extension Version

dwds/lib/src/debugging/modules.dart, dwds/test/debugging/modules_test.dart
Also add some tests for previous module logic.
=> Handle Google3 Module Paths

.travis.yml, dwds/test/fixtures/context.dart, tool/travis_setup.sh, webdev/test/integration_test.dart
- Use latest ChromeDriver due to Chrome update
- Add `.dart_too/package_config` due to SDK update
=> Fix failing tests at head

dwds/CHANGELOG.md, dwds/lib/src/debugging/metadata.dart, dwds/test/debugging/metadata_test.dart
Closes https://github.com/dart-lang/webdev/issues/836
=> Correctly parse length

.travis.yml, webdev/CHANGELOG.md, webdev/lib/src/pubspec.dart, webdev/lib/src/version.dart, webdev/mono_pkg.yaml, webdev/pubspec.yaml, webdev/test/integration_test.dart
Closes https://github.com/dart-lang/webdev/issues/867
Version number negotiable :D
=> require the latest build_web_compilers

dwds/CHANGELOG.md, dwds/lib/src/debugging/location.dart
@grouma I think this is the right place to fix it, though I'm not certain it shouldn't be done "earlier" so let me know if it doesn't seem right.
Fixes #874.
=> Normalise URLs that may contain "../"

dwds/debug_extension/CHANGELOG.md, dwds/debug_extension/pubspec.yaml, dwds/debug_extension/web/background.dart, dwds/debug_extension/web/background.js, dwds/debug_extension/web/manifest.json
It looks like Chrome prevents getting tab information for a subset of tabs, e.g. GMail or Chrome://. Handle related errors to provide the proper alert message.
=> Proper alert for non-dart apps

dwds/debug_extension/web/background.js
Looks like the extension wasn't built with the latest edits in https://github.com/dart-lang/webdev/pull/883
=> Build extension

dwds/lib/src/debugging/dart_scope.dart
This was unintentionally removed in https://github.com/dart-lang/webdev/pull/906
=> Add back comment

.travis.yml, dwds/mono_pkg.yaml, dwds/test/inspector_test.dart, dwds/test/instance_test.dart, example/mono_pkg.yaml, example/pubspec.yaml, tool/travis.sh, webdev/mono_pkg.yaml
Remove Angular from the critical path and skip tests broken with the dev SDK.
=> Run on dev and 2.6.0

dwds/lib/src/services/chrome_proxy_service.dart, dwds/pubspec.yaml, dwds/test/chrome_proxy_service_test.dart, dwds/test/reload_test.dart, webdev/pubspec.yaml
Eventually we'll want to support client names but I do not believe they are used anywhere at this point in time.
=> Depend on the latest vm_service

.travis.yml, dwds/mono_pkg.yaml, frontend_server_common/lib/src/resident_runner.dart, tool/travis.sh
Closes https://github.com/dart-lang/webdev/issues/911
=> Enable Frontend Server Tests

webdev/CHANGELOG.md, webdev/lib/src/version.dart, webdev/pubspec.yaml, webdev/test/daemon/app_domain_test.dart
Change which test is skipped as I now have a better understanding of the issue. It'll require a fix to `package:dwds`.
=> Fix vm service constraint

dwds/CHANGELOG.md, dwds/lib/src/dwds_vm_client.dart
Likely closes https://github.com/dart-lang/webdev/issues/947
=> Check for empty isolate refs

dwds/CHANGELOG.md, dwds/lib/src/debugging/modules.dart, dwds/lib/src/version.dart, dwds/pubspec.yaml
This has a more explicit intent than using a completer.
=> Use AsyncMemoizer to run initalization code once

dwds/CHANGELOG.md, dwds/debug_extension/pubspec.yaml, dwds/lib/src/handlers/dev_handler.dart, dwds/pubspec.yaml, dwds/test/fixtures/fakes.dart, webdev/pubspec.yaml
This allows bypassing the keep-alive period and fixes #950.
@grouma
=> Switch to telling SseHandler to shutdown instead of closing each connection

frontend_server_client/example/app/main.dart, frontend_server_client/example/client.dart, frontend_server_client/lib/src/frontend_server_client.dart, frontend_server_client/pubspec.yaml
Going to follow up with a PR adding tests.
Adds an example app and get things generally working, including an example of doing an incremental recompile + hot restart on the VM.
=> Initial implementation of frontend_server_client

dwds/debug_extension/web/background.dart, dwds/lib/src/debugging/inspector.dart, dwds/lib/src/services/chrome_proxy_service.dart, dwds/test/chrome_proxy_service_test.dart
- implement `getSourceReport`
- related to https://github.com/dart-lang/webdev/issues/970 (through I don't want to close that issue out as there is a more accurate way to implement this feature)
=> implement getSourceReport

frontend_server_client/lib/src/frontend_server_client.dart, frontend_server_client/pubspec.yaml, frontend_server_client/test/frontend_sever_client_test.dart
Essentially this just duplicates what the example does, it compiles a vm app and runs it, and then does an incremental compile + hot reload.
=> add a vm integration test

dwds/CHANGELOG.md
- add an entry to the changelog for `getSourceReport()`
=> add an entry to the changelog

dwds/CHANGELOG.md, dwds/lib/src/debugging/debugger.dart
Towards https://github.com/dart-lang/webdev/issues/993
=> Compute only the required top frame

dwds/lib/src/debugging/debugger.dart
- fix a todo: related to frame indexes (pass the frame index in at `Frame` construction time)
- remove the `[_frameName]` square braces surrounding some DDC compiled method names (generally private names?)
=> fix a todo: related to frame indexes

dwds/lib/src/debugging/metadata/class.dart
- remove a todo related to a performance investigation (see https://github.com/dart-lang/webdev/issues/993#issuecomment-645604496 for context)
=> remove a todo

dwds/CHANGELOG.md, dwds/lib/src/readers/proxy_server_asset_reader.dart
Closes https://github.com/dart-lang/webdev/issues/1112
=> HTTPs in ProxyServerAssetReader

.travis.yml, dwds/mono_pkg.yaml, dwds/pubspec.yaml, frontend_server_common/mono_pkg.yaml, webdev/CHANGELOG.md, webdev/lib/src/command/serve_command.dart, webdev/mono_pkg.yaml, webdev/pubspec.yaml
https://github.com/dart-lang/webdev/pull/1095 caused some issues and was merged on red. Clean up some of those issues. Note we are still waiting on https://github.com/dart-lang/webdev/pull/1115 to fully resolve issues at HEAD.
=> Update min SDK and deps

dwds/test/debug_service_test.dart
Related: https://github.com/dart-lang/webdev/issues/1119
=> Temporarily skip DDS test

dwds/lib/src/dwds_vm_client.dart
Towards https://github.com/flutter/flutter/issues/60495 (once this change is rolled into Flutter master)
I'm able to reproduce the error outlined in the above issue. To do so, a user must trigger a full refresh then a hot restart in the middle of the load. Since the application is not fully loaded, we don't have an execution context and therefore can't properly complete the hot restart. Instead of simply throwing an uncaught exception, catch this issue and return an appropriate RPC error response.
cc @jonahwilliams
=> Handle Execution Context Errors During hotRestart

dwds/lib/src/services/expression_compiler_service.dart
- Construct the `StreamQueue` earlier. This avoids needing to also use
`asBroadcastStream`.
- Use `Object` over `dynamic`.
- Rename a `_getResposne` to `_send`. Puts the side effect as the
important word and avoids violating https://dart.dev/guides/language/effective-dart/design#avoid-starting-a-method-name-with-get
- Avoid an unnecessary `Future.value` inside an `async` method.
- Move the cast to `Map<String, Object>` to the method so it doesn't
need to be repeated at both callsites.
- Remove unnecessary parens.
=> Avoid using broadcast stream before a StreamQueue

dwds/web/reloader/manager.dart
As of Dart 2.1, Future/Stream have been exported from dart:core.
=> Remove unused dart:async imports.

dwds/CHANGELOG.md, dwds/lib/src/dwds_vm_client.dart, dwds/lib/src/handlers/injector.dart, webdev/lib/src/logging.dart
- Add verbose logging to a handful of locations
- Fix webdev log formatting
Towards https://github.com/dart-lang/webdev/issues/1136
=> Improved logging

dwds/CHANGELOG.md, dwds/lib/src/services/chrome_proxy_service.dart, dwds/lib/src/version.dart, dwds/pubspec.yaml
Closes https://github.com/dart-lang/webdev/issues/771
=> Handle null inspector during resume

dwds/CHANGELOG.md, dwds/lib/src/dwds_vm_client.dart, dwds/lib/src/loaders/require.dart, dwds/lib/src/version.dart, dwds/pubspec.yaml
This would have helped diagnose and root cause https://github.com/flutter/flutter/issues/69263. Once this lands and is pulled into Flutter Tools, we will at least fall back to a full reload and log a proper error message.
=> Improved error handling and logging

dwds/CHANGELOG.md, dwds/lib/src/debugging/debugger.dart, dwds/test/chrome_proxy_service_test.dart
Closes https://github.com/dart-lang/webdev/issues/1188
=> Fix multiple breakpoints

dwds/CHANGELOG.md, dwds/lib/src/debugging/frame_computer.dart
Make the recursive calls iterative so we don't have a stack overflow on highly nested JS calls.
=> Handle highly nested frames

dwds/CHANGELOG.md, dwds/lib/src/handlers/dev_handler.dart, dwds/lib/src/services/debug_service.dart
=> Log the encoded URI

dwds/lib/src/handlers/dev_handler.dart
Implement a stream transform to take events until there is a long enough
gap between events. This avoids waiting to start work for one context
until all the IDs are read.
=> Remove timeout for first context

dwds/pubspec.yaml
This dependency was added in #902 but never used.
=> Remove unused dependency sync_http

.github/workflows/dart.yml, dwds/CHANGELOG.md, dwds/lib/src/dwds_vm_client.dart, dwds/lib/src/services/chrome_proxy_service.dart, dwds/mono_pkg.yaml, dwds/pubspec.yaml, frontend_server_common/mono_pkg.yaml, webdev/CHANGELOG.md, webdev/mono_pkg.yaml, webdev/pubspec.yaml, webdev/test/e2e_test.dart
Related issue: https://github.com/dart-lang/webdev/issues/1232
=> Depend on vm_service 6.0.1-nullsafety.0

dwds/CHANGELOG.md, dwds/debug_extension/CHANGELOG.md, dwds/debug_extension/pubspec.yaml, dwds/debug_extension/web/background.dart, dwds/debug_extension/web/background.js, dwds/debug_extension/web/manifest.json, dwds/pubspec.yaml, dwds/web/client.dart, webdev/pubspec.yaml
`onOpen` is now deprecated an not necessary. `package:sse` will buffer requests until the connection is established.
=> Depend on the latest package:sse

dwds/debug_extension/CHANGELOG.md, dwds/debug_extension/pubspec.yaml, dwds/debug_extension/web/background.js, dwds/debug_extension/web/manifest.json
Update to the latest `package:sse` which includes a fix for the `onDone` event. See https://github.com/dart-lang/sse/pull/39
=> Update package:sse in the extension

.github/workflows/dart.yml, frontend_server_client/example/vm_client.dart, frontend_server_client/example/web_client.dart, frontend_server_client/lib/src/dartdevc_bootstrap_amd.dart, frontend_server_client/lib/src/dartdevc_frontend_server_client.dart, frontend_server_client/lib/src/frontend_server_client.dart, frontend_server_client/lib/src/shared.dart, frontend_server_client/mono_pkg.yaml, frontend_server_client/pubspec.yaml, frontend_server_client/test/frontend_sever_client_test.dart, tool/ci.sh
* Fixes several issues where paths were used instead of URIs
* fixes incorrect default for SDK path
* Fixes tests to run on windows
=> migrate frontend_server_client to null safety

dwds/CHANGELOG.md
@grouma I didn't include this in the previous PR. I've added a 9.1.0-dev though I'm not sure if that's the likely next version - let me know if it should be something different.
=> Add changelog note for WebSockets

dwds/pubspec.yaml
cc @jonahwilliams 
cc @kenzieschmoll 
Towards https://github.com/flutter/flutter/issues/77856
=> Support more packages

frontend_server_client/CHANGELOG.md, frontend_server_client/lib/src/dartdevc_frontend_server_client.dart, frontend_server_client/pubspec.yaml, frontend_server_client/test/frontend_sever_client_test.dart
@jonahwilliams PTAL as well for the SDK constraint widening.
=> widen the sdk constraint and fix a couple typos

dwds/lib/src/injected/client.js, dwds/web/reloader/require_restarter.dart
This was broken with https://github.com/dart-lang/webdev/pull/1285. We merged that PR since I thought the flakes were due to recent Github Action / Pub issues. Will wait for a green run before merging this as all tests should now be passing.
=> Fix hot restart / reload tests

dwds/debug_extension/web/manifest.json
Forgot to update this in https://github.com/dart-lang/webdev/pull/1309
=> Update debug extension manifest version

frontend_server_client/pubspec.yaml
Just making it easier to find the sources :D
=> Add homepage and repository

dwds/CHANGELOG.md, dwds/debug_extension/CHANGELOG.md, dwds/debug_extension/pubspec.yaml, dwds/debug_extension/web/background.js, dwds/debug_extension/web/manifest.json, dwds/lib/src/debugging/classes.dart, dwds/lib/src/debugging/debugger.dart, dwds/lib/src/injected/client.js, dwds/lib/src/services/chrome_proxy_service.dart, dwds/lib/src/version.dart, dwds/pubspec.yaml, webdev/CHANGELOG.md, webdev/lib/src/version.dart, webdev/pubspec.yaml, webdev/test/chrome_test.dart
To rev to the latest `package:sse` we needed to roll a bunch of other packages as well. This change should help with the stability of the Dart Debug Extension connection.
=> Rev package:sse version

.github/workflows/dart.yml, dwds/mono_pkg.yaml, example/mono_pkg.yaml, fixtures/_webdevSmoke/mono_pkg.yaml, frontend_server_client/mono_pkg.yaml, frontend_server_common/mono_pkg.yaml, tool/ci.sh, webdev/mono_pkg.yaml
Not sure what's going on with the test failures; looks like they also happened here:
https://github.com/dart-lang/webdev/runs/2811562867?check_suite_focus=true
=> Upgrade CI with mono_repo 5.0

dwds/test/events_test.dart
=> format with the latest sdk

dwds/test/events_test.dart, fixtures/_webdevSmoke/pubspec.yaml, webdev/CHANGELOG.md, webdev/lib/src/version.dart, webdev/pubspec.yaml
Update dwds and webdev version
=> Prepare to publish webdev

dwds/README.md, dwds/lib/src/debugging/debugger.dart, dwds/lib/src/debugging/location.dart
/cc @devoncarew @annagrin @grouma
=> SDK master=>main default branch migration

webdev/CHANGELOG.md, webdev/lib/src/version.dart, webdev/pubspec.yaml
- Updated version to `2.7.7`
- Updated changelog to include latest changes.
- Depend on dwds version `11.5.1`
=> Prepare to publsih webdev

dwds/CHANGELOG.md, dwds/lib/src/version.dart, dwds/pubspec.yaml
Follow-up to https://github.com/dart-lang/webdev/pull/1510.
=> Update dwds changelog and version

dwds/CHANGELOG.md, dwds/lib/src/dwds_vm_client.dart, dwds/lib/src/events.dart, dwds/lib/src/handlers/dev_handler.dart, dwds/test/events_test.dart
Closes: https://github.com/dart-lang/webdev/issues/1551
=> Add screen field to DebuggerReady event

dwds/CHANGELOG.md, dwds/lib/src/version.dart, dwds/pubspec.yaml
=> Prep to publish dwds 13.0.0

dwds/CHANGELOG.md, dwds/lib/src/version.dart, dwds/pubspec.yaml
Prep to publish dwds 14.0.1
Towards: https://github.com/dart-lang/sdk/issues/48754
=> Prep to publish dwds 14.0.1

dwds/analysis_options.yaml, dwds/lib/src/handlers/dev_handler.dart, dwds/lib/src/servers/extension_backend.dart, dwds/pubspec.yaml, dwds/test/chrome_proxy_service_test.dart, dwds/test/readers/frontend_server_asset_reader_test.dart
Work towards https://github.com/dart-lang/webdev/issues/1644
Adds the lints recommended in `package:lints` and applies them.
=> Add recommended lints to DWDS

dwds/CHANGELOG.md, dwds/lib/src/version.dart, dwds/pubspec.yaml
Work towards https://github.com/dart-lang/webdev/issues/1632
=> Prep DWDS 15.0.0 for release

frontend_server_client/CHANGELOG.md, frontend_server_client/pubspec.yaml
unblocks https://github.com/dart-lang/pub/pull/3514
=> publish frontend_server_client

dwds/test/listviews_test.dart
See https://github.com/dart-lang/webdev/issues/1741
Note: Formatting changes due to running `dart format` on file
=> Temporarily disable `listview_test.dart` 

dwds/debug_extension/web/background.dart, dwds/lib/src/services/expression_evaluator.dart, dwds/web/client.dart
Follow up for   https://github.com/dart-lang/webdev/pull/1746
- Add issue references in comments for  issues discovered in the PR above
- Remove unused library
=> Added issue references and removed unused library

dwds/debug_extension_mv3/web/web_api.dart
Initially caught in `package:sse`,  this is the same fix: https://github.com/dart-lang/sse/pull/69
=> Fix implementation of the Fetch API 

dwds/test/events_test.dart
Work towards https://github.com/dart-lang/webdev/issues/1852
=> Skip flaky `events_test` on Windows

dwds/debug_extension_mv3/web/manifest.json
Ran the auto-formatter on the `manifest`
=> [MV3] Format the `manifest.json`

webdev/CHANGELOG.md, webdev/lib/src/version.dart, webdev/pubspec.yaml
Work towards https://github.com/dart-lang/webdev/issues/1918, https://github.com/dart-lang/webdev/issues/1878
=> Prepare Webdev for `3.0.0` release

dwds/lib/src/debugging/classes.dart, dwds/lib/src/debugging/debugger.dart, dwds/test/chrome_proxy_service_test.dart
Fixes https://github.com/dart-lang/webdev/issues/1971
=> Ignore offset / count if an instance has no `length` 

.github/workflows/publish.yaml
See details in: https://github.com/dart-lang/webdev/issues/1995
=> Temporarily disable publish verification

.github/labeler.yml, .github/workflows/dart.yml, .github/workflows/pull_request_label.yml
Related to https://github.com/dart-lang/setup-dart/issues/79, dogfood the new version of the `setup-dart` action.
=> dogfood the new setup-dart action

example/pubspec.yaml, test_common/pubspec.yaml, webdev/CHANGELOG.md, webdev/lib/src/version.dart, webdev/pubspec.yaml
Work towards https://github.com/dart-lang/sdk/issues/51732
=> Prepare Webdev version `3.0.2` for release

.github/workflows/dart.yml, tool/ci.sh
Unblocks https://github.com/dart-lang/webdev/pull/2066:
Also work towards https://github.com/dart-lang/webdev/issues/2053
=> Run `mono_repo generate` to update Github config

.github/workflows/dart.yml, tool/ci.sh
Unblocks https://github.com/dart-lang/webdev/pull/2066
=> Run `mono_repo generate` with version 6.5.3

dwds/lib/src/debugging/debugger.dart, dwds/lib/src/debugging/frame_computer.dart, dwds/lib/src/debugging/inspector.dart, dwds/lib/src/handlers/dev_handler.dart
- Preparatory work for https://github.com/dart-lang/webdev/pull/2092
- Work towards https://github.com/dart-lang/webdev/issues/2053
=> Fix DCM analyzer warnings

.github/workflows/dcm.yml
=> Syntax error in DCM workflow file

.github/workflows/dart.yml, tool/ci.sh
- re-generate w/ the latest monorepo
---
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
(note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some …
=> re-generate w/ the latest monorepo

dwds/test/evaluate_common.dart
Added and used a bunch of helpers in expression evaluation tests. Note that the test behavior is not changed.
=> Cleanup expression evaluation tests

dwds/lib/src/services/expression_evaluator.dart
=> Remove unnecessary `async` keywords

dwds/CHANGELOG.md, dwds/lib/src/services/chrome_proxy_service.dart
Fixes https://github.com/dart-lang/webdev/issues/2133
=> Catch `WipError` on calls to resume and map to appropriate RPC error code

dwds/debug_extension_mv3/pubspec.yaml, dwds/debug_extension_mv3/web/manifest_mv2.json, dwds/debug_extension_mv3/web/manifest_mv3.json
- Follow up to https://github.com/dart-lang/webdev/pull/2136
=> Update Dart Debug Extension version in preparation for publishing

dwds/lib/src/debugging/debugger.dart, dwds/lib/src/debugging/inspector.dart, dwds/lib/src/dwds_vm_client.dart, dwds/lib/src/services/chrome_proxy_service.dart, dwds/lib/src/utilities/domain.dart, dwds/pubspec.yaml, dwds/test/chrome_proxy_service_test.dart
Work towards https://github.com/dart-lang/webdev/issues/2140
The changes in https://github.com/dart-lang/sdk/commit/66ded0cdd94afaa0bb4604bb09e8bbca9fcb32dc have been published in `vm_service` v.11.7.1.
=> Use new error codes from `package:vm_service`

dwds/CHANGELOG.md, dwds/lib/src/services/chrome_proxy_service.dart
Fixes https://github.com/dart-lang/webdev/issues/2161
=> Handle potential `null` value in `setUpChromeConsoleListeners`

.github/workflows/dart.yml, tool/ci.sh
- regenerate from the latest mono_repo
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
Note that many Dart repos have a …
=> regenerate from the latest mono_repo

dwds/test/instances/common/test_inspector.dart, dwds/test/instances/instance_inspection_test.dart, dwds/test/instances/patterns_inspection_test.dart, dwds/test/instances/record_inspection_test.dart, dwds/test/instances/record_type_inspection_test.dart, dwds/test/instances/type_inspection_test.dart
Refactor instance tests in preparation for adding canary mode tests.
Towards: https://github.com/dart-lang/webdev/issues/2175
=> Refactor instance tests

.github/workflows/daily_testing.yml, .github/workflows/dart.yml, .github/workflows/dcm.yml, .github/workflows/release_reminder.yml
- rev to a pre-release of the setup-dart action in order to test it
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
Note …
=> test the latest setup-dart action

.github/workflows/dart.yml, tool/ci.sh
- regenerate from the latest package:mono_repo
---
<details>
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).
Note that many Dart repos …
=> regenerate from the latest package:mono_repo

dwds/debug_extension_mv3/web/cider_connection.dart, dwds/debug_extension_mv3/web/debug_session.dart
=> Send the Flutter inspector URL to Cider when requested 

dwds/debug_extension_mv3/web/cider_connection.dart
=> Send a "pong" response when Cider "pings" the Dart Debug Extension

dwds/CHANGELOG.md, dwds/lib/src/debugging/dart_scope.dart, dwds/lib/src/debugging/debugger.dart, dwds/lib/src/debugging/inspector.dart, dwds/lib/src/debugging/instance.dart, dwds/lib/src/debugging/metadata/provider.dart, dwds/lib/src/services/chrome_proxy_service.dart, dwds/test/evaluate_common.dart, dwds/test/inspector_test.dart, dwds/test/instances/common/instance_inspection_common.dart, dwds/test/instances/common/patterns_inspection_common.dart, dwds/test/instances/common/record_type_inspection_common.dart, dwds/test/instances/common/test_inspector.dart, dwds/test/instances/common/type_inspection_common.dart, dwds/test/variable_scope_test.dart, fixtures/_test/example/scopes/main.dart
Cherry-picks the following changes on top of 23.0.0:
- https://github.com/dart-lang/webdev/pull/2348
- https://github.com/dart-lang/webdev/pull/2343
- https://github.com/dart-lang/webdev/pull/2352 (skip record type inspection tests)
=> Prepare DWDS 23.0.0+1 hotfix

frontend_server_client/CHANGELOG.md, frontend_server_client/pubspec.yaml
Can be merged once https://github.com/dart-lang/webdev/pull/2392 is submitted
=> Prepare frontend_server_client for release to version 4.0.0

dwds/debug_extension_mv3/pubspec.yaml, dwds/debug_extension_mv3/web/cider_connection.dart, dwds/debug_extension_mv3/web/manifest_mv3.json, dwds/debug_extension_mv3/web/popup.dart, dwds/lib/src/services/chrome_proxy_service.dart
This is used by Cider to determine which DevTools panels to show
=> Indicate whether an app is a Flutter app via the app ID

dwds/test/variable_scope_test.dart
See https://github.com/dart-lang/webdev/issues/2469
=> Disable `variable scope variables in function` in `variable_scope_test.dart`

.github/workflows/daily_testing.yml, dwds/test/build_daemon_evaluate_test.dart, dwds/test/chrome_proxy_service_test.dart, dwds/test/expression_compiler_service_test.dart, dwds/test/frontend_server_ddc_evaluate_test.dart, dwds/test/frontend_server_evaluate_test.dart, dwds/test/instances/class_inspection_test.dart, dwds/test/instances/instance_canary_test.dart, dwds/test/instances/instance_inspection_canary_test.dart, dwds/test/instances/instance_inspection_test.dart, dwds/test/instances/instance_test.dart, dwds/test/instances/patterns_inspection_canary_test.dart, dwds/test/instances/patterns_inspection_test.dart, dwds/test/instances/record_inspection_canary_test.dart, dwds/test/instances/record_inspection_test.dart, dwds/test/instances/record_type_inspection_canary_test.dart, dwds/test/instances/record_type_inspection_test.dart, dwds/test/instances/type_inspection_canary_test.dart, dwds/test/instances/type_inspection_test.dart, dwds/test/objects_test.dart, dwds/test/reload_correctness_test.dart, dwds/test/reload_test.dart, webdev/test/installation_test.dart
=> Revert "Update daily testing to run the entire test suite"

test_common/lib/sdk_asset_generator.dart, test_common/lib/test_sdk_layout.dart
Use AOT snapshot of kernel_worker
=> Use AOT snapshot of kernel_worker
